### Import libaries

In [1]:
import os
import sys
import subprocess
import importlib
sys.path.append('DescriPyTor')

import pandas as pd
import numpy as np
from tqdm import tqdm

from datetime import datetime
from pathlib import Path

from desc_utils import atom_numbering as an
from desc_utils import orca_descriptors as od

ROOT_DIR = os.getcwd()
print(f"Current working directory: {ROOT_DIR}")

Current working directory: /Users/julesschleinitz/Desktop/Code/orca_descriptors

### Define the source directory containing the orca and xyz files

Provide path to directory or directory of directories containing xyz files path can be 

1. absolute, e.g. "/home/aconner/orca_descriptors/library_pyox_2026_03_03/",

2. relative, e.g. "library_pyox_2026_03_03" (joined to current working directory).

In [2]:
src_dir = "DATA/LNiH2_library_001_to_download_2026_03_24"  # change this as needed

### Define the atoms to be included in the descriptor.

In [3]:
#Define lists for decriptor retrieval 

# 1 -atom descriptors (e.g. Sterimol L, atomic charge)
atoms = ["H1", "H2", "C1", "C2", "N1", "N2", "Ni"]

# 2-atom descriptors (e.g. Sterimol B1, bond length), if order matters for 2-atom descriptors (e.g. Sterimol B1), atoms must be listed in desired order
bonds = [("C1", "N1"), ("N1", "C1"), ("C2", "N2"), ("N2", "C2"), ("Ni", "N1"), ("Ni", "N2"), ("Ni", "H1"), ("Ni", "H2"), ("C1", "C2"), ("C2", "C1")]
pairs_bending = [("H1", "H2"), ("N1", "C2"), ("N2", "C1")] # list of bonds to consider for bend vibration descriptors, if order matters for bend vibration descriptors, atoms must be listed in desired order

# 3-atom descriptors (e.g. Sterimol B5, bond angle), if order matters for 3-atom descriptors (e.g. Sterimol B5), atoms must be listed in desired order
angles = [("H2", "Ni", "H1"), ("Ni", "N1", "C1"), ("Ni", "N2", "C2"), ("N1", "C1", "C2"), ("N2", "C2", "C1"), ("N1", "Ni", "N2"), ("C1", "Ni", "C2")]

# 4-atom descriptors (e.g. dihedral angle), if order matters for 4-atom descriptors (e.g. dihedral angle), atoms must be listed in desired order
dihedrals = [("N1", "C1", "C2", "N2"), ("C1", "C2", "N2", "Ni"), ("C2", "C1", "N1", "Ni")]

# If you want to include quadrant-based descriptors, define the quadrants here. Each quadrant is a list of atom labels. For example, if you want to define one quadrant that includes atoms C1, N1, C2, N2, and Ni, you would define:
#quadrants = [[2, 1, 3, 4, 6]]

# Atom Numbering

In [4]:
# example for the numbering of the atoms for one molecule:

df = an.compile_final('DATA/LNiH2_library_001_to_download_2026_03_24/AATATIAROAAKIN-SNVBAGLBSA-N/', subdirectory=True)

In [5]:
# Get numbering for all molecules

# Set your ORCA root folder here (contains many conf_* subfolders)
orca_folder = Path(src_dir)

print(f"Current working directory before processing: {os.getcwd()}")

df_num = pd.DataFrame()
for inchi_folder in os.listdir(orca_folder):
    if os.path.isdir(os.path.join(orca_folder, inchi_folder)):
        inchi_folder_path = os.path.join(orca_folder, inchi_folder)
        print(f"Processing {inchi_folder_path} for atom numbering...")
        df = an.compile_final(inchi_folder_path, subdirectory=True)
        df_num = pd.concat([df_num, df], ignore_index=True)

df_num.head()

# add the feather file paths to the df_num dataframe

df_num['feather_path'] = df_num['path'].apply(lambda x: x + x.split('/')[-2] + '.feather')

df_num.head()

Current working directory before processing: /Users/julesschleinitz/Desktop/Code/orca_descriptors
Processing DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/DSZOIEZWGDCKLK-KGLIPLIRSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/DSZOIEZWGDCKLK-KGLIPLIRSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/ZECIAWBAXVMXKI-CQSZACIVSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/ZECIAWBAXVMXKI-CQSZACIVSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/UITFYNBEZIIWCV-LURJTMIESA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/UITFYNBEZIIWCV-LURJTMIESA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/YVULGYITAFNKKF-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/YVULGYITAFNKKF-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/JFOQGDQQMCKEKY-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/JFOQGDQQMCKEKY-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/JPCAXHBKQLBOJG-KGLIPLIRSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/JPCAXHBKQLBOJG-KGLIPLIRSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/NHWBZSGKOQHPDW-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/NHWBZSGKOQHPDW-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/AATATIAROAAKIN-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/AATATIAROAAKIN-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/UOIDAFBRAUSYGL-ZDUSSCGKSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/UOIDAFBRAUSYGL-ZDUSSCGKSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/XVXACZLZNPRNEF-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/XVXACZLZNPRNEF-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/CTDSXZLFAXPRHX-MRVPVSSYSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/CTDSXZLFAXPRHX-MRVPVSSYSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-RBUKOAKNSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-RBUKOAKNSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/RJKNIIOSLLEQAJ-LBPRGKRZSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/RJKNIIOSLLEQAJ-LBPRGKRZSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/YZOJKEJLMYATFV-CYBMUJFWSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/YZOJKEJLMYATFV-CYBMUJFWSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/ZZYZJBMNVRAFBQ-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/ZZYZJBMNVRAFBQ-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-OALUTQOASA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-OALUTQOASA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/LSCORSGHQVIJEW-QGZVFWFLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/LSCORSGHQVIJEW-QGZVFWFLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/WQPDKBFVGVJUHI-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/WQPDKBFVGVJUHI-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/KGZUJYDTOJDLJK-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/KGZUJYDTOJDLJK-SNVBAGLBSA-N/

,xyz_name,path,ligand_type,inchi,SCF_energy,smiles,H1,Ni,H2,N1,C1,C2,N2,ligand_class,feather_path
0,optimization,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425277,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...
1,optimization,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425257,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...
2,optimization,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,DVLYVQBEMHJQAQ-SFHVURJKSA-N,-2811.494785,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...
3,optimization,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,DVLYVQBEMHJQAQ-SFHVURJKSA-N,-2811.49527,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...
4,optimization,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,DVLYVQBEMHJQAQ-SFHVURJKSA-N,-2811.493515,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...

# ORCA Descriptors

### Geometric Descriptors

In [6]:
from desc_utils.data_extraction import *
os.chdir(ROOT_DIR)

results_xyz_dict = get_xyz_descriptors(df_num, atoms, bonds, angles, dihedrals, quadrants=None, overwrite_json=False)
df_xyz_desc = pd.DataFrame.from_dict(results_xyz_dict, orient='index')
df_xyz_desc.set_index('path', inplace=True)
df_xyz_desc.head(5)

  0%|          | 0/308 [00:00<?, ?it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_22/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_14/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_13/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_47/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_78/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_40/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_82/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_76/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_49/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_71/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_85/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_12/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_15/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_23/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_24/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_84/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_70/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_77/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_83/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_48/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_41/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_46/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_79/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_100/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_90/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_64/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_63/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_97/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_55/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_99/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_52/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_39/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_8/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_37/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_30/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_98/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_53/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_54/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_96/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_62/xyz.json.

100%|██████████| 308/308 [00:00<00:00, 4264.76it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_65/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_91/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_31/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_7/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_36/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_9/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_38/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_43/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_88/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_44/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_72/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_86/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_81/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_75/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_21/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_19/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_26/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_10/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_28/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_17/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_74/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_80/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_87/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_73/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_45/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_42/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_89/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_29/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_16/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_11/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_18/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_27/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_20/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_33/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_34/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_60/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_94/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_58/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_93/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_67/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_51/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_69/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_56/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_35/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_32/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_68/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_57/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_50/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_59/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_66/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_92/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_95/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_61/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_7/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_7/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DSZOIEZWGDCKLK-KGLIPLIRSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DSZOIEZWGDCKLK-KGLIPLIRSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_8/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_7/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZECIAWBAXVMXKI-CQSZACIVSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZECIAWBAXVMXKI-CQSZACIVSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/UITFYNBEZIIWCV-LURJTMIESA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/UITFYNBEZIIWCV-LURJTMIESA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_14/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_13/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_12/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_15/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_8/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_7/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_9/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_10/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_17/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_16/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_11/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YVULGYITAFNKKF-SNVBAGLBSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YVULGYITAFNKKF-SNVBAGLBSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/JFOQGDQQMCKEKY-LLVKDONJSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/JFOQGDQQMCKEKY-LLVKDONJSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/JPCAXHBKQLBOJG-KGLIPLIRSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NHWBZSGKOQHPDW-LLVKDONJSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NHWBZSGKOQHPDW-LLVKDONJSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_7/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_7/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_3/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_4/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_25/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_22/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_14/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_13/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_12/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_15/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_23/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_24/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_8/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_1/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_6/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_7/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_21/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_19/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_26/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_10/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_17/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_16/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_11/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_18/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_20/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_5/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_2/xyz.json.
Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_3/xyz.json.

,%Vbur_atom_C1_radius_2.0,%Vbur_atom_C1_radius_2.5,%Vbur_atom_C1_radius_3.0,%Vbur_atom_C1_radius_3.5,%Vbur_atom_C1_radius_4.0,%Vbur_atom_C1_radius_4.5,%Vbur_atom_C1_radius_5.0,%Vbur_atom_C2_radius_2.0,%Vbur_atom_C2_radius_2.5,%Vbur_atom_C2_radius_3.0,...,Sterimol_Ni_H1_L,Sterimol_Ni_H2_Bmax,Sterimol_Ni_H2_Bmin,Sterimol_Ni_H2_L,Sterimol_Ni_N1_Bmax,Sterimol_Ni_N1_Bmin,Sterimol_Ni_N1_L,Sterimol_Ni_N2_Bmax,Sterimol_Ni_N2_Bmin,Sterimol_Ni_N2_L
path,,,,,,,,,,,,,,,,,,,,,
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,96.009814,87.469071,77.479701,67.318533,57.888244,49.658898,41.905411,94.947701,86.817945,77.904313,...,3.680284,8.042405,1.884272,4.356749,8.034602,1.798475,7.319335,6.787812,2.175292,7.610382
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,95.951705,87.402331,77.444316,67.306886,57.882813,49.653200,41.900484,94.921875,86.796783,77.881034,...,3.686991,8.037996,1.873462,4.369356,8.030114,1.792913,7.319373,6.787940,2.159351,7.604794
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25,95.990444,88.471806,80.327212,71.723001,63.066771,56.134129,50.164572,97.155863,92.179971,85.843452,...,4.673138,9.945725,3.068531,5.070741,10.085789,3.054849,7.816049,7.687240,4.458104,9.467927
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_22,96.003357,87.488605,78.053300,69.102917,60.746152,54.083992,48.315056,95.767691,89.114794,82.334811,...,5.070890,7.630035,4.016237,4.680611,9.838185,2.951335,7.772605,7.659860,4.121607,10.032296
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_14,96.067924,87.843469,79.606488,71.722419,64.021088,57.496092,51.465383,97.443182,92.835981,86.682434,...,4.356220,10.990912,3.077963,3.930265,10.946188,3.216689,8.127822,7.918820,4.238545,11.095262

### Charges and Energy Descriptors

In [7]:
results_charges_dict = get_all_charges(df_num, atoms)
df_charges_desc = pd.DataFrame.from_dict(results_charges_dict, orient='index')
df_charges_desc.set_index('path', inplace=True)
df_charges_desc.head(5)

Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...

,mulliken_H1,mulliken_H2,mulliken_C1,mulliken_C2,mulliken_N1,mulliken_N2,mulliken_Ni,loewdin_H1,loewdin_H2,loewdin_C1,...,saniso_N1,saniso_N2,saniso_Ni,siso_H1,siso_H2,siso_C1,siso_C2,siso_N1,siso_N2,siso_Ni
path,,,,,,,,,,,,,,,,,,,,,
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.077996,-0.097464,0.109601,0.291640,-0.048309,-0.049192,-0.348348,-0.069781,-0.071689,-0.149184,...,366.483239,237.285020,-1920.025043,39.219221,40.217872,37.668341,17.161352,-2.515718,18.126859,-4049.465402
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.079398,-0.097876,0.108511,0.292047,-0.048006,-0.049183,-0.347179,-0.069868,-0.071959,-0.149172,...,367.025926,240.718564,-1934.564548,39.198500,40.214541,37.658881,17.139805,-2.552599,18.228884,-4060.608625
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25,-0.098376,-0.074072,0.030477,0.364906,-0.002199,-0.123407,-0.325068,-0.066446,-0.064130,-0.149660,...,397.221237,237.660611,-2606.009812,38.720765,42.552337,36.398284,17.046468,-34.346185,15.348416,-4296.334652
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_22,-0.074343,-0.101332,0.014713,0.342346,0.000563,-0.113657,-0.323956,-0.063714,-0.066555,-0.148204,...,391.974231,233.680584,-2567.533789,42.661792,38.654647,36.125690,17.525786,-34.384262,19.019704,-4349.062139
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_14,-0.080924,-0.090248,-0.008087,0.345838,-0.011580,-0.099585,-0.355787,-0.073015,-0.067048,-0.147685,...,326.209545,255.404107,-2356.927868,38.409917,41.993519,36.788141,18.461544,-35.021918,15.131855,-4358.894092

### NBO Descriptors

In [8]:
results_nbo_dict = get_all_nbo_properties(df_num, atoms, basename="singlepoint")
df_nbo_desc = results_nbo_dict.copy()
df_nbo_desc.set_index("path", inplace=True)
df_nbo_desc.head(5)

# filter homo informations to restrict to the range homo-5 to lumo+5
homo_lumo_range = [1, 2, 3, 4, 5]
colums_to_drop = []
for c in df_nbo_desc.columns:
    if re.search(r'_hm\d+_', c):
        if not any(f'_hm{h}_' in c for h in homo_lumo_range):
            colums_to_drop.append(c)
    elif re.search(r'_lp\d+_', c):
        if not any(f'_lp{l}_' in c for l in homo_lumo_range):
            colums_to_drop.append(c)
print(colums_to_drop)

# remove analysis info:
for c in df_nbo_desc.columns:
    if "analysis_info" in c:
        colums_to_drop.append(c)


# Note: the notation hmX means homo - X and lpX means lumo + X.

df_nbo_desc = df_nbo_desc.drop(columns=colums_to_drop)
df_nbo_desc.head(5)

Could not find any complete NBO section in the file

,npa_H1_charge,npa_H1_core,npa_H1_valence,npa_H1_rydberg,npa_H1_total,npa_H2_charge,npa_H2_core,npa_H2_valence,npa_H2_rydberg,npa_H2_total,...,nho_directionality_hm_H1_Ni_hybrid_theta,nho_directionality_hm_H1_Ni_hybrid_phi,nho_directionality_hm_H1_Ni_deviation,nho_directionality_hm_C2_C1_type,nho_directionality_hm_C2_C1_bond_index,nho_directionality_hm_C2_C1_line_theta,nho_directionality_hm_C2_C1_line_phi,nho_directionality_hm_C2_C1_hybrid_theta,nho_directionality_hm_C2_C1_hybrid_phi,nho_directionality_hm_C2_C1_deviation
path,,,,,,,,,,,,,,,,,,,,,
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.21653,0.0,1.21368,0.00285,1.21653,-0.22963,0.0,1.22667,0.00296,1.22963,...,NaN,NaN,NaN,BD,1.0,111.5,0.2,112.5,357.0,3.2
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.21662,0.0,1.21378,0.00284,1.21662,-0.23047,0.0,1.22752,0.00295,1.23047,...,NaN,NaN,NaN,BD,1.0,110.0,359.7,111.0,356.5,3.2
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25,-0.21984,0.0,1.21684,0.00300,1.21984,-0.23576,0.0,1.23294,0.00282,1.23576,...,NaN,NaN,NaN,BD,1.0,100.5,337.9,99.3,336.2,2.0
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_22,-0.23509,0.0,1.23230,0.00279,1.23509,-0.22010,0.0,1.21712,0.00298,1.22010,...,NaN,NaN,NaN,BD,1.0,98.2,338.9,97.6,336.6,2.3
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_14,-0.23132,0.0,1.22858,0.00274,1.23132,-0.21785,0.0,1.21489,0.00297,1.21785,...,NaN,NaN,NaN,BD,1.0,90.8,352.9,89.4,350.0,3.2

### Vertical Redox Descriptors

In [9]:
results_redox_dict = get_redox_descriptors(
    df_num,
    atoms,
    descriptorPrefixes=["nbo_charge", "cm5"],
    nbo_block_map={"singlepoint": 1, "oxidation": 2, "reduction": 3},
)
df_redox_desc = pd.DataFrame.from_dict(results_redox_dict, orient='index')
df_redox_desc.set_index('path', inplace=True)
df_redox_desc.head(5)

Could not find any complete NBO section in the file
Could not find any complete NBO section in the file
Could not find any complete NBO section in the file

,Vertical_Ionization_Potential,Vertical_Electron_Affinity,Hardness,Electronegativity,Electrophilicity,fplus_nbo_charge_H1,fminus_nbo_charge_H1,fzero_nbo_charge_H1,fplus_nbo_charge_H2,fminus_nbo_charge_H2,...,fzero_cm5_C2,fplus_cm5_N1,fminus_cm5_N1,fzero_cm5_N1,fplus_cm5_N2,fminus_cm5_N2,fzero_cm5_N2,fplus_cm5_Ni,fminus_cm5_Ni,fzero_cm5_Ni
path,,,,,,,,,,,,,,,,,,,,,
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.208644,-0.036060,-0.086292,-0.122352,-0.086741,0.04749,0.10285,0.075170,0.06720,0.12403,...,0.037715,0.050102,-0.014710,0.017696,0.052991,-0.018316,0.017337,0.077775,0.433711,0.255743
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.208691,-0.036117,-0.086287,-0.122404,-0.086819,0.04748,0.10305,0.075265,0.06723,0.12436,...,0.037726,0.050111,-0.014717,0.017697,0.053060,-0.018285,0.017388,0.077710,0.433477,0.255593
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25,-0.213338,-0.046233,-0.083552,-0.129785,-0.100800,0.04229,0.09780,0.070045,0.06443,0.11995,...,0.031622,0.050859,-0.013946,0.018457,0.051549,-0.017930,0.016809,0.071710,0.416382,0.244046
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_22,-0.213240,-0.046011,-0.083614,-0.129625,-0.100478,0.06536,0.12069,0.093025,0.04273,0.09803,...,0.032287,0.050951,-0.014019,0.018466,0.051826,-0.018192,0.016817,0.072292,0.416921,0.244606
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_14,-0.212551,-0.045489,-0.083531,-0.129020,-0.099640,0.04525,0.09811,0.071680,0.06723,0.12080,...,0.032841,0.048564,-0.012434,0.018065,0.049053,-0.017822,0.015615,0.074004,0.411836,0.242920

### Summary of Descriptors

In [10]:
# Build a single summary table matched by molecular path
from desc_utils.data_extraction import _truncate_to_orca_descriptors

# 1) Base table (normalize df_num path so it matches extractor outputs)
_repo_root = Path('desc_utils/data_extraction.py').resolve().parent.parent
df_num_idx = df_num.copy()
df_num_idx['path'] = df_num_idx['path'].map(lambda p: _truncate_to_orca_descriptors(p, _repo_root))
df_num_idx = df_num_idx.set_index("path")

# 2) Concatenate all descriptor tables on index (= path)
total_df = pd.concat(
    [df_num_idx, df_xyz_desc, df_charges_desc, df_redox_desc, df_nbo_desc],
    axis=1,
    join="outer"
)

# 3) Remove duplicated column names (keep first occurrence)
total_df = total_df.loc[:, ~total_df.columns.duplicated()]

# 4) Restore path as a normal column
total_df = total_df.reset_index().rename(columns={"index": "path"})

print("total_df shape:", total_df.shape)
total_df.head(3)

total_df shape: (308, 516)

,path,xyz_name,ligand_type,inchi,SCF_energy,smiles,H1,Ni,H2,N1,...,nho_directionality_hm_H1_Ni_hybrid_theta,nho_directionality_hm_H1_Ni_hybrid_phi,nho_directionality_hm_H1_Ni_deviation,nho_directionality_hm_C2_C1_type,nho_directionality_hm_C2_C1_bond_index,nho_directionality_hm_C2_C1_line_theta,nho_directionality_hm_C2_C1_line_phi,nho_directionality_hm_C2_C1_hybrid_theta,nho_directionality_hm_C2_C1_hybrid_phi,nho_directionality_hm_C2_C1_deviation
0,orca_descriptors/DATA/LNiH2_library_001_to_dow...,optimization,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425277,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,...,NaN,NaN,NaN,BD,1.0,111.5,0.2,112.5,357.0,3.2
1,orca_descriptors/DATA/LNiH2_library_001_to_dow...,optimization,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425257,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,...,NaN,NaN,NaN,BD,1.0,110.0,359.7,111.0,356.5,3.2
2,orca_descriptors/DATA/LNiH2_library_001_to_dow...,optimization,core_5,DVLYVQBEMHJQAQ-SFHVURJKSA-N,-2811.494785,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,...,NaN,NaN,NaN,BD,1.0,100.5,337.9,99.3,336.2,2.0

# DescriPyTor

### Convert the ORCA output files to pseudo Gaussian log files for compatibility with descripytor generation. 

This step is necessary because descripy is designed to work with Gaussian log files, and the ORCA output files need to be converted to this format for descripy to process them correctly.

In [11]:
# convert orca files to log files | a log file is created for each conf_* subfolder in the orca_folder, and contains the same information as the orca output file but in a format that can be read by the descriptor calculation code
script_path = Path("orca2gaussian/orca_2_gauss.py")

if not script_path.exists():
    raise FileNotFoundError(f"Script not found: {script_path.resolve()}")
if not orca_folder.exists():
    raise FileNotFoundError(f"Folder not found: {orca_folder.resolve()}")


try:
    subprocess.run(
                [sys.executable, str(script_path), "--orca-folder", str(orca_folder)],
                capture_output=True,
                text=True,
                check=True,
            )

except subprocess.CalledProcessError as exc:
    print(f"Failed for {orca_folder}: {exc.stderr.strip() or exc}")

### DescriPyTor

#### Convert the log files to feather files for use in DescriPyTor.

In [12]:
# Load Descripytor feather file utils
DESCRIPYTOR_DIR = Path("DescriPyTor/MolFeatures")
OVERWRITE_FEATHER = False  # Set to True to overwrite existing feather files, False to skip if feather file already exists
print(f"Setting DESCRIPYTOR_DIR to: {DESCRIPYTOR_DIR}")
sys.path.append(DESCRIPYTOR_DIR)
sys.path.append(os.path.join(DESCRIPYTOR_DIR, 'M3_modeler'))
sys.path.append(os.path.join(DESCRIPYTOR_DIR, 'M2_data_extractor'))
sys.path.append(os.path.join(DESCRIPYTOR_DIR, 'utils'))

try:
    from data_extractor import Molecules, extract_connectivity
    from feather_extractor import logs_to_feather
    import gaussian_handler
    from gaussian_handler import feather_file_handler
    from help_functions import dict_to_horizontal_df, get_df_from_file, pick_samples_to_remove_for_distribution
    import help_functions
    import visualize

    print("All modules imported successfully.")
    
except ModuleNotFoundError as e:
    print(f"Module import failed: {e} \nPlease ensure all required modules are installed and available in the path specified on the right hand corner of the notebook.")


pd.set_option('display.max_columns', None)

# log_dir = os.path.join(examples_path, 'logs_example')

# iterate over all the log files in the orca_folder and check if they exist, print the path of the log file if it exists, otherwise print a warning message, and extract the log files to a feather file.
pwd_before = os.getcwd()
print(f"Current working directory: {os.getcwd()}")
for inchi_folder in os.listdir(orca_folder):
    if os.path.isdir(os.path.join(orca_folder, inchi_folder)):
        os.chdir(os.path.join(orca_folder, inchi_folder))
    else:
        print(f"Warning: {os.path.join(orca_folder, inchi_folder)} is not a directory, skipping.")
        continue
    
    for conf_folder in os.listdir('.'):
        if conf_folder.startswith('conf_') and os.path.isdir(conf_folder):
            os.chdir(conf_folder)
            log_file_path = None
            for f in os.listdir('.'):
                if f.endswith('.log'):
                    log_file_path = os.path.join(os.getcwd(), f)
            if log_file_path is None:
                print(f"No log file found in {os.getcwd()}")
            else:
                feather_file = log_file_path.replace('.log', '.feather')
                if os.path.exists(feather_file) and not OVERWRITE_FEATHER:
                    print(f"Feather file already exists, skipping: {feather_file}")
                else:
                    try:
                        logs_to_feather(os.getcwd(), feather_dir=os.getcwd())
                        print(f"Logs successfully converted to feather format at: {os.getcwd()}")
                    except Exception as e:
                        print(f"Error converting logs in {os.getcwd()} to feather format: {e}")
            os.chdir('..')
        
    os.chdir(pwd_before)

Setting DESCRIPYTOR_DIR to: DescriPyTor/MolFeatures
All modules imported successfully.
Current working directory: /Users/julesschleinitz/Desktop/Code/orca_descriptors
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1/conf_1.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2/conf_2.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25/conf_25.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_22/conf_22.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_14/conf_14.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_13/conf_13.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_47/conf_47.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_78/conf_78.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_40/conf_40.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_82/conf_82.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_76/conf_76.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_49/conf_49.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_71/conf_71.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_85/conf_85.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_12/conf_12.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_15/conf_15.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_23/conf_23.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_24/conf_24.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_84/conf_84.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_70/conf_70.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_77/conf_77.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_83/conf_83.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_48/conf_48.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_41/conf_41.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_46/conf_46.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_79/conf_79.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_100/conf_100.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_90/conf_90.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_64/conf_64.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_63/conf_63.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_97/conf_97.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_55/conf_55.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_99/conf_99.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_52/conf_52.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_39/conf_39.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_8/conf_8.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_37/conf_37.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_1/conf_1.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_30/conf_30.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_6/conf_6.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_98/conf_98.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_53/conf_53.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_54/conf_54.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_96/conf_96.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_62/conf_62.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_65/conf_65.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_91/conf_91.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_31/conf_31.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_7/conf_7.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_36/conf_36.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_9/conf_9.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_38/conf_38.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_43/conf_43.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_88/conf_88.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_44/conf_44.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_72/conf_72.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_86/conf_86.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_81/conf_81.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_75/conf_75.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_21/conf_21.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_19/conf_19.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_26/conf_26.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_10/conf_10.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_28/conf_28.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_17/conf_17.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_74/conf_74.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_80/conf_80.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_87/conf_87.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_73/conf_73.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_45/conf_45.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_42/conf_42.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_89/conf_89.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_29/conf_29.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_16/conf_16.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_11/conf_11.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_18/conf_18.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_27/conf_27.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_20/conf_20.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_33/conf_33.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_5/conf_5.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_34/conf_34.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_2/conf_2.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_60/conf_60.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_94/conf_94.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_58/conf_58.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_93/conf_93.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_67/conf_67.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_51/conf_51.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_69/conf_69.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_56/conf_56.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_35/conf_35.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_3/conf_3.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_32/conf_32.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_4/conf_4.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_68/conf_68.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_57/conf_57.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_50/conf_50.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_59/conf_59.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_66/conf_66.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_92/conf_92.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_95/conf_95.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_61/conf_61.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_1/conf_1.feather
Feather file already exists, skipping: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_2/conf_2.feather

#### Extract DescriPyTor descriptors (vibrations, dipoles and sterimol descriptors)

In [13]:

os.chdir(ROOT_DIR)

# renumbering of the atoms in the feather files according to the df_num numberings
renumbering_convention = {"H1": 1, "H2": 2, "Ni": 3, "N1": 4, "C1": 5, "C2": 6, "N2": 7}

desc_all = {}
for i, row in tqdm(df_num.iterrows(), total=df_num.shape[0]):
    os.chdir(ROOT_DIR)
    desc_mol = {}
    # read path
    feather_dir = row['path']
    desc_mol['feather_dir'] = feather_dir
    # create Molecule object and renumber atoms according to the df_num numberings
    mols = Molecules(molecules_dir_name=feather_dir)

    # global descriptors
    ## 1-atom descriptors
    charges_dict    = mols.get_charge_df_dict(atom_indices=[row[x] for x in atoms]) # NBO
    index = charges_dict.index[0]
    for j, atom in enumerate(atoms):
        desc_mol[f'charge_NBO_{atom}'] = charges_dict.loc[index, f"nbo_atom_{row[atom]}"]

    ## 2-atom descriptors
    # sterimol descriptors (uses "bonds" list defined above to determine which sterimol descriptors to calculate)
    sterimol_descriptors    = mols.get_sterimol_dict(atom_indices=[[row[x], row[y]] for x, y in bonds])
    for j, (x1, x2) in enumerate(bonds):
        desc_mol[f'B1_{x1}-{x2}']           = sterimol_descriptors.loc[index, f'B1_{row[x1]}-{row[x2]}']
        desc_mol[f'B5_{x1}-{x2}']           = sterimol_descriptors.loc[index, f'B5_{row[x1]}-{row[x2]}']
        desc_mol[f'L_{x1}-{x2}']            = sterimol_descriptors.loc[index, f'L_{row[x1]}-{row[x2]}']
        desc_mol[f'loc_B5_{x1}-{x2}']       = sterimol_descriptors.loc[index, f'loc_B5_{row[x1]}-{row[x2]}']
        desc_mol[f'B1-B5_angle_{x1}-{x2}']  = sterimol_descriptors.loc[index, f'B1_B5_angle_{row[x1]}-{row[x2]}']

    bond_length_dict        = mols.get_bond_length_dict(atom_pairs=[[row[x], row[y]] for x, y in bonds]) # dataframe with bond length descriptors for specified bonds
    for j, (x1, x2) in enumerate(bonds):
        desc_mol[f'dist_{x1}-{x2}'] = bond_length_dict.loc[index, f'0_bond_length_{row[x1]}-{row[x2]}']

    vibrations_dict         = mols.get_stretch_vibration_dict(atom_pairs=[[row[x], row[y]] for x, y in bonds]) # dataframe with vibration descriptors for all molecules in the feather file, can be filtered for specific vibrations of interest based on the atoms involved in the vibration
    for j, (x1, x2) in enumerate(bonds):
        desc_mol[f'vib_freq_{x1}-{x2}'] = vibrations_dict.loc[index, f'Frequency_Stretch_{row[x1]}_{row[x2]}']
        desc_mol[f'vib_amp_{x1}-{x2}'] = vibrations_dict.loc[index, f'Amplitude_Stretch_{row[x1]}_{row[x2]}']

    vibrations_bend_dict    = mols.get_bend_vibration_dict(atom_pairs=[[row[x], row[y]] for x, y in pairs_bending]) # dataframe with bend vibration descriptors for specified angles
    for j, (x1, x2) in enumerate(pairs_bending):
        desc_mol[f'vib_freq_bend_{x1}-{x2}'] = vibrations_bend_dict.loc[index, f'Frequency_Bending_{row[x1]}-{row[x2]}']
        desc_mol[f'vib_amp_bend_{x1}-{x2}']  = vibrations_bend_dict.loc[index, f'Cross_mag_Bending_{row[x1]}-{row[x2]}']
    
    charges_diff_dict       = mols.get_charge_diff_df_dict(atom_indices=[[row[x], row[y]] for x, y in bonds]) # dataframe with charge difference descriptors for specified bonds
    for j, (x1, x2) in enumerate(bonds):
        desc_mol[f'charge_NBO_diff_{x1}-{x2}'] = charges_diff_dict.loc[index, f'nbo_diff_{row[x1]}-{row[x2]}']

    ## 3-atom descriptors
    dipole_ni = mols.get_dipole_dict(atom_indices=[row["Ni"], row["N2"], row["N1"]]) # dataframe with dipole moment descriptors for specified atom
    desc_mol['dipole'] = dipole_ni.loc[index, f'total_dipole_{row["Ni"]}-{row["N2"]}-{row["N1"]}']
    desc_mol['dipole_x_Ni-N2-N1'] = dipole_ni.loc[index, f'dipole_x_{row["Ni"]}-{row["N2"]}-{row["N1"]}']
    desc_mol['dipole_y_Ni-N2-N1'] = dipole_ni.loc[index, f'dipole_y_{row["Ni"]}-{row["N2"]}-{row["N1"]}']
    desc_mol['dipole_z_Ni-N2-N1'] = dipole_ni.loc[index, f'dipole_z_{row["Ni"]}-{row["N2"]}-{row["N1"]}']

    angles_dict = mols.get_bond_angle_dict(atom_indices=[[row[x], row[y], row[z]] for x, y, z in angles])
    for j, (x1, x2, x3) in enumerate(angles):
        desc_mol[f'angle_{x1}-{x2}-{x3}'] = angles_dict.loc[index, f'0_angle_[{row[x1]}, {row[x2]}, {row[x3]}]']

    desc_all[i] = desc_mol

df_desc = pd.DataFrame.from_dict(desc_all, orient='index')
df_desc.head(5)

  0%|          | 0/308 [00:00<?, ?it/s]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

  0%|          | 1/308 [00:00<04:19,  1.18it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

  1%|          | 2/308 [00:01<04:04,  1.25it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_25.feather'] Failed Molecules: []

  1%|          | 3/308 [00:03<06:22,  1.26s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_25 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_25 for [2, 4]

Molecules Loaded: ['conf_22.feather'] Failed Molecules: []

  1%|▏         | 4/308 [00:05<07:32,  1.49s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_22 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_22 for [2, 4]

Molecules Loaded: ['conf_14.feather'] Failed Molecules: []

  2%|▏         | 5/308 [00:07<08:04,  1.60s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 4]

Molecules Loaded: ['conf_13.feather'] Failed Molecules: []

  2%|▏         | 6/308 [00:08<08:29,  1.69s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 4]

Molecules Loaded: ['conf_47.feather'] Failed Molecules: []

  2%|▏         | 7/308 [00:10<08:41,  1.73s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_47 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_47 for [2, 4]

Molecules Loaded: ['conf_78.feather'] Failed Molecules: []

  3%|▎         | 8/308 [00:12<08:50,  1.77s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_78 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_78 for [2, 4]

Molecules Loaded: ['conf_40.feather'] Failed Molecules: []

  3%|▎         | 9/308 [00:14<08:51,  1.78s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_40 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_40 for [2, 4]

Molecules Loaded: ['conf_82.feather'] Failed Molecules: []

  3%|▎         | 10/308 [00:16<08:56,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_82 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_82 for [2, 4]

Molecules Loaded: ['conf_76.feather'] Failed Molecules: []

  4%|▎         | 11/308 [00:18<09:00,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_76 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_76 for [2, 4]

Molecules Loaded: ['conf_49.feather'] Failed Molecules: []

  4%|▍         | 12/308 [00:19<08:58,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_49 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_49 for [2, 4]

Molecules Loaded: ['conf_71.feather'] Failed Molecules: []

  4%|▍         | 13/308 [00:21<08:54,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_71 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_71 for [2, 4]

Molecules Loaded: ['conf_85.feather'] Failed Molecules: []

  5%|▍         | 14/308 [00:23<08:53,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_85 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_85 for [2, 4]

Molecules Loaded: ['conf_12.feather'] Failed Molecules: []

  5%|▍         | 15/308 [00:25<08:54,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 4]

Molecules Loaded: ['conf_15.feather'] Failed Molecules: []

  5%|▌         | 16/308 [00:27<08:52,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 4]

Molecules Loaded: ['conf_23.feather'] Failed Molecules: []

  6%|▌         | 17/308 [00:29<08:52,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_23 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_23 for [2, 4]

Molecules Loaded: ['conf_24.feather'] Failed Molecules: []

  6%|▌         | 18/308 [00:30<08:49,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_24 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_24 for [2, 4]

Molecules Loaded: ['conf_84.feather'] Failed Molecules: []

  6%|▌         | 19/308 [00:32<08:48,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_84 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_84 for [2, 4]

Molecules Loaded: ['conf_70.feather'] Failed Molecules: []

  6%|▋         | 20/308 [00:34<08:44,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_70 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_70 for [2, 4]

Molecules Loaded: ['conf_77.feather'] Failed Molecules: []

  7%|▋         | 21/308 [00:36<08:41,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_77 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_77 for [2, 4]

Molecules Loaded: ['conf_83.feather'] Failed Molecules: []

  7%|▋         | 22/308 [00:38<08:47,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_83 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_83 for [2, 4]

Molecules Loaded: ['conf_48.feather'] Failed Molecules: []

  7%|▋         | 23/308 [00:40<08:54,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_48 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_48 for [2, 4]

Molecules Loaded: ['conf_41.feather'] Failed Molecules: []

  8%|▊         | 24/308 [00:41<08:46,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_41 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_41 for [2, 4]

Molecules Loaded: ['conf_46.feather'] Failed Molecules: []

  8%|▊         | 25/308 [00:43<08:44,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_46 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_46 for [2, 4]

Molecules Loaded: ['conf_79.feather'] Failed Molecules: []

  8%|▊         | 26/308 [00:45<08:41,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_79 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_79 for [2, 4]

Molecules Loaded: ['conf_100.feather'] Failed Molecules: []

  9%|▉         | 27/308 [00:47<08:38,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_100 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_100 for [2, 4]

Molecules Loaded: ['conf_90.feather'] Failed Molecules: []

  9%|▉         | 28/308 [00:49<08:36,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_90 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_90 for [2, 4]

Molecules Loaded: ['conf_64.feather'] Failed Molecules: []

  9%|▉         | 29/308 [00:51<08:37,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_64 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_64 for [2, 4]

Molecules Loaded: ['conf_63.feather'] Failed Molecules: []

 10%|▉         | 30/308 [00:53<08:44,  1.89s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_63 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_63 for [2, 4]

Molecules Loaded: ['conf_97.feather'] Failed Molecules: []

 10%|█         | 31/308 [00:55<08:41,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_97 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_97 for [2, 4]

Molecules Loaded: ['conf_55.feather'] Failed Molecules: []

 10%|█         | 32/308 [00:56<08:29,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_55 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_55 for [2, 4]

Molecules Loaded: ['conf_99.feather'] Failed Molecules: []

 11%|█         | 33/308 [00:58<08:25,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_99 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_99 for [2, 4]

Molecules Loaded: ['conf_52.feather'] Failed Molecules: []

 11%|█         | 34/308 [01:00<08:21,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_52 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_52 for [2, 4]

Molecules Loaded: ['conf_39.feather'] Failed Molecules: []

 11%|█▏        | 35/308 [01:02<08:20,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_39 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_39 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 12%|█▏        | 36/308 [01:04<08:13,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_37.feather'] Failed Molecules: []

 12%|█▏        | 37/308 [01:05<08:16,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_37 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_37 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 12%|█▏        | 38/308 [01:07<08:15,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_30.feather'] Failed Molecules: []

 13%|█▎        | 39/308 [01:09<08:14,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_30 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_30 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 13%|█▎        | 40/308 [01:11<08:07,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_98.feather'] Failed Molecules: []

 13%|█▎        | 41/308 [01:13<08:04,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_98 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_98 for [2, 4]

Molecules Loaded: ['conf_53.feather'] Failed Molecules: []

 14%|█▎        | 42/308 [01:14<08:01,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_53 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_53 for [2, 4]

Molecules Loaded: ['conf_54.feather'] Failed Molecules: []

 14%|█▍        | 43/308 [01:16<08:00,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_54 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_54 for [2, 4]

Molecules Loaded: ['conf_96.feather'] Failed Molecules: []

 14%|█▍        | 44/308 [01:18<07:56,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_96 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_96 for [2, 4]

Molecules Loaded: ['conf_62.feather'] Failed Molecules: []

 15%|█▍        | 45/308 [01:20<07:58,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_62 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_62 for [2, 4]

Molecules Loaded: ['conf_65.feather'] Failed Molecules: []

 15%|█▍        | 46/308 [01:22<07:59,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_65 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_65 for [2, 4]

Molecules Loaded: ['conf_91.feather'] Failed Molecules: []

 15%|█▌        | 47/308 [01:24<07:56,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_91 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_91 for [2, 4]

Molecules Loaded: ['conf_31.feather'] Failed Molecules: []

 16%|█▌        | 48/308 [01:25<07:51,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_31 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_31 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 16%|█▌        | 49/308 [01:27<07:50,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_36.feather'] Failed Molecules: []

 16%|█▌        | 50/308 [01:29<07:52,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_36 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_36 for [2, 4]

Molecules Loaded: ['conf_9.feather'] Failed Molecules: []

 17%|█▋        | 51/308 [01:31<07:53,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 4]

Molecules Loaded: ['conf_38.feather'] Failed Molecules: []

 17%|█▋        | 52/308 [01:33<07:47,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_38 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_38 for [2, 4]

Molecules Loaded: ['conf_43.feather'] Failed Molecules: []

 17%|█▋        | 53/308 [01:35<07:48,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_43 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_43 for [2, 4]

Molecules Loaded: ['conf_88.feather'] Failed Molecules: []

 18%|█▊        | 54/308 [01:36<07:45,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_88 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_88 for [2, 4]

Molecules Loaded: ['conf_44.feather'] Failed Molecules: []

 18%|█▊        | 55/308 [01:38<07:55,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_44 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_44 for [2, 4]

Molecules Loaded: ['conf_72.feather'] Failed Molecules: []

 18%|█▊        | 56/308 [01:40<07:54,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_72 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_72 for [2, 4]

Molecules Loaded: ['conf_86.feather'] Failed Molecules: []

 19%|█▊        | 57/308 [01:42<07:47,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_86 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_86 for [2, 4]

Molecules Loaded: ['conf_81.feather'] Failed Molecules: []

 19%|█▉        | 58/308 [01:44<07:45,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_81 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_81 for [2, 4]

Molecules Loaded: ['conf_75.feather'] Failed Molecules: []

 19%|█▉        | 59/308 [01:46<07:39,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_75 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_75 for [2, 4]

Molecules Loaded: ['conf_21.feather'] Failed Molecules: []

 19%|█▉        | 60/308 [01:48<07:32,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_21 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_21 for [2, 4]

Molecules Loaded: ['conf_19.feather'] Failed Molecules: []

 20%|█▉        | 61/308 [01:50<07:41,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_19 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_19 for [2, 4]

Molecules Loaded: ['conf_26.feather'] Failed Molecules: []

 20%|██        | 62/308 [01:51<07:41,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_26 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_26 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 20%|██        | 63/308 [01:53<07:38,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_28.feather'] Failed Molecules: []

 21%|██        | 64/308 [01:55<07:32,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_28 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_28 for [2, 4]

Molecules Loaded: ['conf_17.feather'] Failed Molecules: []

 21%|██        | 65/308 [01:57<07:25,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 4]

Molecules Loaded: ['conf_74.feather'] Failed Molecules: []

 21%|██▏       | 66/308 [01:59<07:21,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_74 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_74 for [2, 4]

Molecules Loaded: ['conf_80.feather'] Failed Molecules: []

 22%|██▏       | 67/308 [02:00<07:17,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_80 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_80 for [2, 4]

Molecules Loaded: ['conf_87.feather'] Failed Molecules: []

 22%|██▏       | 68/308 [02:02<07:11,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_87 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_87 for [2, 4]

Molecules Loaded: ['conf_73.feather'] Failed Molecules: []

 22%|██▏       | 69/308 [02:04<07:09,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_73 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_73 for [2, 4]

Molecules Loaded: ['conf_45.feather'] Failed Molecules: []

 23%|██▎       | 70/308 [02:06<07:12,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_45 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_45 for [2, 4]

Molecules Loaded: ['conf_42.feather'] Failed Molecules: []

 23%|██▎       | 71/308 [02:08<07:11,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_42 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_42 for [2, 4]

Molecules Loaded: ['conf_89.feather'] Failed Molecules: []

 23%|██▎       | 72/308 [02:10<07:10,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_89 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_89 for [2, 4]

Molecules Loaded: ['conf_29.feather'] Failed Molecules: []

 24%|██▎       | 73/308 [02:11<07:09,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_29 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_29 for [2, 4]

Molecules Loaded: ['conf_16.feather'] Failed Molecules: []

 24%|██▍       | 74/308 [02:13<07:08,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 4]

Molecules Loaded: ['conf_11.feather'] Failed Molecules: []

 24%|██▍       | 75/308 [02:15<07:06,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 4]

Molecules Loaded: ['conf_18.feather'] Failed Molecules: []

 25%|██▍       | 76/308 [02:17<07:02,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_18 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_18 for [2, 4]

Molecules Loaded: ['conf_27.feather'] Failed Molecules: []

 25%|██▌       | 77/308 [02:19<07:06,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_27 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_27 for [2, 4]

Molecules Loaded: ['conf_20.feather'] Failed Molecules: []

 25%|██▌       | 78/308 [02:21<07:06,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_20 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_20 for [2, 4]

Molecules Loaded: ['conf_33.feather'] Failed Molecules: []

 26%|██▌       | 79/308 [02:23<07:07,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_33 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_33 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 26%|██▌       | 80/308 [02:24<07:05,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_34.feather'] Failed Molecules: []

 26%|██▋       | 81/308 [02:26<07:01,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_34 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_34 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 27%|██▋       | 82/308 [02:28<06:59,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_60.feather'] Failed Molecules: []

 27%|██▋       | 83/308 [02:31<07:36,  2.03s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_60 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_60 for [2, 4]

Molecules Loaded: ['conf_94.feather'] Failed Molecules: []

 27%|██▋       | 84/308 [02:33<07:40,  2.06s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_94 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_94 for [2, 4]

Molecules Loaded: ['conf_58.feather'] Failed Molecules: []

 28%|██▊       | 85/308 [02:35<07:27,  2.01s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_58 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_58 for [2, 4]

Molecules Loaded: ['conf_93.feather'] Failed Molecules: []

 28%|██▊       | 86/308 [02:36<07:18,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_93 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_93 for [2, 4]

Molecules Loaded: ['conf_67.feather'] Failed Molecules: []

 28%|██▊       | 87/308 [02:38<07:16,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_67 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_67 for [2, 4]

Molecules Loaded: ['conf_51.feather'] Failed Molecules: []

 29%|██▊       | 88/308 [02:40<07:06,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_51 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_51 for [2, 4]

Molecules Loaded: ['conf_69.feather'] Failed Molecules: []

 29%|██▉       | 89/308 [02:42<07:01,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_69 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_69 for [2, 4]

Molecules Loaded: ['conf_56.feather'] Failed Molecules: []

 29%|██▉       | 90/308 [02:44<06:59,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_56 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_56 for [2, 4]

Molecules Loaded: ['conf_35.feather'] Failed Molecules: []

 30%|██▉       | 91/308 [02:46<06:59,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_35 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_35 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 30%|██▉       | 92/308 [02:48<07:08,  1.98s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_32.feather'] Failed Molecules: []

 30%|███       | 93/308 [02:50<07:04,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_32 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_32 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 31%|███       | 94/308 [02:52<07:02,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_68.feather'] Failed Molecules: []

 31%|███       | 95/308 [02:54<06:58,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_68 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_68 for [2, 4]

Molecules Loaded: ['conf_57.feather'] Failed Molecules: []

 31%|███       | 96/308 [02:56<06:51,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_57 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_57 for [2, 4]

Molecules Loaded: ['conf_50.feather'] Failed Molecules: []

 31%|███▏      | 97/308 [02:58<06:52,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_50 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_50 for [2, 4]

Molecules Loaded: ['conf_59.feather'] Failed Molecules: []

 32%|███▏      | 98/308 [03:00<06:49,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_59 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_59 for [2, 4]

Molecules Loaded: ['conf_66.feather'] Failed Molecules: []

 32%|███▏      | 99/308 [03:02<06:46,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_66 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_66 for [2, 4]

Molecules Loaded: ['conf_92.feather'] Failed Molecules: []

 32%|███▏      | 100/308 [03:04<06:43,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_92 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_92 for [2, 4]

Molecules Loaded: ['conf_95.feather'] Failed Molecules: []

 33%|███▎      | 101/308 [03:06<06:44,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_95 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_95 for [2, 4]

Molecules Loaded: ['conf_61.feather'] Failed Molecules: []

 33%|███▎      | 102/308 [03:08<06:42,  1.96s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_61 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_61 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 33%|███▎      | 103/308 [03:08<05:32,  1.62s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 34%|███▍      | 104/308 [03:09<04:46,  1.40s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 34%|███▍      | 105/308 [03:10<04:13,  1.25s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 34%|███▍      | 106/308 [03:11<03:50,  1.14s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 35%|███▍      | 107/308 [03:12<03:42,  1.10s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 35%|███▌      | 108/308 [03:13<03:32,  1.06s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 35%|███▌      | 109/308 [03:14<03:28,  1.05s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 36%|███▌      | 110/308 [03:15<03:26,  1.04s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 36%|███▌      | 111/308 [03:16<03:20,  1.02s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 36%|███▋      | 112/308 [03:17<03:19,  1.02s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 37%|███▋      | 113/308 [03:18<03:17,  1.01s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 37%|███▋      | 114/308 [03:19<03:13,  1.00it/s]

Calculating stretch vibration for atoms [[6, 14], [14, 6], [5, 4], [4, 5], [2, 14], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 14]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 37%|███▋      | 115/308 [03:20<03:13,  1.00s/it]

Calculating stretch vibration for atoms [[6, 14], [14, 6], [5, 4], [4, 5], [2, 14], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 14]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 38%|███▊      | 116/308 [03:21<03:13,  1.01s/it]

Calculating stretch vibration for atoms [[6, 14], [14, 6], [5, 4], [4, 5], [2, 14], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 14]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 38%|███▊      | 117/308 [03:22<03:10,  1.00it/s]

Calculating stretch vibration for atoms [[6, 14], [14, 6], [5, 4], [4, 5], [2, 14], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 14]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 38%|███▊      | 118/308 [03:23<03:09,  1.00it/s]

Calculating stretch vibration for atoms [[6, 14], [14, 6], [5, 4], [4, 5], [2, 14], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 14]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 39%|███▊      | 119/308 [03:24<03:06,  1.01it/s]

Calculating stretch vibration for atoms [[6, 14], [14, 6], [5, 4], [4, 5], [2, 14], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 14]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 39%|███▉      | 120/308 [03:25<03:06,  1.01it/s]

Calculating stretch vibration for atoms [[6, 14], [14, 6], [5, 4], [4, 5], [2, 14], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 14]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 39%|███▉      | 121/308 [03:26<03:06,  1.01it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 40%|███▉      | 122/308 [03:27<03:06,  1.00s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 40%|███▉      | 123/308 [03:28<03:03,  1.01it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 40%|████      | 124/308 [03:29<03:02,  1.01it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 41%|████      | 125/308 [03:30<03:17,  1.08s/it]

Calculating stretch vibration for atoms [[6, 20], [20, 6], [5, 4], [4, 5], [2, 20], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 20]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 41%|████      | 126/308 [03:32<03:26,  1.13s/it]

Calculating stretch vibration for atoms [[6, 20], [20, 6], [5, 4], [4, 5], [2, 20], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 20]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 41%|████      | 127/308 [03:33<03:35,  1.19s/it]

Calculating stretch vibration for atoms [[6, 20], [20, 6], [5, 4], [4, 5], [2, 20], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 20]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 42%|████▏     | 128/308 [03:34<03:38,  1.21s/it]

Calculating stretch vibration for atoms [[6, 20], [20, 6], [5, 4], [4, 5], [2, 20], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 20]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 42%|████▏     | 129/308 [03:35<03:39,  1.23s/it]

Calculating stretch vibration for atoms [[6, 20], [20, 6], [5, 4], [4, 5], [2, 20], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 20]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 42%|████▏     | 130/308 [03:37<03:40,  1.24s/it]

Calculating stretch vibration for atoms [[6, 20], [20, 6], [5, 4], [4, 5], [2, 20], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 20]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 43%|████▎     | 131/308 [03:38<03:22,  1.15s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 43%|████▎     | 132/308 [03:39<03:11,  1.09s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 43%|████▎     | 133/308 [03:40<03:42,  1.27s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 44%|████▎     | 134/308 [03:42<04:03,  1.40s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 44%|████▍     | 135/308 [03:44<04:16,  1.48s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 44%|████▍     | 136/308 [03:45<04:27,  1.55s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 44%|████▍     | 137/308 [03:47<04:32,  1.59s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 45%|████▍     | 138/308 [03:49<04:36,  1.62s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 45%|████▌     | 139/308 [03:50<04:37,  1.64s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 45%|████▌     | 140/308 [03:52<04:39,  1.66s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 46%|████▌     | 141/308 [03:53<04:08,  1.49s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 46%|████▌     | 142/308 [03:54<03:46,  1.36s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 46%|████▋     | 143/308 [03:55<03:10,  1.16s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 47%|████▋     | 144/308 [03:56<02:45,  1.01s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 47%|████▋     | 145/308 [03:57<02:41,  1.01it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 47%|████▋     | 146/308 [03:58<02:36,  1.03it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 48%|████▊     | 147/308 [03:59<02:35,  1.03it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_14.feather'] Failed Molecules: []

 48%|████▊     | 148/308 [04:00<02:53,  1.08s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 4]

Molecules Loaded: ['conf_13.feather'] Failed Molecules: []

 48%|████▊     | 149/308 [04:01<03:05,  1.17s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 4]

Molecules Loaded: ['conf_12.feather'] Failed Molecules: []

 49%|████▊     | 150/308 [04:03<03:13,  1.22s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 4]

Molecules Loaded: ['conf_15.feather'] Failed Molecules: []

 49%|████▉     | 151/308 [04:04<03:18,  1.26s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 49%|████▉     | 152/308 [04:05<03:22,  1.30s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 50%|████▉     | 153/308 [04:07<03:23,  1.31s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 50%|█████     | 154/308 [04:08<03:23,  1.32s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 50%|█████     | 155/308 [04:09<03:22,  1.33s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_9.feather'] Failed Molecules: []

 51%|█████     | 156/308 [04:11<03:24,  1.35s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 51%|█████     | 157/308 [04:12<03:23,  1.35s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_17.feather'] Failed Molecules: []

 51%|█████▏    | 158/308 [04:13<03:21,  1.34s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 4]

Molecules Loaded: ['conf_16.feather'] Failed Molecules: []

 52%|█████▏    | 159/308 [04:15<03:21,  1.35s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 4]

Molecules Loaded: ['conf_11.feather'] Failed Molecules: []

 52%|█████▏    | 160/308 [04:16<03:19,  1.35s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 52%|█████▏    | 161/308 [04:17<03:18,  1.35s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 53%|█████▎    | 162/308 [04:19<03:17,  1.35s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 53%|█████▎    | 163/308 [04:20<03:16,  1.36s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 53%|█████▎    | 164/308 [04:22<03:14,  1.35s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 54%|█████▎    | 165/308 [04:22<02:51,  1.20s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 54%|█████▍    | 166/308 [04:23<02:38,  1.11s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 54%|█████▍    | 167/308 [04:24<02:30,  1.06s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 55%|█████▍    | 168/308 [04:25<02:25,  1.04s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 55%|█████▍    | 169/308 [04:26<02:16,  1.02it/s]

Calculating stretch vibration for atoms [[6, 11], [11, 6], [5, 4], [4, 5], [2, 11], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 11]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 55%|█████▌    | 170/308 [04:27<02:13,  1.03it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 56%|█████▌    | 171/308 [04:28<02:17,  1.00s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 56%|█████▌    | 172/308 [04:29<02:19,  1.03s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 56%|█████▌    | 173/308 [04:30<02:21,  1.05s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 56%|█████▋    | 174/308 [04:31<02:22,  1.06s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 57%|█████▋    | 175/308 [04:32<02:20,  1.05s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 57%|█████▋    | 176/308 [04:34<02:22,  1.08s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 57%|█████▋    | 177/308 [04:35<02:20,  1.08s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 58%|█████▊    | 178/308 [04:36<02:20,  1.08s/it]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 58%|█████▊    | 179/308 [04:37<02:20,  1.09s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 58%|█████▊    | 180/308 [04:38<02:19,  1.09s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 59%|█████▉    | 181/308 [04:39<02:17,  1.08s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 59%|█████▉    | 182/308 [04:40<02:18,  1.10s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 59%|█████▉    | 183/308 [04:41<02:17,  1.10s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 60%|█████▉    | 184/308 [04:42<02:14,  1.09s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 60%|██████    | 185/308 [04:43<02:14,  1.09s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_25.feather'] Failed Molecules: []

 60%|██████    | 186/308 [04:45<02:35,  1.28s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_25 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_25 for [2, 4]

Molecules Loaded: ['conf_22.feather'] Failed Molecules: []

 61%|██████    | 187/308 [04:47<02:46,  1.38s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_22 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_22 for [2, 4]

Molecules Loaded: ['conf_14.feather'] Failed Molecules: []

 61%|██████    | 188/308 [04:48<02:49,  1.41s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 4]

Molecules Loaded: ['conf_13.feather'] Failed Molecules: []

 61%|██████▏   | 189/308 [04:50<02:53,  1.46s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 4]

Molecules Loaded: ['conf_12.feather'] Failed Molecules: []

 62%|██████▏   | 190/308 [04:51<02:52,  1.46s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 4]

Molecules Loaded: ['conf_15.feather'] Failed Molecules: []

 62%|██████▏   | 191/308 [04:53<02:53,  1.48s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 4]

Molecules Loaded: ['conf_23.feather'] Failed Molecules: []

 62%|██████▏   | 192/308 [04:54<02:54,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_23 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_23 for [2, 4]

Molecules Loaded: ['conf_24.feather'] Failed Molecules: []

 63%|██████▎   | 193/308 [04:56<02:51,  1.49s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_24 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_24 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 63%|██████▎   | 194/308 [04:57<02:51,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 63%|██████▎   | 195/308 [04:59<02:51,  1.52s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 64%|██████▎   | 196/308 [05:00<02:52,  1.54s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 64%|██████▍   | 197/308 [05:02<02:48,  1.51s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_21.feather'] Failed Molecules: []

 64%|██████▍   | 198/308 [05:03<02:46,  1.51s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_21 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_21 for [2, 4]

Molecules Loaded: ['conf_19.feather'] Failed Molecules: []

 65%|██████▍   | 199/308 [05:05<02:44,  1.51s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_19 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_19 for [2, 4]

Molecules Loaded: ['conf_26.feather'] Failed Molecules: []

 65%|██████▍   | 200/308 [05:06<02:41,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_26 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_26 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 65%|██████▌   | 201/308 [05:08<02:39,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_17.feather'] Failed Molecules: []

 66%|██████▌   | 202/308 [05:09<02:38,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 4]

Molecules Loaded: ['conf_16.feather'] Failed Molecules: []

 66%|██████▌   | 203/308 [05:11<02:35,  1.48s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 4]

Molecules Loaded: ['conf_11.feather'] Failed Molecules: []

 66%|██████▌   | 204/308 [05:12<02:35,  1.49s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 4]

Molecules Loaded: ['conf_18.feather'] Failed Molecules: []

 67%|██████▋   | 205/308 [05:14<02:34,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_18 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_18 for [2, 4]

Molecules Loaded: ['conf_20.feather'] Failed Molecules: []

 67%|██████▋   | 206/308 [05:15<02:32,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_20 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_20 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 67%|██████▋   | 207/308 [05:17<02:31,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 68%|██████▊   | 208/308 [05:18<02:29,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 68%|██████▊   | 209/308 [05:20<02:28,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 68%|██████▊   | 210/308 [05:21<02:26,  1.50s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 69%|██████▊   | 211/308 [05:22<02:09,  1.34s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 69%|██████▉   | 212/308 [05:23<01:56,  1.21s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 69%|██████▉   | 213/308 [05:24<01:48,  1.15s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 69%|██████▉   | 214/308 [05:25<01:43,  1.10s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 70%|██████▉   | 215/308 [05:26<01:38,  1.06s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 70%|███████   | 216/308 [05:27<01:35,  1.04s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 70%|███████   | 217/308 [05:28<01:33,  1.02s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 71%|███████   | 218/308 [05:29<01:36,  1.07s/it]

Calculating stretch vibration for atoms [[6, 18], [18, 6], [5, 4], [4, 5], [2, 18], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 18]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 71%|███████   | 219/308 [05:31<01:39,  1.12s/it]

Calculating stretch vibration for atoms [[6, 18], [18, 6], [5, 4], [4, 5], [2, 18], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 18]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 71%|███████▏  | 220/308 [05:32<01:40,  1.14s/it]

Calculating stretch vibration for atoms [[6, 18], [18, 6], [5, 4], [4, 5], [2, 18], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 18]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 72%|███████▏  | 221/308 [05:33<01:40,  1.15s/it]

Calculating stretch vibration for atoms [[6, 18], [18, 6], [5, 4], [4, 5], [2, 18], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 18]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 72%|███████▏  | 222/308 [05:34<01:40,  1.17s/it]

Calculating stretch vibration for atoms [[6, 18], [18, 6], [5, 4], [4, 5], [2, 18], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 18]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 72%|███████▏  | 223/308 [05:35<01:40,  1.18s/it]

Calculating stretch vibration for atoms [[6, 18], [18, 6], [5, 4], [4, 5], [2, 18], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 18]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_14.feather'] Failed Molecules: []

 73%|███████▎  | 224/308 [05:37<01:41,  1.21s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 4]

Molecules Loaded: ['conf_13.feather'] Failed Molecules: []

 73%|███████▎  | 225/308 [05:38<01:40,  1.22s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 4]

Molecules Loaded: ['conf_12.feather'] Failed Molecules: []

 73%|███████▎  | 226/308 [05:39<01:40,  1.22s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 4]

Molecules Loaded: ['conf_15.feather'] Failed Molecules: []

 74%|███████▎  | 227/308 [05:40<01:39,  1.23s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 74%|███████▍  | 228/308 [05:42<01:38,  1.23s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 74%|███████▍  | 229/308 [05:43<01:37,  1.24s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 75%|███████▍  | 230/308 [05:44<01:36,  1.24s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 75%|███████▌  | 231/308 [05:45<01:35,  1.25s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_9.feather'] Failed Molecules: []

 75%|███████▌  | 232/308 [05:47<01:34,  1.24s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 76%|███████▌  | 233/308 [05:48<01:33,  1.24s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_17.feather'] Failed Molecules: []

 76%|███████▌  | 234/308 [05:49<01:32,  1.25s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 4]

Molecules Loaded: ['conf_16.feather'] Failed Molecules: []

 76%|███████▋  | 235/308 [05:50<01:30,  1.24s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 4]

Molecules Loaded: ['conf_11.feather'] Failed Molecules: []

 77%|███████▋  | 236/308 [05:52<01:30,  1.25s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 77%|███████▋  | 237/308 [05:53<01:28,  1.25s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 77%|███████▋  | 238/308 [05:54<01:26,  1.24s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 78%|███████▊  | 239/308 [05:55<01:26,  1.25s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 78%|███████▊  | 240/308 [05:57<01:24,  1.24s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 78%|███████▊  | 241/308 [05:58<01:18,  1.17s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 79%|███████▊  | 242/308 [05:58<01:13,  1.11s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 79%|███████▉  | 243/308 [06:00<01:10,  1.08s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 79%|███████▉  | 244/308 [06:01<01:08,  1.06s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 80%|███████▉  | 245/308 [06:02<01:05,  1.04s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 80%|███████▉  | 246/308 [06:03<01:04,  1.04s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 80%|████████  | 247/308 [06:04<01:03,  1.03s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 81%|████████  | 248/308 [06:05<01:02,  1.04s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 81%|████████  | 249/308 [06:06<01:00,  1.03s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 81%|████████  | 250/308 [06:07<00:59,  1.03s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 81%|████████▏ | 251/308 [06:08<00:58,  1.03s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 82%|████████▏ | 252/308 [06:08<00:53,  1.05it/s]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 82%|████████▏ | 253/308 [06:09<00:48,  1.13it/s]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 82%|████████▏ | 254/308 [06:10<00:46,  1.17it/s]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 83%|████████▎ | 255/308 [06:11<00:43,  1.21it/s]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 83%|████████▎ | 256/308 [06:12<00:49,  1.06it/s]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 83%|████████▎ | 257/308 [06:13<00:51,  1.01s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 84%|████████▍ | 258/308 [06:14<00:52,  1.05s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 84%|████████▍ | 259/308 [06:15<00:49,  1.01s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 84%|████████▍ | 260/308 [06:16<00:46,  1.03it/s]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_13.feather'] Failed Molecules: []

 85%|████████▍ | 261/308 [06:17<00:51,  1.09s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 4]

Molecules Loaded: ['conf_12.feather'] Failed Molecules: []

 85%|████████▌ | 262/308 [06:19<00:54,  1.18s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 85%|████████▌ | 263/308 [06:20<00:56,  1.26s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 86%|████████▌ | 264/308 [06:22<00:56,  1.29s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 86%|████████▌ | 265/308 [06:23<00:56,  1.31s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 86%|████████▋ | 266/308 [06:24<00:56,  1.34s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_9.feather'] Failed Molecules: []

 87%|████████▋ | 267/308 [06:26<00:55,  1.35s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 87%|████████▋ | 268/308 [06:27<00:54,  1.36s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_11.feather'] Failed Molecules: []

 87%|████████▋ | 269/308 [06:29<00:53,  1.37s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 88%|████████▊ | 270/308 [06:30<00:51,  1.37s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 88%|████████▊ | 271/308 [06:31<00:50,  1.37s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 88%|████████▊ | 272/308 [06:33<00:49,  1.38s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 89%|████████▊ | 273/308 [06:34<00:48,  1.38s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 89%|████████▉ | 274/308 [06:35<00:42,  1.24s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 89%|████████▉ | 275/308 [06:36<00:37,  1.13s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 90%|████████▉ | 276/308 [06:37<00:38,  1.19s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 90%|████████▉ | 277/308 [06:38<00:37,  1.22s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 90%|█████████ | 278/308 [06:40<00:37,  1.24s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 91%|█████████ | 279/308 [06:41<00:36,  1.26s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_9.feather'] Failed Molecules: []

 91%|█████████ | 280/308 [06:42<00:35,  1.28s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 91%|█████████ | 281/308 [06:44<00:34,  1.28s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 92%|█████████▏| 282/308 [06:45<00:33,  1.28s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 92%|█████████▏| 283/308 [06:46<00:32,  1.28s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 92%|█████████▏| 284/308 [06:48<00:31,  1.30s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 93%|█████████▎| 285/308 [06:49<00:29,  1.30s/it]

Calculating stretch vibration for atoms [[6, 19], [19, 6], [5, 4], [4, 5], [2, 19], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 19]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 93%|█████████▎| 286/308 [06:50<00:28,  1.27s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_12.feather'] Failed Molecules: []

 93%|█████████▎| 287/308 [06:51<00:25,  1.24s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 94%|█████████▎| 288/308 [06:52<00:24,  1.21s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 94%|█████████▍| 289/308 [06:54<00:22,  1.19s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 94%|█████████▍| 290/308 [06:55<00:21,  1.19s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 94%|█████████▍| 291/308 [06:56<00:19,  1.18s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_9.feather'] Failed Molecules: []

 95%|█████████▍| 292/308 [06:57<00:18,  1.18s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 95%|█████████▌| 293/308 [06:58<00:17,  1.17s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_11.feather'] Failed Molecules: []

 95%|█████████▌| 294/308 [06:59<00:16,  1.18s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 96%|█████████▌| 295/308 [07:01<00:16,  1.23s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 96%|█████████▌| 296/308 [07:02<00:15,  1.32s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 96%|█████████▋| 297/308 [07:04<00:14,  1.31s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 97%|█████████▋| 298/308 [07:05<00:12,  1.25s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 97%|█████████▋| 299/308 [07:06<00:10,  1.18s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 97%|█████████▋| 300/308 [07:07<00:09,  1.14s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 98%|█████████▊| 301/308 [07:08<00:07,  1.10s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 98%|█████████▊| 302/308 [07:09<00:06,  1.09s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 98%|█████████▊| 303/308 [07:10<00:05,  1.05s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 99%|█████████▊| 304/308 [07:11<00:04,  1.01s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 99%|█████████▉| 305/308 [07:12<00:02,  1.00it/s]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 99%|█████████▉| 306/308 [07:13<00:01,  1.01it/s]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

100%|█████████▉| 307/308 [07:14<00:00,  1.03it/s]

Calculating stretch vibration for atoms [[6, 16], [16, 6], [5, 4], [4, 5], [2, 16], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 16]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

100%|██████████| 308/308 [07:14<00:00,  1.41s/it]

Calculating stretch vibration for atoms [[6, 16], [16, 6], [5, 4], [4, 5], [2, 16], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 16]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

,feather_dir,charge_NBO_H1,charge_NBO_H2,charge_NBO_C1,charge_NBO_C2,charge_NBO_N1,charge_NBO_N2,charge_NBO_Ni,B1_C1-N1,B5_C1-N1,L_C1-N1,loc_B5_C1-N1,B1-B5_angle_C1-N1,B1_N1-C1,B5_N1-C1,L_N1-C1,loc_B5_N1-C1,B1-B5_angle_N1-C1,B1_C2-N2,B5_C2-N2,L_C2-N2,loc_B5_C2-N2,B1-B5_angle_C2-N2,B1_N2-C2,B5_N2-C2,L_N2-C2,loc_B5_N2-C2,B1-B5_angle_N2-C2,B1_Ni-N1,B5_Ni-N1,L_Ni-N1,loc_B5_Ni-N1,B1-B5_angle_Ni-N1,B1_Ni-N2,B5_Ni-N2,L_Ni-N2,loc_B5_Ni-N2,B1-B5_angle_Ni-N2,B1_Ni-H1,B5_Ni-H1,L_Ni-H1,loc_B5_Ni-H1,B1-B5_angle_Ni-H1,B1_Ni-H2,B5_Ni-H2,L_Ni-H2,loc_B5_Ni-H2,B1-B5_angle_Ni-H2,B1_C1-C2,B5_C1-C2,L_C1-C2,loc_B5_C1-C2,B1-B5_angle_C1-C2,B1_C2-C1,B5_C2-C1,L_C2-C1,loc_B5_C2-C1,B1-B5_angle_C2-C1,dist_C1-N1,dist_N1-C1,dist_C2-N2,dist_N2-C2,dist_Ni-N1,dist_Ni-N2,dist_Ni-H1,dist_Ni-H2,dist_C1-C2,dist_C2-C1,vib_freq_C1-N1,vib_amp_C1-N1,vib_freq_N1-C1,vib_amp_N1-C1,vib_freq_C2-N2,vib_amp_C2-N2,vib_freq_N2-C2,vib_amp_N2-C2,vib_freq_Ni-N1,vib_amp_Ni-N1,vib_freq_Ni-N2,vib_amp_Ni-N2,vib_freq_Ni-H1,vib_amp_Ni-H1,vib_freq_Ni-H2,vib_amp_Ni-H2,vib_freq_C1-C2,vib_amp_C1-C2,vib_freq_C2-C1,vib_amp_C2-C1,vib_freq_bend_H1-H2,vib_amp_bend_H1-H2,vib_freq_bend_N1-C2,vib_amp_bend_N1-C2,vib_freq_bend_N2-C1,vib_amp_bend_N2-C1,charge_NBO_diff_C1-N1,charge_NBO_diff_N1-C1,charge_NBO_diff_C2-N2,charge_NBO_diff_N2-C2,charge_NBO_diff_Ni-N1,charge_NBO_diff_Ni-N2,charge_NBO_diff_Ni-H1,charge_NBO_diff_Ni-H2,charge_NBO_diff_C1-C2,charge_NBO_diff_C2-C1,dipole,dipole_x_Ni-N2-N1,dipole_y_Ni-N2-N1,dipole_z_Ni-N2-N1,angle_H2-Ni-H1,angle_Ni-N1-C1,angle_Ni-N2-C2,angle_N1-C1-C2,angle_N2-C2-C1,angle_N1-Ni-N2,angle_C1-Ni-C2
0,DATA/LNiH2_library_001_to_download_2026_03_24/...,-0.21653,-0.22963,0.11686,0.50297,-0.46491,-0.47278,0.37908,1.6991,4.3120,4.6065,1.8397,179.9947,1.8611,8.4536,5.8585,2.4020,136.5252,1.6991,6.8659,5.3416,2.8889,124.7608,1.9308,6.8659,5.9723,-1.6114,151.5772,2.0079,7.9342,6.8193,-0.4638,140.4172,2.0809,6.6878,7.1104,1.3597,85.3772,1.919,1.9201,2.4654,0.0,34.5459,1.919,1.9201,2.4624,0.0,34.5459,1.8854,6.1346,6.7984,5.5038,159.5956,1.6998,3.9380,6.2132,3.7593,90.0509,1.353525,1.353525,1.277524,1.277524,1.997576,1.936436,1.465408,1.462377,1.455706,1.455706,1428.29,0.0,1428.29,0.0,1428.29,0.0,1428.29,0.0,NaN,NaN,NaN,NaN,1428.29,0.0,1428.29,0.0,1428.29,0.0,1428.29,0.0,1310.99,0.0,1310.99,0.0,1310.99,0.0,0.58177,-0.58177,0.97575,-0.97575,0.84399,0.85186,0.59561,0.60871,-0.38611,0.38611,3.749951,-0.222724,3.640507,0.871343,80.285471,112.981322,113.778353,111.707045,119.327386,82.181594,30.439763
1,DATA/LNiH2_library_001_to_download_2026_03_24/...,-0.21662,-0.23047,0.11683,0.50311,-0.46484,-0.47284,0.37963,1.6991,4.3119,4.6064,1.8398,179.9601,1.8636,8.4487,5.8557,2.4083,136.5769,1.6991,6.8727,5.3207,2.8673,124.8268,1.9325,6.8727,5.9731,-1.5897,152.5569,2.0133,7.9298,6.8194,-0.4775,140.3940,2.0665,6.6878,7.1048,4.0966,86.0972,1.919,1.9201,2.4659,0.0,34.5459,1.919,1.9201,2.4633,0.0,34.5459,1.8811,6.1351,6.7936,5.4978,159.8085,1.6998,3.9376,6.2134,3.7598,89.9782,1.353520,1.353520,1.277506,1.277506,1.997321,1.936877,1.465891,1.463258,1.455765,1.455765,1428.32,0.0,1428.32,0.0,1428.32,0.0,1428.32,0.0,NaN,NaN,NaN,NaN,1428.32,0.0,1428.32,0.0,1428.32,0.0,1428.32,0.0,1310.99,0.0,1310.99,0.0,1310.99,0.0,0.58167,-0.58167,0.97595,-0.97595,0.84447,0.85247,0.59625,0.61010,-0.38628,0.38628,3.744847,-0.222501,3.635383,0.870840,80.423241,112.983518,113.755704,111.715783,119.338751,82.195500,30.442192
2,DATA/LNiH2_library_001_to_download_2026_03_24/...,-0.21984,-0.23576,0.11566,0.51649,-0.42570,-0.49418,0.39430,1.6991,5.9192,4.6873,1.6383,166.6662,4.0773,7.9415,7.7080,2.1073,117.5082,1.6991,8.0730,6.1007,-0.8508,144.1682,4.0843,8.0728,6.0448,2.1300,68.8488,3.9375,9.9856,7.2960,1.2475,112.0676,4.9938,7.5671,8.9679,-1.3111,166.6627,1.919,1.9201,2.4620,0.0,34.5459,1.919,1.9201,2.4608,0.0,34.5459,3.9697,7.2447,7.6971,2.1121,69.2596,2.2372,3.3991,7.5498,3.6594,68.0624,1.342071,1.342071,1.279223,1.279223,1.952133,1.988616,1.461994,1.460825,1.457091,1.457091,1409.66,0.0,1409.66,0.0,1409.66,0.0,1409.66,0.0,NaN,NaN,NaN,NaN,1409.66,0.0,1409.66,0.0,1409.66,0.0,1409.66,0.0,1310.08,0.0,1310.08,0.0,1310.08,0.0,0.54136,-0.54136,1.01067,-1.01067,0.82000,0.88848,0.61414,0.63006,-0.40083,0.40083,4.218276,-0.191636,4.194527,0.403823,79.727500,113.673297,110.255129,112.146031,120.559021,83.229149,30.756295
3,DATA/LNiH2_library_001_to_download_2026_03_24/...,-0.23509,-0.22010,0.11644,0.50879,-0.42565,-0.49172,0.39549,1.6991,5.9033,4.6900,1.6685,166.1904,3.7659,7.9354,8.7209,2.1071,112.7100,1.6991,7.3963,6.1022,-2.5039,115.0607,4.0682,7.3963,6.0471,3.7832,167.0723,2.8839,9.7382,7.2526,2.6303,86.5389,4.3165,7.5396,9.5323,-1.3295,125.1639,1.919,1.9201,2.4607,0.0,34.5459,1.919,1.9201,2.4625,0.0,34.5459,3.4906,7.6830,7.6882,3.0440,167.2754,2.2769,3.3987,7.5470,3.6602,65.0976,1.342044,1.342044,1.279297,1.279297,1.952955,1.991251,1.460665,1.462452,1.457270,1.457270,1402.88,0.0,1402.88,0.0,1402.88,0.0,1402.88,0.0,NaN,NaN,NaN,NaN,1402.88,0.0,1402.88,0.0,1402.88,0.0,1402.88,0.0,1311.25,0.0,1311.25,0.0,1311.25,0.0,0.54209,-0.54209,1.00051,-1.00051,0.82114,0.88721,0.63058,0.61559,-0.39235,0.39235,4.672207,-0.013101,4.652063,0.433200,79.859309,113.698794,110.222900,112.176979,120.597080,83.200926,30.743563
4,DATA/LNiH2_library_001_to_download_2026_03_24/...,-0.23132,-0.21785,0.11222,0.51317,-0.42548,-0.50255,0.39070,1.6991,6.0319,4.5791,1.3674,172.6333,3.4649,8.4656,8.6375,6.0113,107.1316,1.6991,9.0696,5.2187,0.8650,177.9919,4.0064,9.0697,6.0784,0.4137,104.8587,3.9624,10.8459,7.6078,-1.4211,128.5645,4.1475,7.7984,10.5953,-1.0104,64.6715,1.919,1.9201,2.4686,0.0,34.5459,1.919,1.9201,2.4654,0.0,34.5459,3.6442,6.8481,9.8787,2.3512,135.6597,2.0623,3.4114,7.6100,3.6495,88.5588,1.345928,1.345928,1.278706,1.278706,1.959760,1.953338,1.468580,1.465423,1.457437,1.457437,1402.66,0.0,1402.66,0.0,1402.66,0.0,1402.66,0.0,NaN,NaN,NaN,NaN,1402.66,0.0,1402.66,0.0,1402.66,0.0,1402.66,0.0,1304.58,0.0,1304.58,0.0,1304.58,0.0,0.53770,-0.53770,1.01572,-1.01572,0.81618,0.89325,0.62202,0.60855,-0.40095,0.40095,4.716655,-0.341323,4.662591,-0.624966,81.140146,113.006447,111.529361,111.863869,119.423906,82.913154,30.826314

# Combining ORCA and DescriPyTor descriptors

In [14]:
import re

# --- 1) Build merge key (conf folder) for total_df ---
total_work = total_df.drop(columns=atoms).copy()

def _normalize_conf_dir(p):
    if pd.isna(p):
        return np.nan
    p = str(p).replace("\\", "/")
    if p.endswith(".feather"):
        p = os.path.dirname(p)
    p = p.rstrip("/")
    p = re.sub(r"^orca_descriptors/", "", p)  # align with df_desc paths
    return p

total_work["conf_dir"] = total_work["path"].map(_normalize_conf_dir)

# --- 2) Build merge key for df_desc ---
desc_work = df_desc.copy()
if "feather_dir" not in desc_work.columns:
    raise KeyError("df_desc must contain 'feather_dir'.")

desc_work["conf_dir"] = desc_work["feather_dir"].map(_normalize_conf_dir)

# --- 3) Combine descriptor tables ---
combined_df = total_work.merge(
    desc_work,
    on="conf_dir",
    how="outer",
    suffixes=("_total", "_desc")
)

# If duplicate energy columns exist, keep one unified SCF_energy
if "SCF_energy" not in combined_df.columns:
    scf_candidates = [c for c in combined_df.columns if c.startswith("SCF_energy")]
    if scf_candidates:
        combined_df["SCF_energy"] = combined_df[scf_candidates].bfill(axis=1).iloc[:, 0]

os.chdir(ROOT_DIR)
combined_df.to_csv("combined_descriptors.csv", index=False)

# --- 4) Group key = inchi folder (path without /conf_XX) ---
combined_df["inchi_folder"] = combined_df["conf_dir"].str.replace(
    r"/conf_\d+$", "", regex=True
)

# --- 5) Boltzmann aggregation per inchi folder ---
T = 298.15
kB_hartree_per_K = 3.166811563e-6  # Hartree/K

if "SCF_energy" not in combined_df.columns:
    raise KeyError("SCF_energy column not found after merge.")

numeric_cols = combined_df.select_dtypes(include=[np.number]).columns.tolist()

rows = []
for inchi_folder, g in combined_df.groupby("inchi_folder", dropna=True):
    g = g.copy()
    e = pd.to_numeric(g["SCF_energy"], errors="coerce")
    if e.notna().sum() == 0:
        continue

    e_min = e.min()
    idx_low = e.idxmin()

    dE = e - e_min
    w = np.exp(-(dE / (kB_hartree_per_K * T)))
    w = w / np.nansum(w)

    out = {
        "inchi_folder": inchi_folder,
        "inchi": os.path.basename(inchi_folder),
        "min_energy_value": e_min,
        "smiles": g["smiles"].iloc[0] if "smiles" in g.columns else np.nan,
        "ligand_class": g["ligand_class"].iloc[0] if "ligand_class" in g.columns else np.nan
    }

    for col in numeric_cols:
        v = pd.to_numeric(g[col], errors="coerce")

        out[f"{col}_min"] = v.min()
        out[f"{col}_max"] = v.max()
        out[f"{col}_lowE"] = g.loc[idx_low, col] if idx_low in g.index else np.nan

        valid = v.notna() & w.notna()
        out[f"{col}_boltz"] = (
            np.average(v[valid], weights=w[valid]) if valid.any() else np.nan
        )

    rows.append(out)

df_boltzmann_summary = pd.DataFrame(rows).sort_values("inchi_folder").reset_index(drop=True)
df_boltzmann_summary.drop(columns=["min_energy_value"], inplace=True)

print("combined_df shape:", combined_df.shape)
print("df_boltzmann_summary shape:", df_boltzmann_summary.shape)
df_boltzmann_summary.head()

combined_df shape: (308, 626)
df_boltzmann_summary shape: (38, 2396)

,inchi_folder,inchi,smiles,ligand_class,%Vbur_atom_C1_radius_2.0_min,%Vbur_atom_C1_radius_2.0_max,%Vbur_atom_C1_radius_2.0_lowE,%Vbur_atom_C1_radius_2.0_boltz,%Vbur_atom_C1_radius_2.5_min,%Vbur_atom_C1_radius_2.5_max,%Vbur_atom_C1_radius_2.5_lowE,%Vbur_atom_C1_radius_2.5_boltz,%Vbur_atom_C1_radius_3.0_min,%Vbur_atom_C1_radius_3.0_max,%Vbur_atom_C1_radius_3.0_lowE,%Vbur_atom_C1_radius_3.0_boltz,%Vbur_atom_C1_radius_3.5_min,%Vbur_atom_C1_radius_3.5_max,%Vbur_atom_C1_radius_3.5_lowE,%Vbur_atom_C1_radius_3.5_boltz,%Vbur_atom_C1_radius_4.0_min,%Vbur_atom_C1_radius_4.0_max,%Vbur_atom_C1_radius_4.0_lowE,%Vbur_atom_C1_radius_4.0_boltz,%Vbur_atom_C1_radius_4.5_min,%Vbur_atom_C1_radius_4.5_max,%Vbur_atom_C1_radius_4.5_lowE,%Vbur_atom_C1_radius_4.5_boltz,%Vbur_atom_C1_radius_5.0_min,%Vbur_atom_C1_radius_5.0_max,%Vbur_atom_C1_radius_5.0_lowE,%Vbur_atom_C1_radius_5.0_boltz,%Vbur_atom_C2_radius_2.0_min,%Vbur_atom_C2_radius_2.0_max,%Vbur_atom_C2_radius_2.0_lowE,%Vbur_atom_C2_radius_2.0_boltz,%Vbur_atom_C2_radius_2.5_min,%Vbur_atom_C2_radius_2.5_max,%Vbur_atom_C2_radius_2.5_lowE,%Vbur_atom_C2_radius_2.5_boltz,%Vbur_atom_C2_radius_3.0_min,%Vbur_atom_C2_radius_3.0_max,%Vbur_atom_C2_radius_3.0_lowE,%Vbur_atom_C2_radius_3.0_boltz,%Vbur_atom_C2_radius_3.5_min,%Vbur_atom_C2_radius_3.5_max,%Vbur_atom_C2_radius_3.5_lowE,%Vbur_atom_C2_radius_3.5_boltz,%Vbur_atom_C2_radius_4.0_min,%Vbur_atom_C2_radius_4.0_max,%Vbur_atom_C2_radius_4.0_lowE,%Vbur_atom_C2_radius_4.0_boltz,%Vbur_atom_C2_radius_4.5_min,%Vbur_atom_C2_radius_4.5_max,%Vbur_atom_C2_radius_4.5_lowE,%Vbur_atom_C2_radius_4.5_boltz,%Vbur_atom_C2_radius_5.0_min,%Vbur_atom_C2_radius_5.0_max,%Vbur_atom_C2_radius_5.0_lowE,%Vbur_atom_C2_radius_5.0_boltz,%Vbur_atom_H1_radius_2.0_min,%Vbur_atom_H1_radius_2.0_max,%Vbur_atom_H1_radius_2.0_lowE,%Vbur_atom_H1_radius_2.0_boltz,%Vbur_atom_H1_radius_2.5_min,%Vbur_atom_H1_radius_2.5_max,%Vbur_atom_H1_radius_2.5_lowE,%Vbur_atom_H1_radius_2.5_boltz,%Vbur_atom_H1_radius_3.0_min,%Vbur_atom_H1_radius_3.0_max,%Vbur_atom_H1_radius_3.0_lowE,%Vbur_atom_H1_radius_3.0_boltz,%Vbur_atom_H1_radius_3.5_min,%Vbur_atom_H1_radius_3.5_max,%Vbur_atom_H1_radius_3.5_lowE,%Vbur_atom_H1_radius_3.5_boltz,%Vbur_atom_H1_radius_4.0_min,%Vbur_atom_H1_radius_4.0_max,%Vbur_atom_H1_radius_4.0_lowE,%Vbur_atom_H1_radius_4.0_boltz,%Vbur_atom_H1_radius_4.5_min,%Vbur_atom_H1_radius_4.5_max,%Vbur_atom_H1_radius_4.5_lowE,%Vbur_atom_H1_radius_4.5_boltz,%Vbur_atom_H1_radius_5.0_min,%Vbur_atom_H1_radius_5.0_max,%Vbur_atom_H1_radius_5.0_lowE,%Vbur_atom_H1_radius_5.0_boltz,%Vbur_atom_H2_radius_2.0_min,%Vbur_atom_H2_radius_2.0_max,%Vbur_atom_H2_radius_2.0_lowE,%Vbur_atom_H2_radius_2.0_boltz,%Vbur_atom_H2_radius_2.5_min,%Vbur_atom_H2_radius_2.5_max,%Vbur_atom_H2_radius_2.5_lowE,%Vbur_atom_H2_radius_2.5_boltz,%Vbur_atom_H2_radius_3.0_min,%Vbur_atom_H2_radius_3.0_max,%Vbur_atom_H2_radius_3.0_lowE,%Vbur_atom_H2_radius_3.0_boltz,%Vbur_atom_H2_radius_3.5_min,%Vbur_atom_H2_radius_3.5_max,%Vbur_atom_H2_radius_3.5_lowE,%Vbur_atom_H2_radius_3.5_boltz,%Vbur_atom_H2_radius_4.0_min,%Vbur_atom_H2_radius_4.0_max,%Vbur_atom_H2_radius_4.0_lowE,%Vbur_atom_H2_radius_4.0_boltz,%Vbur_atom_H2_radius_4.5_min,%Vbur_atom_H2_radius_4.5_max,%Vbur_atom_H2_radius_4.5_lowE,%Vbur_atom_H2_radius_4.5_boltz,%Vbur_atom_H2_radius_5.0_min,%Vbur_atom_H2_radius_5.0_max,%Vbur_atom_H2_radius_5.0_lowE,%Vbur_atom_H2_radius_5.0_boltz,%Vbur_atom_N1_radius_2.0_min,%Vbur_atom_N1_radius_2.0_max,%Vbur_atom_N1_radius_2.0_lowE,%Vbur_atom_N1_radius_2.0_boltz,%Vbur_atom_N1_radius_2.5_min,%Vbur_atom_N1_radius_2.5_max,%Vbur_atom_N1_radius_2.5_lowE,%Vbur_atom_N1_radius_2.5_boltz,%Vbur_atom_N1_radius_3.0_min,%Vbur_atom_N1_radius_3.0_max,%Vbur_atom_N1_radius_3.0_lowE,%Vbur_atom_N1_radius_3.0_boltz,%Vbur_atom_N1_radius_3.5_min,%Vbur_atom_N1_radius_3.5_max,%Vbur_atom_N1_radius_3.5_lowE,%Vbur_atom_N1_radius_3.5_boltz,%Vbur_atom_N1_radius_4.0_min,%Vbur_atom_N1_radius_4.0_max,%Vbur_atom_N1_radius_4.0_lowE,%Vbur_atom_N1_radius_4.0_boltz,%Vbur_atom_N1_radius_4.5_min,%Vbur_atom_N1_radius_4.5_max,%Vbur_atom_N1_radius_4.5_lowE,%Vbur_atom_N1_radius_4.5_boltz,%Vbur_atom_N1_radius_5.0_min,%Vbur_atom_N1_radius_5.0_max,%Vbur_atom_N1_radius_5.0_lowE,%Vbur_atom_N1_radius_5.0_boltz,%Vbur_atom_N2_radius_2.0_min,%Vbur_atom_N2_radius_2.0_max,%Vbur_atom_N2_radius_2.0_lowE,%Vbur_atom_N2_radius_2.0_boltz,%Vbur_atom_N2_radius_2.5_min,%Vbur_atom_N2_radius_2.5_max,%Vbur_atom_N2_radius_2.5_lowE,%Vbur_atom_N2_radius_2.5_boltz,%Vbur_atom_N2_radius_3.0_min,%Vbur_atom_N2_radius_3.0_max,%Vbur_atom_N2_radius_3.0_lowE,%Vbur_atom_N2_radius_3.0_boltz,%Vbur_atom_N2_radius_3.5_min,%Vbur_atom_N2_radius_3.5_max,%Vbur_atom_N2_radius_3.5_lowE,%Vbur_atom_N2_radius_3.5_boltz,%Vbur_atom_N2_radius_4.0_min,%Vbur_atom_N2_radius_4.0_max,%Vbur_atom_N2_radius_4.0_lowE,%Vbur_atom_N2_radius_4.0_boltz,%Vbur_atom_N2_radius_4.5_min,%Vbur_atom_N2_radius_4.5_max,%Vbur_atom_N2_radius_4.5_lowE,%Vbur_atom_N2_radius_4.5_boltz,%Vbur_atom_N2_radius_5.0_min,%Vbur_atom_N2_radius_5.0_max,%Vbur_atom_N2_radius_5.0_lowE,%Vbur_atom_N2_radius_5.0_boltz,%Vbur_atom_Ni_radius_2.0_min,%Vbur_atom_Ni_radius_2.0_max,%Vbur_atom_Ni_radius_2.0_lowE,%Vbur_atom_Ni_radius_2.0_boltz,%Vbur_atom_Ni_radius_2.5_min,%Vbur_atom_Ni_radius_2.5_max,%Vbur_atom_Ni_radius_2.5_lowE,%Vbur_atom_Ni_radius_2.5_boltz,%Vbur_atom_Ni_radius_3.0_min,%Vbur_atom_Ni_radius_3.0_max,%Vbur_atom_Ni_radius_3.0_lowE,%Vbur_atom_Ni_radius_3.0_boltz,%Vbur_atom_Ni_radius_3.5_min,%Vbur_atom_Ni_radius_3.5_max,%Vbur_atom_Ni_radius_3.5_lowE,%Vbur_atom_Ni_radius_3.5_boltz,%Vbur_atom_Ni_radius_4.0_min,%Vbur_atom_Ni_radius_4.0_max,%Vbur_atom_Ni_radius_4.0_lowE,%Vbur_atom_Ni_radius_4.0_boltz,%Vbur_atom_Ni_radius_4.5_min,%Vbur_atom_Ni_radius_4.5_max,%Vbur_atom_Ni_radius_4.5_lowE,%Vbur_atom_Ni_radius_4.5_boltz,%Vbur_atom_Ni_radius_5.0_min,%Vbur_atom_Ni_radius_5.0_max,%Vbur_atom_Ni_radius_5.0_lowE,%Vbur_atom_Ni_radius_5.0_boltz,Angle_C1_Ni_C2_min,Angle_C1_Ni_C2_max,Angle_C1_Ni_C2_lowE,Angle_C1_Ni_C2_boltz,Angle_H2_Ni_H1_min,Angle_H2_Ni_H1_max,Angle_H2_Ni_H1_lowE,Angle_H2_Ni_H1_boltz,Angle_N1_C1_C2_min,Angle_N1_C1_C2_max,Angle_N1_C1_C2_lowE,Angle_N1_C1_C2_boltz,Angle_N1_Ni_N2_min,Angle_N1_Ni_N2_max,Angle_N1_Ni_N2_lowE,Angle_N1_Ni_N2_boltz,Angle_N2_C2_C1_min,Angle_N2_C2_C1_max,Angle_N2_C2_C1_lowE,Angle_N2_C2_C1_boltz,Angle_Ni_N1_C1_min,Angle_Ni_N1_C1_max,Angle_Ni_N1_C1_lowE,Angle_Ni_N1_C1_boltz,Angle_Ni_N2_C2_min,Angle_Ni_N2_C2_max,Angle_Ni_N2_C2_lowE,Angle_Ni_N2_C2_boltz,Bond_C1_C2_min,Bond_C1_C2_max,Bond_C1_C2_lowE,Bond_C1_C2_boltz,Bond_C1_N1_min,Bond_C1_N1_max,Bond_C1_N1_lowE,Bond_C1_N1_boltz,Bond_C2_C1_min,Bond_C2_C1_max,Bond_C2_C1_lowE,Bond_C2_C1_boltz,Bond_C2_N2_min,Bond_C2_N2_max,Bond_C2_N2_lowE,Bond_C2_N2_boltz,Bond_N1_C1_min,Bond_N1_C1_max,Bond_N1_C1_lowE,Bond_N1_C1_boltz,Bond_N2_C2_min,Bond_N2_C2_max,Bond_N2_C2_lowE,Bond_N2_C2_boltz,Bond_Ni_H1_min,Bond_Ni_H1_max,Bond_Ni_H1_lowE,Bond_Ni_H1_boltz,Bond_Ni_H2_min,Bond_Ni_H2_max,Bond_Ni_H2_lowE,Bond_Ni_H2_boltz,Bond_Ni_N1_min,Bond_Ni_N1_max,Bond_Ni_N1_lowE,Bond_Ni_N1_boltz,Bond_Ni_N2_min,Bond_Ni_N2_max,Bond_Ni_N2_lowE,Bond_Ni_N2_boltz,Dihed_C1_C2_N2_Ni_min,Dihed_C1_C2_N2_Ni_max,Dihed_C1_C2_N2_Ni_lowE,Dihed_C1_C2_N2_Ni_boltz,Dihed_C2_C1_N1_Ni_min,Dihed_C2_C1_N1_Ni_max,Dihed_C2_C1_N1_Ni_lowE,Dihed_C2_C1_N1_Ni_boltz,Dihed_N1_C1_C2_N2_min,Dihed_N1_C1_C2_N2_max,Dihed_N1_C1_C2_N2_lowE,Dihed_N1_C1_C2_N2_boltz,Pyr_C1_min,Pyr_C1_max,Pyr_C1_lowE,Pyr_C1_boltz,Pyr_C2_min,Pyr_C2_max,Pyr_C2_lowE,Pyr_C2_boltz,Pyr_N1_min,Pyr_N1_max,Pyr_N1_lowE,Pyr_N1_boltz,Pyr_N2_min,Pyr_N2_max,Pyr_N2_lowE,Pyr_N2_boltz,Pyr_angle_C1_min,Pyr_angle_C1_max,Pyr_angle_C1_lowE,Pyr_angle_C1_boltz,Pyr_angle_C2_min,Pyr_angle_C2_max,Pyr_angle_C2_lowE,Pyr_angle_C2_boltz,Pyr_angle_N1_min,Pyr_angle_N1_max,Pyr_angle_N1_lowE,Pyr_angle_N1_boltz,Pyr_angle_N2_min,Pyr_angle_N2_max,Pyr_angle_N2_lowE,Pyr_angle_N2_boltz,SASA_min,SASA_max,SASA_lowE,SASA_boltz,SASA_C1_min,SASA_C1_max,SASA_C1_lowE,SASA_C1_boltz,SASA_C2_min,SASA_C2_max,SASA_C2_lowE,SASA_C2_boltz,SASA_H1_min,SASA_H1_max,SASA_H1_lowE,SASA_H1_boltz,SASA_H2_min,SASA_H2_max,SASA_H2_lowE,SASA_H2_boltz,SASA_N1_min,SASA_N1_max,SASA_N1_lowE,SASA_N1_boltz,SASA_N2_min,SASA_N2_max,SASA_N2_lowE,SASA_N2_boltz,SASA_Ni_min,SASA_Ni_max,SASA_Ni_lowE,SASA_Ni_boltz,SASA_Volume_min,SASA_Volume_max,SASA_Volume_lowE,SASA_Volume_boltz,Sterimol_C1_C2_Bmax_min,Sterimol_C1_C2_Bmax_max,Sterimol_C1_C2_Bmax_lowE,Sterimol_C1_C2_Bmax_boltz,Sterimol_C1_C2_Bmin_min,Sterimol_C1_C2_Bmin_max,Sterimol_C1_C2_Bmin_lowE,Sterimol_C1_C2_Bmin_boltz,Sterimol_C1_C2_L_min,Sterimol_C1_C2_L_max,Sterimol_C1_C2_L_lowE,Sterimol_C1_C2_L_boltz,Sterimol_C1_N1_Bmax_min,Sterimol_C1_N1_Bmax_max,Sterimol_C1_N1_Bmax_lowE,Sterimol_C1_N1_Bmax_boltz,Sterimol_C1_N1_Bmin_min,Sterimol_C1_N1_Bmin_max,Sterimol_C1_N1_Bmin_lowE,Sterimol_C1_N1_Bmin_boltz,Sterimol_C1_N1_L_min,Sterimol_C1_N1_L_max,Sterimol_C1_N1_L_lowE,Sterimol_C1_N1_L_boltz,Sterimol_C2_C1_Bmax_min,Sterimol_C2_C1_Bmax_max,Sterimol_C2_C1_Bmax_lowE,Sterimol_C2_C1_Bmax_boltz,Sterimol_C2_C1_Bmin_min,Sterimol_C2_C1_Bmin_max,Sterimol_C2_C1_Bmin_lowE,Sterimol_C2_C1_Bmin_boltz,Sterimol_C2_C1_L_min,Sterimol_C2_C1_L_max,Sterimol_C2_C1_L_lowE,Sterimol_C2_C1_L_boltz,Sterimol_C2_N2_Bmax_min,Sterimol_C2_N2_Bmax_max,Sterimol_C2_N2_Bmax_lowE,Sterimol_C2_N2_Bmax_boltz,Sterimol_C2_N2_Bmin_min,Sterimol_C2_N2_Bmin_max,Sterimol_C2_N2_Bmin_lowE,Sterimol_C2_N2_Bmin_boltz,Sterimol_C2_N2_L_min,Sterimol_C2_N2_L_max,Sterimol_C2_N2_L_lowE,Sterimol_C2_N2_L_boltz,Sterimol_N1_C1_Bmax_min,Sterimol_N1_C1_Bmax_max,Sterimol_N1_C1_Bmax_lowE,Sterimol_N1_C1_Bmax_boltz,Sterimol_N1_C1_Bmin_min,Sterimol_N1_C1_Bmin_max,Sterimol_N1_C1_Bmin_lowE,Sterimol_N1_C1_Bmin_boltz,Sterimol_N1_C1_L_min,Sterimol_N1_C1_L_max,Sterimol_N1_C1_L_lowE,Sterimol_N1_C1_L_boltz,Sterimol_N2_C2_Bmax_min,Sterimol_N2_C2_Bmax_max,Sterimol_N2_C2_Bmax_lowE,Sterimol_N2_C2_Bmax_boltz,Sterimol_N2_C2_Bmin_min,Sterimol_N2_C2_Bmin_max,Sterimol_N2_C2_Bmin_lowE,Sterimol_N2_C2_Bmin_boltz,Sterimol_N2_C2_L_min,Sterimol_N2_C2_L_max,Sterimol_N2_C2_L_lowE,Sterimol_N2_C2_L_boltz,Sterimol_Ni_H1_Bmax_min,Sterimol_Ni_H1_Bmax_max,Sterimol_Ni_H1_Bmax_lowE,Sterimol_Ni_H1_Bmax_boltz,Sterimol_Ni_H1_Bmin_min,Sterimol_Ni_H1_Bmin_max,Sterimol_Ni_H1_Bmin_lowE,Sterimol_Ni_H1_Bmin_boltz,Sterimol_Ni_H1_L_min,Sterimol_Ni_H1_L_max,Sterimol_Ni_H1_L_lowE,Sterimol_Ni_H1_L_boltz,Sterimol_Ni_H2_Bmax_min,Sterimol_Ni_H2_Bmax_max,Sterimol_Ni_H2_Bmax_lowE,Sterimol_Ni_H2_Bmax_boltz,Sterimol_Ni_H2_Bmin_min,Sterimol_Ni_H2_Bmin_max,Sterimol_Ni_H2_Bmin_lowE,Sterimol_Ni_H2_Bmin_boltz,Sterimol_Ni_H2_L_min,Sterimol_Ni_H2_L_max,Sterimol_Ni_H2_L_lowE,Sterimol_Ni_H2_L_boltz,Sterimol_Ni_N1_Bmax_min,Sterimol_Ni_N1_Bmax_max,Sterimol_Ni_N1_Bmax_lowE,Sterimol_Ni_N1_Bmax_boltz,Sterimol_Ni_N1_Bmin_min,Sterimol_Ni_N1_Bmin_max,Sterimol_Ni_N1_Bmin_lowE,Sterimol_Ni_N1_Bmin_boltz,Sterimol_Ni_N1_L_min,Sterimol_Ni_N1_L_max,Sterimol_Ni_N1_L_lowE,Sterimol_Ni_N1_L_boltz,Sterimol_Ni_N2_Bmax_min,Sterimol_Ni_N2_Bmax_max,Sterimol_Ni_N2_Bmax_lowE,Sterimol_Ni_N2_Bmax_boltz,Sterimol_Ni_N2_Bmin_min,Sterimol_Ni_N2_Bmin_max,Sterimol_Ni_N2_Bmin_lowE,Sterimol_Ni_N2_Bmin_boltz,Sterimol_Ni_N2_L_min,Sterimol_Ni_N2_L_max,Sterimol_Ni_N2_L_lowE,Sterimol_Ni_N2_L_boltz,mulliken_H1_min,mulliken_H1_max,mulliken_H1_lowE,mulliken_H1_boltz,mulliken_H2_min,mulliken_H2_max,mulliken_H2_lowE,mulliken_H2_boltz,mulliken_C1_min,mulliken_C1_max,mulliken_C1_lowE,mulliken_C1_boltz,mulliken_C2_min,mulliken_C2_max,mulliken_C2_lowE,mulliken_C2_boltz,mulliken_N1_min,mulliken_N1_max,mulliken_N1_lowE,mulliken_N1_boltz,mulliken_N2_min,mulliken_N2_max,mulliken_N2_lowE,mulliken_N2_boltz,mulliken_Ni_min,mulliken_Ni_max,mulliken_Ni_lowE,mulliken_Ni_boltz,loewdin_H1_min,loewdin_H1_max,loewdin_H1_lowE,loewdin_H1_boltz,loewdin_H2_min,loewdin_H2_max,loewdin_H2_lowE,loewdin_H2_boltz,loewdin_C1_min,loewdin_C1_max,loewdin_C1_lowE,loewdin_C1_boltz,loewdin_C2_min,loewdin_C2_max,loewdin_C2_lowE,loewdin_C2_boltz,loewdin_N1_min,loewdin_N1_max,loewdin_N1_lowE,loewdin_N1_boltz,loewdin_N2_min,loewdin_N2_max,loewdin_N2_lowE,loewdin_N2_boltz,loewdin_Ni_min,loewdin_Ni_max,loewdin_Ni_lowE,loewdin_Ni_boltz,chelpG_H1_min,chelpG_H1_max,chelpG_H1_lowE,chelpG_H1_boltz,chelpG_H2_min,chelpG_H2_max,chelpG_H2_lowE,chelpG_H2_boltz,chelpG_C1_min,chelpG_C1_max,chelpG_C1_lowE,chelpG_C1_boltz,chelpG_C2_min,chelpG_C2_max,chelpG_C2_lowE,chelpG_C2_boltz,chelpG_N1_min,chelpG_N1_max,chelpG_N1_lowE,chelpG_N1_boltz,chelpG_N2_min,chelpG_N2_max,chelpG_N2_lowE,chelpG_N2_boltz,chelpG_Ni_min,chelpG_Ni_max,chelpG_Ni_lowE,chelpG_Ni_boltz,hirshfeld_H1_min,hirshfeld_H1_max,hirshfeld_H1_lowE,hirshfeld_H1_boltz,hirshfeld_H2_min,hirshfeld_H2_max,hirshfeld_H2_lowE,hirshfeld_H2_boltz,hirshfeld_C1_min,hirshfeld_C1_max,hirshfeld_C1_lowE,hirshfeld_C1_boltz,hirshfeld_C2_min,hirshfeld_C2_max,hirshfeld_C2_lowE,hirshfeld_C2_boltz,hirshfeld_N1_min,hirshfeld_N1_max,hirshfeld_N1_lowE,hirshfeld_N1_boltz,hirshfeld_N2_min,hirshfeld_N2_max,hirshfeld_N2_lowE,hirshfeld_N2_boltz,hirshfeld_Ni_min,hirshfeld_Ni_max,hirshfeld_Ni_lowE,hirshfeld_Ni_boltz,cm5_H1_min,cm5_H1_max,cm5_H1_lowE,cm5_H1_boltz,cm5_H2_min,cm5_H2_max,cm5_H2_lowE,cm5_H2_boltz,cm5_C1_min,cm5_C1_max,cm5_C1_lowE,cm5_C1_boltz,cm5_C2_min,cm5_C2_max,cm5_C2_lowE,cm5_C2_boltz,cm5_N1_min,cm5_N1_max,cm5_N1_lowE,cm5_N1_boltz,cm5_N2_min,cm5_N2_max,cm5_N2_lowE,cm5_N2_boltz,cm5_Ni_min,cm5_Ni_max,cm5_Ni_lowE,cm5_Ni_boltz,HOMO_energy_min,HOMO_energy_max,HOMO_energy_lowE,HOMO_energy_boltz,LUMO_energy_min,LUMO_energy_max,LUMO_energy_lowE,LUMO_energy_boltz,saniso_H1_min,saniso_H1_max,saniso_H1_lowE,saniso_H1_boltz,saniso_H2_min,saniso_H2_max,saniso_H2_lowE,saniso_H2_boltz,saniso_C1_min,saniso_C1_max,saniso_C1_lowE,saniso_C1_boltz,saniso_C2_min,saniso_C2_max,saniso_C2_lowE,saniso_C2_boltz,saniso_N1_min,saniso_N1_max,saniso_N1_lowE,saniso_N1_boltz,saniso_N2_min,saniso_N2_max,saniso_N2_lowE,saniso_N2_boltz,saniso_Ni_min,saniso_Ni_max,saniso_Ni_lowE,saniso_Ni_boltz,siso_H1_min,siso_H1_max,siso_H1_lowE,siso_H1_boltz,siso_H2_min,siso_H2_max,siso_H2_lowE,siso_H2_boltz,siso_C1_min,siso_C1_max,siso_C1_lowE,siso_C1_boltz,siso_C2_min,siso_C2_max,siso_C2_lowE,siso_C2_boltz,siso_N1_min,siso_N1_max,siso_N1_lowE,siso_N1_boltz,siso_N2_min,siso_N2_max,siso_N2_lowE,siso_N2_boltz,siso_Ni_min,siso_Ni_max,siso_Ni_lowE,siso_Ni_boltz,Vertical_Ionization_Potential_min,Vertical_Ionization_Potential_max,Vertical_Ionization_Potential_lowE,Vertical_Ionization_Potential_boltz,Vertical_Electron_Affinity_min,Vertical_Electron_Affinity_max,Vertical_Electron_Affinity_lowE,Vertical_Electron_Affinity_boltz,Hardness_min,Hardness_max,Hardness_lowE,Hardness_boltz,Electronegativity_min,Electronegativity_max,Electronegativity_lowE,Electronegativity_boltz,Electrophilicity_min,Electrophilicity_max,Electrophilicity_lowE,Electrophilicity_boltz,fplus_nbo_charge_H1_min,fplus_nbo_charge_H1_max,fplus_nbo_charge_H1_lowE,fplus_nbo_charge_H1_boltz,fminus_nbo_charge_H1_min,fminus_nbo_charge_H1_max,fminus_nbo_charge_H1_lowE,fminus_nbo_charge_H1_boltz,fzero_nbo_charge_H1_min,fzero_nbo_charge_H1_max,fzero_nbo_charge_H1_lowE,fzero_nbo_charge_H1_boltz,fplus_nbo_charge_H2_min,fplus_nbo_charge_H2_max,fplus_nbo_charge_H2_lowE,fplus_nbo_charge_H2_boltz,fminus_nbo_charge_H2_min,fminus_nbo_charge_H2_max,fminus_nbo_charge_H2_lowE,fminus_nbo_charge_H2_boltz,fzero_nbo_charge_H2_min,fzero_nbo_charge_H2_max,fzero_nbo_charge_H2_lowE,fzero_nbo_charge_H2_boltz,fplus_nbo_charge_C1_min,fplus_nbo_charge_C1_max,fplus_nbo_charge_C1_lowE,fplus_nbo_charge_C1_boltz,fminus_nbo_charge_C1_min,fminus_nbo_charge_C1_max,fminus_nbo_charge_C1_lowE,fminus_nbo_charge_C1_boltz,fzero_nbo_charge_C1_min,fzero_nbo_charge_C1_max,fzero_nbo_charge_C1_lowE,fzero_nbo_charge_C1_boltz,fplus_nbo_charge_C2_min,fplus_nbo_charge_C2_max,fplus_nbo_charge_C2_lowE,fplus_nbo_charge_C2_boltz,fminus_nbo_charge_C2_min,fminus_nbo_charge_C2_max,fminus_nbo_charge_C2_lowE,fminus_nbo_charge_C2_boltz,fzero_nbo_charge_C2_min,fzero_nbo_charge_C2_max,fzero_nbo_charge_C2_lowE,fzero_nbo_charge_C2_boltz,fplus_nbo_charge_N1_min,fplus_nbo_charge_N1_max,fplus_nbo_charge_N1_lowE,fplus_nbo_charge_N1_boltz,fminus_nbo_charge_N1_min,fminus_nbo_charge_N1_max,fminus_nbo_charge_N1_lowE,fminus_nbo_charge_N1_boltz,fzero_nbo_charge_N1_min,fzero_nbo_charge_N1_max,fzero_nbo_charge_N1_lowE,fzero_nbo_charge_N1_boltz,fplus_nbo_charge_N2_min,fplus_nbo_charge_N2_max,fplus_nbo_charge_N2_lowE,fplus_nbo_charge_N2_boltz,fminus_nbo_charge_N2_min,fminus_nbo_charge_N2_max,fminus_nbo_charge_N2_lowE,fminus_nbo_charge_N2_boltz,fzero_nbo_charge_N2_min,fzero_nbo_charge_N2_max,fzero_nbo_charge_N2_lowE,fzero_nbo_charge_N2_boltz,fplus_nbo_charge_Ni_min,fplus_nbo_charge_Ni_max,fplus_nbo_charge_Ni_lowE,fplus_nbo_charge_Ni_boltz,fminus_nbo_charge_Ni_min,fminus_nbo_charge_Ni_max,fminus_nbo_charge_Ni_lowE,fminus_nbo_charge_Ni_boltz,fzero_nbo_charge_Ni_min,fzero_nbo_charge_Ni_max,fzero_nbo_charge_Ni_lowE,fzero_nbo_charge_Ni_boltz,fplus_cm5_H1_min,fplus_cm5_H1_max,fplus_cm5_H1_lowE,fplus_cm5_H1_boltz,fminus_cm5_H1_min,fminus_cm5_H1_max,fminus_cm5_H1_lowE,fminus_cm5_H1_boltz,fzero_cm5_H1_min,fzero_cm5_H1_max,fzero_cm5_H1_lowE,fzero_cm5_H1_boltz,fplus_cm5_H2_min,fplus_cm5_H2_max,fplus_cm5_H2_lowE,fplus_cm5_H2_boltz,fminus_cm5_H2_min,fminus_cm5_H2_max,fminus_cm5_H2_lowE,fminus_cm5_H2_boltz,fzero_cm5_H2_min,fzero_cm5_H2_max,fzero_cm5_H2_lowE,fzero_cm5_H2_boltz,fplus_cm5_C1_min,fplus_cm5_C1_max,fplus_cm5_C1_lowE,fplus_cm5_C1_boltz,fminus_cm5_C1_min,fminus_cm5_C1_max,fminus_cm5_C1_lowE,fminus_cm5_C1_boltz,fzero_cm5_C1_min,fzero_cm5_C1_max,fzero_cm5_C1_lowE,fzero_cm5_C1_boltz,fplus_cm5_C2_min,fplus_cm5_C2_max,fplus_cm5_C2_lowE,fplus_cm5_C2_boltz,fminus_cm5_C2_min,fminus_cm5_C2_max,fminus_cm5_C2_lowE,fminus_cm5_C2_boltz,fzero_cm5_C2_min,fzero_cm5_C2_max,fzero_cm5_C2_lowE,fzero_cm5_C2_boltz,fplus_cm5_N1_min,fplus_cm5_N1_max,fplus_cm5_N1_lowE,fplus_cm5_N1_boltz,fminus_cm5_N1_min,fminus_cm5_N1_max,fminus_cm5_N1_lowE,fminus_cm5_N1_boltz,fzero_cm5_N1_min,fzero_cm5_N1_max,fzero_cm5_N1_lowE,fzero_cm5_N1_boltz,fplus_cm5_N2_min,fplus_cm5_N2_max,fplus_cm5_N2_lowE,fplus_cm5_N2_boltz,fminus_cm5_N2_min,fminus_cm5_N2_max,fminus_cm5_N2_lowE,fminus_cm5_N2_boltz,fzero_cm5_N2_min,fzero_cm5_N2_max,fzero_cm5_N2_lowE,fzero_cm5_N2_boltz,fplus_cm5_Ni_min,fplus_cm5_Ni_max,fplus_cm5_Ni_lowE,fplus_cm5_Ni_boltz,fminus_cm5_Ni_min,fminus_cm5_Ni_max,fminus_cm5_Ni_lowE,fminus_cm5_Ni_boltz,fzero_cm5_Ni_min,fzero_cm5_Ni_max,fzero_cm5_Ni_lowE,fzero_cm5_Ni_boltz,npa_H1_charge_min,npa_H1_charge_max,npa_H1_charge_lowE,npa_H1_charge_boltz,npa_H1_core_min,npa_H1_core_max,npa_H1_core_lowE,npa_H1_core_boltz,npa_H1_valence_min,npa_H1_valence_max,npa_H1_valence_lowE,npa_H1_valence_boltz,npa_H1_rydberg_min,npa_H1_rydberg_max,npa_H1_rydberg_lowE,npa_H1_rydberg_boltz,npa_H1_total_min,npa_H1_total_max,npa_H1_total_lowE,npa_H1_total_boltz,npa_H2_charge_min,npa_H2_charge_max,npa_H2_charge_lowE,npa_H2_charge_boltz,npa_H2_core_min,npa_H2_core_max,npa_H2_core_lowE,npa_H2_core_boltz,npa_H2_valence_min,npa_H2_valence_max,npa_H2_valence_lowE,npa_H2_valence_boltz,npa_H2_rydberg_min,npa_H2_rydberg_max,npa_H2_rydberg_lowE,npa_H2_rydberg_boltz,npa_H2_total_min,npa_H2_total_max,npa_H2_total_lowE,npa_H2_total_boltz,npa_C1_charge_min,npa_C1_charge_max,npa_C1_charge_lowE,npa_C1_charge_boltz,npa_C1_core_min,npa_C1_core_max,npa_C1_core_lowE,npa_C1_core_boltz,npa_C1_valence_min,npa_C1_valence_max,npa_C1_valence_lowE,npa_C1_valence_boltz,npa_C1_rydberg_min,npa_C1_rydberg_max,npa_C1_rydberg_lowE,npa_C1_rydberg_boltz,npa_C1_total_min,npa_C1_total_max,npa_C1_total_lowE,npa_C1_total_boltz,npa_C2_charge_min,npa_C2_charge_max,npa_C2_charge_lowE,npa_C2_charge_boltz,npa_C2_core_min,npa_C2_core_max,npa_C2_core_lowE,npa_C2_core_boltz,npa_C2_valence_min,npa_C2_valence_max,npa_C2_valence_lowE,npa_C2_valence_boltz,npa_C2_rydberg_min,npa_C2_rydberg_max,npa_C2_rydberg_lowE,npa_C2_rydberg_boltz,npa_C2_total_min,npa_C2_total_max,npa_C2_total_lowE,npa_C2_total_boltz,npa_N1_charge_min,npa_N1_charge_max,npa_N1_charge_lowE,npa_N1_charge_boltz,npa_N1_core_min,npa_N1_core_max,npa_N1_core_lowE,npa_N1_core_boltz,npa_N1_valence_min,npa_N1_valence_max,npa_N1_valence_lowE,npa_N1_valence_boltz,npa_N

In [15]:
ROOT_DIR

'/Users/julesschleinitz/Desktop/Code/orca_descriptors'

### Remove noisy descriptors

In [16]:
import importlib
import desc_utils.data_extraction as de

importlib.reload(de)

from desc_utils.data_extraction import filter_numeric_descriptors

df_num_desc_filtered, report = filter_numeric_descriptors(
    df_boltzmann_summary,
    remove_low_occupancy_nbo=True,
    occupancy_boltz_threshold=0.001,
    corr_threshold=0.95,
    corr_pruning_mode="bridge_star_centers", #"component_ranked",
    ratio_threshold=0.01,
    orbital_filter="remove rydbergs",
    cor_orbital_filter="remove cor",
    ni_orbital_filter="remove 4f rydbergs",    # new filter
    nmr_filter="remove aniso",
    bond_analysis_filter="remove phi theta",
)

print("Initial numeric descriptors:", report["initial_numeric_count"])
print("Removed (NBO low occupancy orbitals):", len(report["removed_low_occ_nbo_orbitals"]))
print("Removed (NBO low occupancy columns):", len(report["removed_low_occ_nbo_columns"]))
print("Removed (Rydberg, except Ni):", len(report["removed_rydberg"]))
print("Removed (Ni 4f Rydbergs):", len(report["removed_ni_4f_rydberg"]))
print("Removed (NMR aniso):", len(report["removed_nmr_aniso"]))
print("Removed (phi/theta bond analysis):", len(report["removed_phi_theta"]))
print("Removed (zero std):", len(report["removed_zero_std"]))
print("Removed (std/abs(mean) < 1%):", len(report["removed_low_ratio"]))
print("Removed (high correlation):", len(report["removed_high_corr"]))
print("Final numeric descriptors:", report["final_numeric_count"])

# filter_numeric_descriptors returns only numeric columns, so re-attach meta columns from df_boltzmann_summary
meta_cols = ["smiles", "inchi", "inchi_folder", "ligand_class"]
for col in meta_cols:
    if col in df_boltzmann_summary.columns:
        df_num_desc_filtered[col] = df_boltzmann_summary[col].values

df_num_desc_filtered.head()

Initial numeric descriptors: 2392
Removed (NBO low occupancy orbitals): 96
Removed (NBO low occupancy columns): 400
Removed (Rydberg, except Ni): 168
Removed (Ni 4f Rydbergs): 0
Removed (NMR aniso): 28
Removed (phi/theta bond analysis): 68
Removed (zero std): 132
Removed (std/abs(mean) < 1%): 335
Removed (high correlation): 650
Final numeric descriptors: 559

,%Vbur_atom_C1_radius_3.0_boltz,%Vbur_atom_C1_radius_4.5_max,%Vbur_atom_C1_radius_5.0_lowE,%Vbur_atom_C1_radius_5.0_boltz,%Vbur_atom_C2_radius_2.5_min,%Vbur_atom_C2_radius_3.5_max,%Vbur_atom_C2_radius_3.5_lowE,%Vbur_atom_C2_radius_3.5_boltz,%Vbur_atom_C2_radius_5.0_boltz,%Vbur_atom_H1_radius_2.0_min,%Vbur_atom_H1_radius_2.0_max,%Vbur_atom_H1_radius_2.0_lowE,%Vbur_atom_H1_radius_2.0_boltz,%Vbur_atom_H1_radius_2.5_min,%Vbur_atom_H1_radius_2.5_max,%Vbur_atom_H1_radius_2.5_lowE,%Vbur_atom_H1_radius_2.5_boltz,%Vbur_atom_H1_radius_3.0_min,%Vbur_atom_H1_radius_3.0_lowE,%Vbur_atom_H1_radius_3.0_boltz,%Vbur_atom_H1_radius_4.0_max,%Vbur_atom_H1_radius_5.0_min,%Vbur_atom_H1_radius_5.0_max,%Vbur_atom_H2_radius_2.0_min,%Vbur_atom_H2_radius_2.0_max,%Vbur_atom_H2_radius_2.0_boltz,%Vbur_atom_H2_radius_2.5_min,%Vbur_atom_H2_radius_2.5_max,%Vbur_atom_H2_radius_2.5_lowE,%Vbur_atom_H2_radius_2.5_boltz,%Vbur_atom_H2_radius_4.0_max,%Vbur_atom_H2_radius_5.0_min,%Vbur_atom_H2_radius_5.0_max,%Vbur_atom_H2_radius_5.0_lowE,%Vbur_atom_H2_radius_5.0_boltz,%Vbur_atom_N1_radius_3.0_min,%Vbur_atom_N1_radius_3.0_max,%Vbur_atom_N1_radius_3.0_boltz,%Vbur_atom_N1_radius_3.5_lowE,%Vbur_atom_N1_radius_4.0_min,%Vbur_atom_N1_radius_4.0_max,%Vbur_atom_N1_radius_4.0_lowE,%Vbur_atom_N1_radius_4.0_boltz,%Vbur_atom_N1_radius_4.5_min,%Vbur_atom_N1_radius_4.5_max,%Vbur_atom_N1_radius_4.5_lowE,%Vbur_atom_N1_radius_4.5_boltz,%Vbur_atom_N1_radius_5.0_min,%Vbur_atom_N1_radius_5.0_max,%Vbur_atom_N1_radius_5.0_lowE,%Vbur_atom_N1_radius_5.0_boltz,%Vbur_atom_N2_radius_2.5_min,%Vbur_atom_N2_radius_3.0_boltz,%Vbur_atom_N2_radius_4.0_max,%Vbur_atom_N2_radius_4.5_boltz,%Vbur_atom_Ni_radius_2.0_max,%Vbur_atom_Ni_radius_2.5_min,%Vbur_atom_Ni_radius_2.5_boltz,%Vbur_atom_Ni_radius_4.0_min,%Vbur_atom_Ni_radius_5.0_min,%Vbur_atom_Ni_radius_5.0_lowE,%Vbur_atom_Ni_radius_5.0_boltz,Angle_Ni_N2_C2_min,Dihed_C1_C2_N2_Ni_min,Dihed_C1_C2_N2_Ni_max,Dihed_C1_C2_N2_Ni_lowE,Dihed_C1_C2_N2_Ni_boltz,Dihed_C2_C1_N1_Ni_min,Dihed_C2_C1_N1_Ni_max,Dihed_C2_C1_N1_Ni_lowE,Dihed_C2_C1_N1_Ni_boltz,Dihed_N1_C1_C2_N2_min,Dihed_N1_C1_C2_N2_max,Dihed_N1_C1_C2_N2_boltz,Pyr_angle_C1_max,Pyr_angle_C1_boltz,Pyr_angle_C2_min,Pyr_angle_C2_max,Pyr_angle_C2_lowE,Pyr_angle_C2_boltz,Pyr_angle_N1_min,Pyr_angle_N2_min,Pyr_angle_N2_max,Pyr_angle_N2_lowE,Pyr_angle_N2_boltz,SASA_C1_min,SASA_C1_max,SASA_C1_lowE,SASA_C1_boltz,SASA_C2_min,SASA_C2_max,SASA_C2_boltz,SASA_H1_min,SASA_H2_min,SASA_H2_lowE,SASA_H2_boltz,SASA_N1_min,SASA_N1_max,SASA_N1_lowE,SASA_N1_boltz,SASA_N2_min,SASA_N2_max,SASA_N2_boltz,SASA_Ni_min,SASA_Ni_max,SASA_Ni_lowE,SASA_Ni_boltz,Sterimol_C1_C2_Bmax_max,Sterimol_C1_C2_Bmax_boltz,Sterimol_C1_C2_Bmin_min,Sterimol_C1_C2_L_min,Sterimol_C1_N1_Bmax_max,Sterimol_C1_N1_Bmax_lowE,Sterimol_C1_N1_Bmin_max,Sterimol_C1_N1_L_min,Sterimol_C1_N1_L_max,Sterimol_C2_C1_Bmax_min,Sterimol_C2_C1_Bmax_lowE,Sterimol_C2_C1_Bmin_max,Sterimol_C2_C1_Bmin_boltz,Sterimol_C2_N2_L_max,Sterimol_N1_C1_Bmax_min,Sterimol_N1_C1_L_boltz,Sterimol_N2_C2_Bmin_boltz,Sterimol_N2_C2_L_min,Sterimol_N2_C2_L_boltz,Sterimol_Ni_H1_Bmax_min,Sterimol_Ni_H1_Bmax_max,Sterimol_Ni_H1_Bmax_lowE,Sterimol_Ni_H1_Bmax_boltz,Sterimol_Ni_H1_Bmin_min,Sterimol_Ni_H1_Bmin_max,Sterimol_Ni_H1_Bmin_lowE,Sterimol_Ni_H1_Bmin_boltz,Sterimol_Ni_H1_L_min,Sterimol_Ni_H1_L_max,Sterimol_Ni_H1_L_lowE,Sterimol_Ni_H1_L_boltz,Sterimol_Ni_H2_Bmax_min,Sterimol_Ni_H2_Bmax_max,Sterimol_Ni_H2_Bmax_lowE,Sterimol_Ni_H2_Bmax_boltz,Sterimol_Ni_H2_Bmin_min,Sterimol_Ni_H2_Bmin_max,Sterimol_Ni_H2_Bmin_boltz,Sterimol_Ni_H2_L_min,Sterimol_Ni_H2_L_max,Sterimol_Ni_H2_L_lowE,Sterimol_Ni_H2_L_boltz,Sterimol_Ni_N1_Bmax_min,Sterimol_Ni_N1_Bmax_boltz,Sterimol_Ni_N1_Bmin_min,Sterimol_Ni_N1_Bmin_lowE,Sterimol_Ni_N1_Bmin_boltz,Sterimol_Ni_N1_L_min,Sterimol_Ni_N1_L_boltz,Sterimol_Ni_N2_Bmax_min,Sterimol_Ni_N2_Bmax_lowE,Sterimol_Ni_N2_L_min,mulliken_H1_min,mulliken_H1_max,mulliken_H1_lowE,mulliken_H1_boltz,mulliken_H2_min,mulliken_H2_max,mulliken_H2_lowE,mulliken_H2_boltz,mulliken_C1_boltz,mulliken_C2_boltz,mulliken_N1_boltz,mulliken_N2_min,mulliken_N2_max,mulliken_N2_boltz,mulliken_Ni_min,mulliken_Ni_max,mulliken_Ni_lowE,mulliken_Ni_boltz,loewdin_H1_min,loewdin_H1_max,loewdin_H2_min,loewdin_H2_max,loewdin_H2_boltz,loewdin_C1_boltz,loewdin_C2_boltz,loewdin_N1_boltz,loewdin_N2_max,loewdin_N2_boltz,loewdin_Ni_min,loewdin_Ni_max,loewdin_Ni_boltz,chelpG_H1_min,chelpG_H1_max,chelpG_H1_boltz,chelpG_H2_min,chelpG_H2_max,chelpG_H2_lowE,chelpG_H2_boltz,chelpG_C1_min,chelpG_C1_max,chelpG_C1_boltz,chelpG_C2_min,chelpG_C2_max,chelpG_C2_boltz,chelpG_N1_min,chelpG_N1_max,chelpG_N1_boltz,chelpG_N2_min,chelpG_N2_max,chelpG_N2_lowE,chelpG_N2_boltz,chelpG_Ni_min,chelpG_Ni_max,chelpG_Ni_boltz,cm5_H1_max,cm5_H1_lowE,cm5_H1_boltz,cm5_H2_max,cm5_C1_boltz,cm5_C2_max,cm5_N1_boltz,cm5_N2_min,cm5_N2_max,cm5_N2_boltz,cm5_Ni_boltz,LUMO_energy_boltz,siso_H1_min,siso_H1_max,siso_H1_lowE,siso_H1_boltz,siso_H2_min,siso_H2_max,siso_H2_lowE,siso_H2_boltz,siso_C1_min,siso_C1_boltz,siso_C2_min,siso_C2_max,siso_C2_boltz,siso_N1_boltz,siso_N2_min,siso_N2_max,siso_N2_boltz,siso_Ni_boltz,Vertical_Ionization_Potential_boltz,Hardness_boltz,fplus_nbo_charge_H1_lowE,fminus_nbo_charge_H1_min,fminus_nbo_charge_H1_max,fminus_nbo_charge_H1_boltz,fplus_nbo_charge_H2_max,fplus_nbo_charge_H2_boltz,fminus_nbo_charge_H2_lowE,fzero_nbo_charge_H2_min,fplus_nbo_charge_C1_boltz,fminus_nbo_charge_C1_boltz,fplus_nbo_charge_C2_boltz,fminus_nbo_charge_C2_min,fminus_nbo_charge_C2_max,fminus_nbo_charge_C2_boltz,fzero_nbo_charge_C2_min,fzero_nbo_charge_C2_max,fminus_nbo_charge_N1_min,fminus_nbo_charge_N1_max,fminus_nbo_charge_N1_lowE,fzero_nbo_charge_N1_min,fplus_nbo_charge_N2_min,fplus_nbo_charge_N2_max,fplus_nbo_charge_N2_lowE,fminus_nbo_charge_N2_min,fminus_nbo_charge_N2_max,fminus_nbo_charge_N2_boltz,fzero_nbo_charge_N2_min,fzero_nbo_charge_N2_max,fzero_nbo_charge_N2_boltz,fplus_nbo_charge_Ni_boltz,fminus_nbo_charge_Ni_min,fminus_nbo_charge_Ni_boltz,fzero_nbo_charge_Ni_min,fplus_cm5_H1_min,fplus_cm5_H1_max,fplus_cm5_H1_boltz,fminus_cm5_H1_min,fminus_cm5_H1_max,fminus_cm5_H1_lowE,fminus_cm5_H1_boltz,fzero_cm5_H1_min,fzero_cm5_H1_boltz,fplus_cm5_H2_min,fminus_cm5_H2_min,fminus_cm5_H2_max,fminus_cm5_H2_lowE,fminus_cm5_H2_boltz,fzero_cm5_H2_lowE,fzero_cm5_H2_boltz,fplus_cm5_C2_boltz,fminus_cm5_C2_min,fminus_cm5_C2_boltz,fzero_cm5_C2_boltz,fplus_cm5_N1_lowE,fminus_cm5_N1_boltz,fplus_cm5_N2_min,fplus_cm5_N2_max,fplus_cm5_N2_boltz,fminus_cm5_N2_min,fminus_cm5_N2_max,fminus_cm5_N2_lowE,fplus_cm5_Ni_min,fplus_cm5_Ni_max,fplus_cm5_Ni_lowE,fminus_cm5_Ni_min,fminus_cm5_Ni_max,fminus_cm5_Ni_lowE,fminus_cm5_Ni_boltz,fzero_cm5_Ni_min,fzero_cm5_Ni_max,fzero_cm5_Ni_lowE,fzero_cm5_Ni_boltz,npa_H1_charge_max,npa_H2_charge_max,npa_C2_charge_min,npa_C2_charge_boltz,npa_N1_charge_boltz,npa_N2_charge_max,npa_Ni_charge_min,npa_Ni_rydberg_max,npa_totals_total_boltz,nao_H1_Val-1s_occupancy_lowE,nao_Ni_Val-4s_occupancy_min,nao_Ni_Val-4s_occupancy_max,nao_Ni_Val-4s_occupancy_lowE,nao_Ni_Val-4s_occupancy_boltz,nao_Ni_Ryd-5s_occupancy_min,nao_Ni_Ryd-5s_occupancy_max,nao_Ni_Ryd-5s_occupancy_lowE,nao_Ni_Ryd-4p_occupancy_min,nao_Ni_Ryd-4p_occupancy_max,nao_Ni_Ryd-4p_occupancy_lowE,nao_Ni_Ryd-4p_occupancy_boltz,nao_Ni_Ryd-4p_2_occupancy_lowE,nao_Ni_Ryd-4p_2_occupancy_boltz,nao_Ni_Ryd-4p_3_occupancy_min,nao_Ni_Ryd-4p_3_occupancy_lowE,nao_Ni_Val-3d_occupancy_min,nao_Ni_Val-3d_occupancy_max,nao_Ni_Val-3d_occupancy_lowE,nao_Ni_Val-3d_occupancy_boltz,nao_Ni_Ryd-5d_occupancy_min,nao_Ni_Ryd-5d_occupancy_max,nao_Ni_Val-3d_2_occupancy_min,nao_Ni_Val-3d_2_occupancy_max,nao_Ni_Ryd-5d_2_occupancy_min,nao_Ni_Ryd-5d_2_occupancy_lowE,nao_Ni_Ryd-5d_2_occupancy_boltz,nao_Ni_Val-3d_3_occupancy_min,nao_Ni_Val-3d_3_occupancy_max,nao_Ni_Val-3d_3_occupancy_lowE,nao_Ni_Val-3d_3_occupancy_boltz,nao_Ni_Ryd-5d_3_occupancy_min,nao_Ni_Ryd-5d_3_occupancy_max,nao_Ni_Ryd-5d_3_occupancy_lowE,nao_Ni_Ryd-5d_3_occupancy_boltz,nao_Ni_Val-3d_4_occupancy_min,nao_Ni_Val-3d_4_occupancy_max,nao_Ni_Val-3d_4_occupancy_lowE,nao_Ni_Val-3d_4_occupancy_boltz,nao_Ni_Ryd-5d_4_occupancy_min,nao_Ni_Ryd-5d_4_occupancy_max,nao_Ni_Ryd-5d_4_occupancy_boltz,nao_Ni_Val-3d_5_occupancy_min,nao_Ni_Val-3d_5_occupancy_max,nao_Ni_Val-3d_5_occupancy_lowE,nao_Ni_Val-3d_5_occupancy_boltz,nao_Ni_Ryd-5d_5_occupancy_min,nao_Ni_Ryd-5d_5_occupancy_max,nao_Ni_Ryd-5d_5_occupancy_lowE,nao_Ni_Ryd-5d_5_occupancy_boltz,nao_H2_Val-1s_occupancy_lowE,nao_N2_Val-2p_occupancy_min,nao_N2_Val-2p_occupancy_lowE,nao_N2_Val-2p_occupancy_boltz,nao_N2_Val-2p_2_occupancy_min,nao_N2_Val-2p_2_occupancy_lowE,nao_N2_Val-2p_2_occupancy_boltz,nao_N2_Val-2p_3_occupancy_min,nao_N2_Val-2p_3_occupancy_lowE,nao_N2_Val-2p_3_occupancy_boltz,nao_C2_Val-2p_occupancy_min,nao_C2_Val-2p_2_occupancy_min,nao_C1_Val-2p_occupancy_lowE,nao_C1_Val-2p_occupancy_boltz,nao_C1_Val-2p_2_occupancy_min,nao_C1_Val-2p_2_occupancy_lowE,nao_C1_Val-2p_2_occupancy_boltz,nao_C1_Val-2p_3_occupancy_min,nao_C1_Val-2p_3_occupancy_boltz,nao_N1_Val-2p_occupancy_min,nao_N1_Val-2p_occupancy_max,nao_N1_Val-2p_occupancy_boltz,nao_N1_Val-2p_2_occupancy_min,nao_N1_Val-2p_2_occupancy_max,nao_N1_Val-2p_2_occupancy_lowE,nao_N1_Val-2p_2_occupancy_boltz,nao_N1_Val-2p_3_occupancy_min,nao_N1_Val-2p_3_occupancy_max,nao_N1_Val-2p_3_occupancy_lowE,nao_N1_Val-2p_3_occupancy_boltz,nbo_lp4_H1_energy_min,nbo_lp4_H1_energy_boltz,nbo_lp5_H1_energy_min,nbo_lp5_H1_energy_boltz,bond_orbital_details_lp3_H1_occupancy_lowE,bond_orbital_details_lp3_H1_occupancy_boltz,bond_orbital_details_lp5_H1_bond_index_min,bond_orbital_details_lp5_H1_bond_index_boltz,nho_directionality_hm_C2_C1_deviation_min,nho_directionality_hm_C2_C1_deviation_max,nho_directionality_hm_C2_C1_deviation_lowE,nho_directionality_hm_C2_C1_deviation_boltz,charge_NBO_H1_min,charge_NBO_H1_max,charge_NBO_H1_boltz,charge_NBO_H2_min,charge_NBO_H2_max,charge_NBO_H2_boltz,charge_NBO_C1_min,charge_NBO_C2_max,charge_NBO_Ni_max,charge_NBO_Ni_boltz,B5_C1-N1_min,L_C1-N1_min,L_C1-N1_boltz,loc_B5_C1-N1_min,loc_B5_C1-N1_lowE,loc_B5_C1-N1_boltz,B1-B5_angle_C1-N1_max,B1-B5_angle_C1-N1_lowE,B1-B5_angle_C1-N1_boltz,B1_N1-C1_boltz,B5_N1-C1_boltz,L_N1-C1_min,loc_B5_N1-C1_min,loc_B5_N1-C1_max,loc_B5_N1-C1_lowE,loc_B5_N1-C1_boltz,B1-B5_angle_N1-C1_min,B1-B5_angle_N1-C1_max,B1-B5_angle_N1-C1_lowE,B1-B5_angle_N1-C1_boltz,B5_C2-N2_min,B5_C2-N2_boltz,L_C2-N2_min,L_C2-N2_boltz,loc_B5_C2-N2_min,loc_B5_C2-N2_max,loc_B5_C2-N2_lowE,loc_B5_C2-N2_boltz,B1-B5_angle_C2-N2_min,B1-B5_angle_C2-N2_max,B1-B5_angle_C2-N2_lowE,B1-B5_angle_C2-N2_boltz,B1_N2-C2_min,B5_N2-C2_min,B5_N2-C2_lowE,B5_N2-C2_boltz,L_N2-C2_lowE,loc_B5_N2-C2_min,loc_B5_N2-C2_max,loc_B5_N2-C2_lowE,loc_B5_N2-C2_boltz,B1-B5_angle_N2-C2_min,B1-B5_angle_N2-C2_max,B1-B5_angle_N2-C2_lowE,B1-B5_angle_N2-C2_boltz,B1_Ni-N1_max,L_Ni-N1_max,loc_B5_Ni-N1_min,loc_B5_Ni-N1_max,loc_B5_Ni-N1_lowE,loc_B5_Ni-N1_boltz,B1-B5_angle_Ni-N1_min,B1-B5_angle_Ni-N1_max,B1-B5_angle_Ni-N1_lowE,B1-B5_angle_Ni-N1_boltz,B1_Ni-N2_min,B1_Ni-N2_max,B1_Ni-N2_lowE,B1_Ni-N2_boltz,L_Ni-N2_boltz,loc_B5_Ni-N2_min,loc_B5_Ni-N2_max,loc_B5_Ni-N2_lowE,loc_B5_Ni-N2_boltz,B1-B5_angle_Ni-N2_min,B1-B5_angle_Ni-N2_max,B1-B5_angle_Ni-N2_lowE,B1-B5_angle_Ni-N2_boltz,B1_C1-C2_min,B1_C1-C2_boltz,B5_C1-C2_min,B5_C1-C2_max,B5_C1-C2_lowE,B5_C1-C2_boltz,L_C1-C2_max,L_C1-C2_lowE,L_C1-C2_boltz,loc_B5_C1-C2_min,loc_B5_C1-C2_max,loc_B5_C1-C2_lowE,loc_B5_C1-C2_boltz,B1-B5_angle_C1-C2_min,B1-B5_angle_C1-C2_max,B1-B5_angle_C1-C2_boltz,B1_C2-C1_min,B1_C2-C1_max,B1_C2-C1_lowE,B1_C2-C1_boltz,B5_C2-C1_min,B5_C2-C1_lowE,B5_C2-C1_boltz,L_C2-C1_min,L_C2-C1_max,L_C2-C1_lowE,L_C2-C1_boltz,loc_B5_C2-C1_min,loc_B5_C2-C1_max,loc_B5_C2-C1_boltz,B1-B5_angle_C2-C1_min,B1-B5_angle_C2-C1_max,B1-B5_angle_C2-C1_lowE,B1-B5_angle_C2-C1_boltz,dist_Ni-N2_max,vib_freq_C1-C2_boltz,charge_NBO_diff_C1-N1_min,charge_NBO_diff_C1-N1_boltz,charge_NBO_diff_C2-N2_boltz,charge_NBO_diff_N2-C2_min,charge_NBO_diff_Ni-N1_min,charge_NBO_diff_Ni-N1_boltz,charge_NBO_diff_Ni-N2_boltz,charge_NBO_diff_Ni-H1_max,charge_NBO_diff_Ni-H1_lowE,charge_NBO_diff_Ni-H1_boltz,charge_NBO_diff_Ni-H2_max,charge_NBO_diff_Ni-H2_lowE,charge_NBO_diff_Ni-H2_boltz,charge_NBO_diff_C2-C1_min,dipole_min,dipole_max,dipole_boltz,dipole_x_Ni-N2-N1_max,dipole_x_Ni-N2-N1_boltz,dipole_y_Ni-N2-N1_max,dipole_y_Ni-N2-N1_boltz,dipole_z_Ni-N2-N1_min,dipole_z_Ni-N2-N1_max,dipole_z_Ni-N2-N1_lowE,dipole_z_Ni-N2-N1_boltz,angle_H2-Ni-H1_min,angle_H2-Ni-H1_boltz,smiles,inchi,inchi_folder,ligand_class
0,78.501323,51.881078,44.836768,44.838225,89.337804,72.489401,72.452712,72.470798,46.730363,66.741994,67.775052,67.775052,67.265792,56.713114,59.687134,59.687134,58.221052,48.125559,52.766500,50.478688,39.445875,28.560279,31.603584,66.738765,67.684659,67.205056,56.696836,59.600859,56.696836,58.128412,39.389237,28.593587,31.573626,28.593587,30.062636,79.518027,79.545962,79.532192,69.259574,59.938474,59.940801,59.940801,59.939654,51.492217,51.504157,51.504157,51.498271,44.024353,44.036770,44.036770,44.030649,94.094283,87.837568,69.615092,58.429855,80.765754,71.752507,71.776580,46.545062,37.038409,37.042745,37.040608,111.511017,-8.806631,-8.337114,-8.337114,-8.568569,5.233326,5.309198,5.233326,5.270728,2.176753,2.442327,2.307671,0.043648,0.042077,0.035488,0.040200,0.040200,0.037877,0.411051,0.356976,0.414541,0.356976,0.385354,4.520106,4.570107,4.520106,4.544754,3.280077,3.310077,3.295288,15.059965,15.049965,17.809958,16.449384,1.029989,1.039989,1.029989,1.034919,0.419996,0.459995,0.440277,27.269047,27.319046,27.319046,27.294398,5.105040,5.104507,2.404816,7.683345,7.610572,7.608133,2.399536,5.203553,5.207690,5.103987,5.103987,2.487313,2.445394,5.818501,7.608134,5.591673,2.327463,6.482405,6.483835,6.906364,7.747757,6.906364,7.321139,2.625600,2.841390,2.841390,2.735013,4.154402,4.538047,4.154402,4.343525,6.907598,7.654419,7.654419,7.286264,2.599611,2.811533,2.704080,4.136650,4.568089,4.568089,4.355405,6.847980,6.848684,2.562795,2.562795,2.595975,7.763888,7.826532,7.658705,7.658705,6.934493,-0.090359,-0.085815,-0.085815,-0.088055,-0.090836,-0.086835,-0.090836,-0.088863,0.121662,0.255924,0.000237,-0.065609,-0.065297,-0.065455,-0.333546,-0.333054,-0.333546,-0.333304,-0.071696,-0.066606,-0.071602,-0.066873,-0.069271,-0.148475,-0.327710,0.260634,0.230093,0.230051,-0.290196,-0.289988,-0.290093,-0.143063,-0.134126,-0.138531,-0.140963,-0.135282,-0.140963,-0.138163,0.006916,0.009898,0.008428,0.357970,0.362994,0.360447,0.163659,0.169627,0.166685,0.023837,0.031071,0.031071,0.027505,-0.366206,-0.358621,-0.362467,-0.127497,-0.127497,-0.130462,-0.127698,0.076585,0.165087,-0.069010,-0.109512,-0.109494,-0.109503,-0.149348,-2.672690,38.205809,41.884781,41.884781,40.071184,38.175686,41.899526,38.175686,40.011401,37.671960,37.679055,16.883951,16.894585,16.889193,-34.363011,22.033388,22.162409,22.098806,-4418.240157,-0.218077,-0.085599,0.06947,0.10275,0.12167,0.112343,0.06947,0.058386,0.10278,0.075195,0.115195,0.010532,0.035305,0.04723,0.04736,0.047294,0.041255,0.041345,-0.08540,-0.08527,-0.08540,0.001450,0.09995,0.10003,0.09995,-0.09551,-0.09538,-0.095444,0.002260,0.002285,0.002273,0.021526,0.57310,0.573223,0.297335,0.036268,0.044842,0.040615,0.094551,0.099668,0.099668,0.097145,0.065409,0.068880,0.036235,0.094557,0.099728,0.094557,0.097106,0.065396,0.068794,0.046218,0.022296,0.022316,0.034267,0.051226,-0.013087,0.050103,0.050114,0.050108,-0.016739,-0.016724,-0.016724,0.078744,0.078748,0.078744,0.419175,0.419401,0.419175,0.419287,0.248960,0.249074,0.248960,0.249016,-0.21900,-0.21869,0.50655,0.506580,-0.425930,-0.48794,0.39219,0.02274,172.0,1.21609,0.49920,0.49939,0.49920,0.499294,0.00391,0.00392,0.00391,0.00378,0.00380,0.00378,0.003790,0.00341,0.003390,0.00203,0.00203,1.37715,1.39810,1.39810,1.387772,0.00215,0.00221,1.92731,1.93000,0.00085,0.00085,0.000855,1.88614,1.88822,1.88614,1.887165,0.00077,0.00079,0.00079,0.000780,1.92757,1.95085,1.92757,1.939046,0.00111,0.00117,0.001140,1.94243,1.94402,1.94402,1.943236,0.00084,0.00084,0.00084,0.000840,1.22696,1.19478,1.19478,1.198354,1.54215,1.54943,1.545841,1.32253,1.32253,1.322540,0.96213,0.78424,1.03525,1.033638,0.96191,0.96191,0.963675,0.98057,0.980737,1.40266,1.41673,1.409794,1.38739,1.40193,1.38739,1.394558,1.24056,1.24098,1.24098,1.240773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.2,3.2,3.2,3.200000,-0.22978,-0.21900,-0.224314,-0.22972,-0.21869,-0.224283,0.11260,0.50661,0.39248,0.392337,5.9128,4.6836,4.685679,1.6048,1.6651,1.635374,167.7575,166.7043,167.223489,2.275182,7.509383,5.0910,2.5520,2.5548,2.5548,2.553420,110.3368,111.3421,111.3421,110.846524,5.1671,5.170092,5.3125,5.315542,3.3063,3.3166,3.3063,3.311378,149.6545,149.6667,149.6667,149.660686,2.2147,7.4217,7.4217,7.421996,5.9852,2.6566,2.6666,2.6666,2.661670,91.4006,93.5408,91.4006,92.455639,2.5289,7.3710,-1.2605,-1.2523,-1.2523,-1.256342,100.9590,101.9257,101.9257,101.449153,2.4112,2.4265,2.4112,2.418742,6.436225,-1.2495,-1.1587,-1.2495,-1.204739,128.9439,129.4435,129.4435,129.197216,2.0342,2.034792,5.0039,5.0049,5.0039,5.004393,7.1077,7.1077,7.105876,4.4134,4.4236,4.4236,4.418572,113.1321,113.1657,113.148664,2.1989,2.2539,2.1989,2.226013,3.4141,3.4141,3.414790,7.5386,7.5701,7.5701,7.554572,3.6444,3.6457,3.645059,69.2049,119.2218,69.2049,93.861378,1.957104,1412.029156,0.53853,0.538540,0.994555,-0.99456,0.81812,0.818267,0.880312,0.62197,0.61148,0.616651,0.62220,0.62220,0.616620,0.39393,2.828415,2.832789,2.830571,0.503899,0.503531,2.761978,2.759818,0.375512,0.378164,0.375512,0.376819,81.055124,81.067184,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,AATATIAROAAKIN-SNVBAGLBSA-N,DATA/LNiH2_library_001_to_download_2026_03_24/...,pyox

In [ ]:
# save to csv
from datetime import datetime
output_csv_path = datetime.now().strftime("%Y%m%d") + "_" + src_dir.split('/')[-1] + "_descriptors" + ".csv"
df_num_desc_filtered.to_csv(output_csv_path, index=False)