### Import libaries

In [1]:
import os
import sys
import subprocess
import importlib
sys.path.append('DescriPyTor')

import pandas as pd
import numpy as np
from tqdm import tqdm

from datetime import datetime
from pathlib import Path

from desc_utils import atom_numbering as an
from desc_utils import orca_descriptors as od

ROOT_DIR = os.getcwd()

### Define the source directory containing the orca and xyz files

Provide path to directory or directory of directories containing xyz files path can be 

1. absolute, e.g. "/home/aconner/orca_descriptors/library_pyox_2026_03_03/",

2. relative, e.g. "library_pyox_2026_03_03" (joined to current working directory).

In [2]:
src_dir = "DATA/LNiH2_library_001_to_download_2026_03_24"  # change this as needed

### Define the atoms to be included in the descriptor.

In [3]:
#Define lists for decriptor retrieval 

# 1 -atom descriptors (e.g. Sterimol L, atomic charge)
atoms = ["H1", "H2", "C1", "C2", "N1", "N2", "Ni"]

# 2-atom descriptors (e.g. Sterimol B1, bond length), if order matters for 2-atom descriptors (e.g. Sterimol B1), atoms must be listed in desired order
bonds = [("C1", "N1"), ("N1", "C1"), ("C2", "N2"), ("N2", "C2"), ("Ni", "N1"), ("Ni", "N2"), ("Ni", "H1"), ("Ni", "H2"), ("C1", "C2"), ("C2", "C1")]
pairs_bending = [("H1", "H2"), ("N1", "C2"), ("N2", "C1")] # list of bonds to consider for bend vibration descriptors, if order matters for bend vibration descriptors, atoms must be listed in desired order

# 3-atom descriptors (e.g. Sterimol B5, bond angle), if order matters for 3-atom descriptors (e.g. Sterimol B5), atoms must be listed in desired order
angles = [("H2", "Ni", "H1"), ("Ni", "N1", "C1"), ("Ni", "N2", "C2"), ("N1", "C1", "C2"), ("N2", "C2", "C1"), ("N1", "Ni", "N2"), ("C1", "Ni", "C2")]

# 4-atom descriptors (e.g. dihedral angle), if order matters for 4-atom descriptors (e.g. dihedral angle), atoms must be listed in desired order
dihedrals = [("N1", "C1", "C2", "N2"), ("C1", "C2", "N2", "Ni"), ("C2", "C1", "N1", "Ni")]

# If you want to include quadrant-based descriptors, define the quadrants here. Each quadrant is a list of atom labels. For example, if you want to define one quadrant that includes atoms C1, N1, C2, N2, and Ni, you would define:
#quadrants = [[2, 1, 3, 4, 6]]

# Atom Numbering

In [4]:
# example for the numbering of the atoms for one molecule:

df = an.compile_final('DATA/LNiH2_library_001_to_download_2026_03_24/AATATIAROAAKIN-SNVBAGLBSA-N/', subdirectory=True)

In [5]:
# Get numbering for all molecules

# Set your ORCA root folder here (contains many conf_* subfolders)
orca_folder = Path(src_dir)

print(f"Current working directory before processing: {os.getcwd()}")

df_num = pd.DataFrame()
for inchi_folder in os.listdir(orca_folder):
    if os.path.isdir(os.path.join(orca_folder, inchi_folder)):
        inchi_folder_path = os.path.join(orca_folder, inchi_folder)
        print(f"Processing {inchi_folder_path} for atom numbering...")
        df = an.compile_final(inchi_folder_path, subdirectory=True)
        df_num = pd.concat([df_num, df], ignore_index=True)

df_num.head()

# add the feather file paths to the df_num dataframe

df_num['feather_path'] = df_num['path'].apply(lambda x: x + x.split('/')[-2] + '.feather')

df_num.head()

Current working directory before processing: /Users/julesschleinitz/Desktop/Code/orca_descriptors
Processing DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/DSZOIEZWGDCKLK-KGLIPLIRSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/DSZOIEZWGDCKLK-KGLIPLIRSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/ZECIAWBAXVMXKI-CQSZACIVSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/ZECIAWBAXVMXKI-CQSZACIVSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/UITFYNBEZIIWCV-LURJTMIESA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/UITFYNBEZIIWCV-LURJTMIESA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/YVULGYITAFNKKF-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/YVULGYITAFNKKF-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/JFOQGDQQMCKEKY-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/JFOQGDQQMCKEKY-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/JPCAXHBKQLBOJG-KGLIPLIRSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/JPCAXHBKQLBOJG-KGLIPLIRSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/NHWBZSGKOQHPDW-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/NHWBZSGKOQHPDW-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/AATATIAROAAKIN-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/AATATIAROAAKIN-SNVBAGLBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/UOIDAFBRAUSYGL-ZDUSSCGKSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/UOIDAFBRAUSYGL-ZDUSSCGKSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/XVXACZLZNPRNEF-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/XVXACZLZNPRNEF-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/CTDSXZLFAXPRHX-MRVPVSSYSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/CTDSXZLFAXPRHX-MRVPVSSYSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-RBUKOAKNSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-RBUKOAKNSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/RJKNIIOSLLEQAJ-LBPRGKRZSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/RJKNIIOSLLEQAJ-LBPRGKRZSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/YZOJKEJLMYATFV-CYBMUJFWSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/YZOJKEJLMYATFV-CYBMUJFWSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/ZZYZJBMNVRAFBQ-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/ZZYZJBMNVRAFBQ-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-OALUTQOASA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-OALUTQOASA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/LSCORSGHQVIJEW-QGZVFWFLSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/LSCORSGHQVIJEW-QGZVFWFLSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/WQPDKBFVGVJUHI-LLVKDONJSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/WQPDKBFVGVJUHI-LLVKDONJSA-N/
Processing DATA/LNiH2_library_001_to_download_2026_03_24/KGZUJYDTOJDLJK-SNVBAGLBSA-N for atom numbering...
added slash to end of path, new path is DATA/LNiH2_library_001_to_download_2026_03_24/KGZUJYDTOJDLJK-SNVBAGLBSA-N/

,xyz_name,path,ligand_type,inchi,SCF_energy,smiles,H1,Ni,H2,N1,C1,C2,N2,ligand_class,feather_path
0,conf_1,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425277,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...
1,optimization,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425277,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...
2,conf_2,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425257,[H]C1=C([H])C([H])=C(F)N[C]1[C]1N[C@@]2([H])c3...,1,2,3,12,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...
3,optimization,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425257,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...
4,conf_25,DATA/LNiH2_library_001_to_download_2026_03_24/...,core_5,DVLYVQBEMHJQAQ-SFHVURJKSA-N,-2811.494785,[H]C1=C(C(F)(F)F)C([H])=C([H])C(=C2N[C@@]([H])...,1,2,3,15,6,5,4,pyox,DATA/LNiH2_library_001_to_download_2026_03_24/...

# ORCA Descriptors

### Geometric Descriptors

In [6]:
from desc_utils.data_extraction import *
os.chdir(ROOT_DIR)

results_xyz_dict = get_xyz_descriptors(df_num, atoms, bonds, angles, dihedrals, quadrants=None, overwrite_json=False)
df_xyz_desc = pd.DataFrame.from_dict(results_xyz_dict, orient='index')
df_xyz_desc.set_index('path', inplace=True)
df_xyz_desc.head(5)

  0%|          | 0/606 [00:00<?, ?it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  0%|          | 1/606 [00:01<14:24,  1.43s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  0%|          | 3/606 [00:02<08:58,  1.12it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  1%|          | 5/606 [00:04<08:21,  1.20it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  1%|          | 7/606 [00:05<08:06,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_22/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  1%|▏         | 9/606 [00:07<08:04,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_14/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  2%|▏         | 11/606 [00:09<08:03,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_13/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  2%|▏         | 13/606 [00:10<07:53,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_47/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  2%|▏         | 15/606 [00:12<07:49,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_78/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  3%|▎         | 17/606 [00:13<07:43,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_40/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  3%|▎         | 19/606 [00:15<07:45,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_82/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  3%|▎         | 21/606 [00:17<07:40,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_76/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  4%|▍         | 23/606 [00:18<07:40,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_49/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  4%|▍         | 25/606 [00:20<07:39,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_71/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  4%|▍         | 27/606 [00:21<07:37,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_85/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  5%|▍         | 29/606 [00:23<07:37,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_12/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  5%|▌         | 31/606 [00:24<07:37,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_15/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  5%|▌         | 33/606 [00:26<07:33,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_23/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  6%|▌         | 35/606 [00:28<07:32,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_24/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  6%|▌         | 37/606 [00:29<07:46,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_84/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  6%|▋         | 39/606 [00:31<07:45,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_70/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  7%|▋         | 41/606 [00:33<07:46,  1.21it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_77/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  7%|▋         | 43/606 [00:34<07:49,  1.20it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_83/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  7%|▋         | 45/606 [00:36<07:45,  1.20it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_48/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  8%|▊         | 47/606 [00:38<07:42,  1.21it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_41/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  8%|▊         | 49/606 [00:39<07:39,  1.21it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_46/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  8%|▊         | 51/606 [00:41<07:34,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_79/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  9%|▊         | 53/606 [00:43<07:29,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_100/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  9%|▉         | 55/606 [00:44<07:26,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_90/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

  9%|▉         | 57/606 [00:46<07:26,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_64/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 10%|▉         | 59/606 [00:47<07:24,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_63/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 10%|█         | 61/606 [00:49<07:18,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_97/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 10%|█         | 63/606 [00:51<07:11,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_55/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 11%|█         | 65/606 [00:52<07:14,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_99/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 11%|█         | 67/606 [00:54<07:11,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_52/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 11%|█▏        | 69/606 [00:55<07:06,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_39/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 12%|█▏        | 71/606 [00:57<07:05,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_8/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 12%|█▏        | 73/606 [00:59<07:02,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_37/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 12%|█▏        | 75/606 [01:00<07:03,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 13%|█▎        | 77/606 [01:02<06:58,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_30/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 13%|█▎        | 79/606 [01:03<06:58,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 13%|█▎        | 81/606 [01:05<06:54,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_98/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 14%|█▎        | 83/606 [01:06<06:51,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_53/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 14%|█▍        | 85/606 [01:08<06:52,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_54/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 14%|█▍        | 87/606 [01:10<06:54,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_96/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 15%|█▍        | 89/606 [01:11<06:50,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_62/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 15%|█▌        | 91/606 [01:13<06:50,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_65/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 15%|█▌        | 93/606 [01:14<06:45,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_91/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 16%|█▌        | 95/606 [01:16<06:41,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_31/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 16%|█▌        | 97/606 [01:18<06:41,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 16%|█▋        | 99/606 [01:19<06:37,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_36/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 17%|█▋        | 101/606 [01:21<06:39,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_9/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 17%|█▋        | 103/606 [01:22<06:50,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_38/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 17%|█▋        | 105/606 [01:24<06:59,  1.19it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_43/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 18%|█▊        | 107/606 [01:26<06:56,  1.20it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_88/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 18%|█▊        | 109/606 [01:27<06:49,  1.21it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_44/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 18%|█▊        | 111/606 [01:29<06:48,  1.21it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_72/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 19%|█▊        | 113/606 [01:31<06:44,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_86/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 19%|█▉        | 115/606 [01:32<06:43,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_81/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 19%|█▉        | 117/606 [01:34<06:41,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_75/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 20%|█▉        | 119/606 [01:36<06:34,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_21/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 20%|█▉        | 121/606 [01:37<06:28,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_19/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 20%|██        | 123/606 [01:39<06:21,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_26/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 21%|██        | 125/606 [01:40<06:15,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_10/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 21%|██        | 127/606 [01:42<06:13,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_28/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 21%|██▏       | 129/606 [01:43<06:14,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_17/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 22%|██▏       | 131/606 [01:45<06:14,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_74/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 22%|██▏       | 133/606 [01:46<06:11,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_80/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 22%|██▏       | 135/606 [01:48<06:08,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_87/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 23%|██▎       | 137/606 [01:50<06:04,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_73/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 23%|██▎       | 139/606 [01:51<06:02,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_45/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 23%|██▎       | 141/606 [01:53<06:01,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_42/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 24%|██▎       | 143/606 [01:54<06:02,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_89/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 24%|██▍       | 145/606 [01:56<05:59,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_29/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 24%|██▍       | 147/606 [01:57<05:56,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_16/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 25%|██▍       | 149/606 [01:59<05:54,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_11/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 25%|██▍       | 151/606 [02:00<05:52,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_18/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 25%|██▌       | 153/606 [02:02<05:51,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_27/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 26%|██▌       | 155/606 [02:04<05:51,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_20/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 26%|██▌       | 157/606 [02:05<05:47,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_33/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 26%|██▌       | 159/606 [02:07<05:50,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 27%|██▋       | 161/606 [02:08<05:50,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_34/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 27%|██▋       | 163/606 [02:10<05:50,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 27%|██▋       | 165/606 [02:11<05:46,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_60/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 28%|██▊       | 167/606 [02:13<05:44,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_94/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 28%|██▊       | 169/606 [02:15<05:44,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_58/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 28%|██▊       | 171/606 [02:16<05:48,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_93/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 29%|██▊       | 173/606 [02:18<05:49,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_67/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 29%|██▉       | 175/606 [02:20<05:49,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_51/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 29%|██▉       | 177/606 [02:21<05:52,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_69/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 30%|██▉       | 179/606 [02:23<05:48,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_56/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 30%|██▉       | 181/606 [02:25<05:47,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_35/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 30%|███       | 183/606 [02:26<05:45,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 31%|███       | 185/606 [02:28<05:43,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_32/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 31%|███       | 187/606 [02:29<05:39,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 31%|███       | 189/606 [02:31<05:35,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_68/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 32%|███▏      | 191/606 [02:33<05:32,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_57/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 32%|███▏      | 193/606 [02:34<05:30,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_50/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 32%|███▏      | 195/606 [02:36<05:28,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_59/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 33%|███▎      | 197/606 [02:37<05:26,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_66/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 33%|███▎      | 199/606 [02:39<05:25,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_92/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 33%|███▎      | 201/606 [02:41<05:24,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_95/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 33%|███▎      | 203/606 [02:42<05:23,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_61/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 34%|███▍      | 205/606 [02:44<05:13,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 34%|███▍      | 207/606 [02:45<05:06,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 34%|███▍      | 209/606 [02:47<05:00,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 35%|███▍      | 211/606 [02:48<04:56,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ILENSZIBAAQNCZ-SNVBAGLBSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 35%|███▌      | 213/606 [02:50<04:54,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 35%|███▌      | 215/606 [02:51<04:52,  1.34it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 36%|███▌      | 217/606 [02:53<04:51,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 36%|███▌      | 219/606 [02:54<04:50,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 36%|███▋      | 221/606 [02:56<04:48,  1.34it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 37%|███▋      | 223/606 [02:57<04:48,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 37%|███▋      | 225/606 [02:59<04:45,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YOWGAJZEYGYTFY-SNVBAGLBSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 37%|███▋      | 227/606 [03:00<04:44,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 38%|███▊      | 229/606 [03:02<04:42,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 38%|███▊      | 231/606 [03:03<04:42,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 38%|███▊      | 233/606 [03:05<04:39,  1.34it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 39%|███▉      | 235/606 [03:06<04:36,  1.34it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 39%|███▉      | 237/606 [03:08<04:36,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 39%|███▉      | 239/606 [03:09<04:34,  1.34it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WXGMFBHACBRVEN-SNVBAGLBSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 40%|███▉      | 241/606 [03:11<04:35,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 40%|████      | 243/606 [03:12<04:35,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 40%|████      | 245/606 [03:14<04:32,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 41%|████      | 247/606 [03:15<04:29,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DERMNSMASFMDOJ-AWEZNQCLSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 41%|████      | 249/606 [03:17<04:31,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 41%|████▏     | 251/606 [03:18<04:32,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 42%|████▏     | 253/606 [03:20<04:33,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 42%|████▏     | 255/606 [03:21<04:31,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 42%|████▏     | 257/606 [03:23<04:31,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 43%|████▎     | 259/606 [03:24<04:30,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RYNVXYBNTRCDQQ-LLVKDONJSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 43%|████▎     | 261/606 [03:26<04:24,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DSZOIEZWGDCKLK-KGLIPLIRSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 43%|████▎     | 263/606 [03:27<04:21,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/DSZOIEZWGDCKLK-KGLIPLIRSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 44%|████▎     | 265/606 [03:29<04:24,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_8/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 44%|████▍     | 267/606 [03:31<04:27,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 44%|████▍     | 269/606 [03:32<04:27,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 45%|████▍     | 271/606 [03:34<04:27,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 45%|████▌     | 273/606 [03:35<04:25,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 45%|████▌     | 275/606 [03:37<04:26,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 46%|████▌     | 277/606 [03:39<04:26,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 46%|████▌     | 279/606 [03:40<04:23,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LJCASYBHMLZNFS-QFIPXVFZSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 46%|████▋     | 281/606 [03:42<04:19,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZECIAWBAXVMXKI-CQSZACIVSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 47%|████▋     | 283/606 [03:44<04:16,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZECIAWBAXVMXKI-CQSZACIVSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 47%|████▋     | 285/606 [03:45<04:11,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/UITFYNBEZIIWCV-LURJTMIESA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 47%|████▋     | 287/606 [03:47<04:05,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/UITFYNBEZIIWCV-LURJTMIESA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 48%|████▊     | 289/606 [03:48<04:02,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 48%|████▊     | 291/606 [03:50<04:01,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 48%|████▊     | 293/606 [03:51<04:00,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/SGJXJZCXVZDEEU-CABCVRRESA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 49%|████▊     | 295/606 [03:53<04:02,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_14/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 49%|████▉     | 297/606 [03:54<04:03,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_13/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 49%|████▉     | 299/606 [03:56<04:07,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_12/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 50%|████▉     | 301/606 [03:58<04:07,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_15/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 50%|█████     | 303/606 [03:59<04:05,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_8/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 50%|█████     | 305/606 [04:01<04:02,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 51%|█████     | 307/606 [04:02<03:58,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 51%|█████     | 309/606 [04:04<04:02,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 51%|█████▏    | 311/606 [04:06<04:09,  1.18it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_9/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 52%|█████▏    | 313/606 [04:08<04:04,  1.20it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_10/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 52%|█████▏    | 315/606 [04:09<03:59,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_17/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 52%|█████▏    | 317/606 [04:11<03:52,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_16/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 53%|█████▎    | 319/606 [04:12<03:48,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_11/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 53%|█████▎    | 321/606 [04:14<03:50,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 53%|█████▎    | 323/606 [04:15<03:45,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 54%|█████▎    | 325/606 [04:17<03:40,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 54%|█████▍    | 327/606 [04:19<03:36,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZDNYUSYASDJIOQ-QGZVFWFLSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 54%|█████▍    | 329/606 [04:20<03:33,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YVULGYITAFNKKF-SNVBAGLBSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 55%|█████▍    | 331/606 [04:22<03:33,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YVULGYITAFNKKF-SNVBAGLBSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 55%|█████▍    | 333/606 [04:23<03:29,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/JFOQGDQQMCKEKY-LLVKDONJSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 55%|█████▌    | 335/606 [04:25<03:26,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/JFOQGDQQMCKEKY-LLVKDONJSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 56%|█████▌    | 337/606 [04:26<03:22,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/JPCAXHBKQLBOJG-KGLIPLIRSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 56%|█████▌    | 339/606 [04:28<03:21,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NHWBZSGKOQHPDW-LLVKDONJSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 56%|█████▋    | 341/606 [04:29<03:20,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NHWBZSGKOQHPDW-LLVKDONJSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 57%|█████▋    | 343/606 [04:31<03:20,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 57%|█████▋    | 345/606 [04:32<03:17,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 57%|█████▋    | 347/606 [04:34<03:15,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 58%|█████▊    | 349/606 [04:35<03:14,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 58%|█████▊    | 351/606 [04:37<03:12,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 58%|█████▊    | 353/606 [04:38<03:11,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 59%|█████▊    | 355/606 [04:40<03:09,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/PQZZXVXAXGWXAX-NSHDSACASA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 59%|█████▉    | 357/606 [04:41<03:08,  1.32it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 59%|█████▉    | 358/606 [04:43<03:41,  1.12it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 59%|█████▉    | 360/606 [04:44<03:27,  1.19it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 60%|█████▉    | 362/606 [04:46<03:19,  1.22it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 60%|█████▉    | 363/606 [04:47<03:51,  1.05it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 60%|██████    | 364/606 [04:49<04:22,  1.08s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 60%|██████    | 366/606 [04:50<03:51,  1.04it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/HYOAIWRQTPVAAR-ZDUSSCGKSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 61%|██████    | 368/606 [04:52<03:32,  1.12it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_25/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 61%|██████    | 370/606 [04:54<03:24,  1.16it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 61%|██████    | 371/606 [04:55<03:52,  1.01it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_14/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 62%|██████▏   | 373/606 [04:57<03:32,  1.10it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_13/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 62%|██████▏   | 375/606 [04:58<03:18,  1.16it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_12/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 62%|██████▏   | 377/606 [05:00<03:08,  1.21it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_15/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 63%|██████▎   | 379/606 [05:01<03:02,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_23/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 63%|██████▎   | 381/606 [05:03<02:58,  1.26it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 63%|██████▎   | 382/606 [05:04<03:26,  1.09it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_8/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 63%|██████▎   | 384/606 [05:06<03:12,  1.15it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 64%|██████▎   | 386/606 [05:07<03:03,  1.20it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 64%|██████▍   | 388/606 [05:09<02:58,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 64%|██████▍   | 390/606 [05:10<02:54,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_21/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 65%|██████▍   | 392/606 [05:12<02:50,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_19/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 65%|██████▌   | 394/606 [05:13<02:46,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_26/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 65%|██████▌   | 396/606 [05:15<02:42,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_10/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 66%|██████▌   | 398/606 [05:17<02:42,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_17/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 66%|██████▌   | 400/606 [05:18<02:40,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_16/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 66%|██████▋   | 402/606 [05:20<02:39,  1.28it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 67%|██████▋   | 403/606 [05:21<03:06,  1.09it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 67%|██████▋   | 404/606 [05:23<03:31,  1.04s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_20/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 67%|██████▋   | 406/606 [05:24<03:09,  1.05it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 67%|██████▋   | 408/606 [05:26<02:56,  1.12it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 68%|██████▊   | 410/606 [05:27<02:46,  1.18it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 68%|██████▊   | 412/606 [05:29<02:40,  1.21it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/TXZUWWPJFPWJBJ-XMMPIXPASA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 68%|██████▊   | 414/606 [05:30<02:35,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/AATATIAROAAKIN-SNVBAGLBSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 69%|██████▊   | 416/606 [05:32<02:30,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/AATATIAROAAKIN-SNVBAGLBSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 69%|██████▉   | 418/606 [05:33<02:26,  1.29it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 69%|██████▉   | 419/606 [05:35<02:48,  1.11it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/UOIDAFBRAUSYGL-ZDUSSCGKSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 69%|██████▉   | 421/606 [05:36<02:38,  1.17it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/UOIDAFBRAUSYGL-ZDUSSCGKSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 70%|██████▉   | 423/606 [05:38<02:30,  1.21it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 70%|██████▉   | 424/606 [05:39<02:52,  1.06it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/UOIDAFBRAUSYGL-ZDUSSCGKSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 70%|███████   | 426/606 [05:41<02:39,  1.13it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 71%|███████   | 428/606 [05:43<02:30,  1.18it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 71%|███████   | 430/606 [05:44<02:24,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 71%|███████▏  | 432/606 [05:46<02:19,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 72%|███████▏  | 434/606 [05:47<02:15,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 72%|███████▏  | 436/606 [05:49<02:14,  1.27it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WDGJHIYZYORLQS-LLVKDONJSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 72%|███████▏  | 438/606 [05:50<02:10,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_14/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 73%|███████▎  | 440/606 [05:52<02:08,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_13/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 73%|███████▎  | 442/606 [05:53<02:06,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_12/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 73%|███████▎  | 444/606 [05:55<02:03,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_15/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 74%|███████▎  | 446/606 [05:56<02:02,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_8/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 74%|███████▍  | 448/606 [05:58<02:01,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 74%|███████▍  | 450/606 [05:59<01:59,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 75%|███████▍  | 452/606 [06:01<01:57,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 75%|███████▍  | 454/606 [06:02<01:56,  1.30it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_9/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 75%|███████▌  | 456/606 [06:04<01:55,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_10/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 76%|███████▌  | 458/606 [06:06<01:54,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_17/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 76%|███████▌  | 460/606 [06:07<01:53,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_16/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 76%|███████▌  | 462/606 [06:09<01:51,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_11/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 77%|███████▋  | 464/606 [06:10<01:50,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 77%|███████▋  | 466/606 [06:12<01:48,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 77%|███████▋  | 468/606 [06:13<01:47,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 78%|███████▊  | 470/606 [06:15<01:48,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CCRBBXHXJMPAHM-QGZVFWFLSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 78%|███████▊  | 472/606 [06:17<01:44,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/XVXACZLZNPRNEF-LLVKDONJSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 78%|███████▊  | 474/606 [06:18<01:42,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/XVXACZLZNPRNEF-LLVKDONJSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 79%|███████▊  | 476/606 [06:20<01:41,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/XVXACZLZNPRNEF-LLVKDONJSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 79%|███████▉  | 478/606 [06:21<01:39,  1.28it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/XVXACZLZNPRNEF-LLVKDONJSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 79%|███████▉  | 480/606 [06:23<01:37,  1.29it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 80%|███████▉  | 482/606 [06:24<01:34,  1.31it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 80%|███████▉  | 484/606 [06:26<01:32,  1.32it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 80%|████████  | 486/606 [06:27<01:30,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 81%|████████  | 488/606 [06:29<01:28,  1.33it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 81%|████████  | 490/606 [06:30<01:31,  1.26it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 81%|████████  | 492/606 [06:32<01:31,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FMKIQTJCGKBWQI-LBPRGKRZSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 82%|████████▏ | 494/606 [06:34<01:29,  1.25it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CTDSXZLFAXPRHX-MRVPVSSYSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 82%|████████▏ | 496/606 [06:35<01:28,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CTDSXZLFAXPRHX-MRVPVSSYSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 82%|████████▏ | 498/606 [06:37<01:27,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CTDSXZLFAXPRHX-MRVPVSSYSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 83%|████████▎ | 500/606 [06:39<01:25,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/CTDSXZLFAXPRHX-MRVPVSSYSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 83%|████████▎ | 502/606 [06:40<01:25,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-RBUKOAKNSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 83%|████████▎ | 504/606 [06:42<01:27,  1.17it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RJKNIIOSLLEQAJ-LBPRGKRZSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 83%|████████▎ | 506/606 [06:44<01:28,  1.13it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/RJKNIIOSLLEQAJ-LBPRGKRZSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 84%|████████▍ | 508/606 [06:46<01:27,  1.12it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YZOJKEJLMYATFV-CYBMUJFWSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 84%|████████▍ | 510/606 [06:48<01:25,  1.13it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YZOJKEJLMYATFV-CYBMUJFWSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 84%|████████▍ | 512/606 [06:50<01:27,  1.08it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_13/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 85%|████████▍ | 514/606 [06:51<01:25,  1.08it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_12/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 85%|████████▌ | 516/606 [06:53<01:22,  1.09it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_8/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 85%|████████▌ | 518/606 [06:55<01:21,  1.08it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 86%|████████▌ | 520/606 [06:57<01:18,  1.10it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 86%|████████▌ | 522/606 [06:59<01:14,  1.12it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 86%|████████▋ | 524/606 [07:00<01:12,  1.13it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_9/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 87%|████████▋ | 526/606 [07:02<01:11,  1.12it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_10/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 87%|████████▋ | 528/606 [07:04<01:08,  1.14it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_11/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 87%|████████▋ | 530/606 [07:06<01:06,  1.15it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 88%|████████▊ | 532/606 [07:07<01:04,  1.15it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 88%|████████▊ | 534/606 [07:09<01:01,  1.17it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 88%|████████▊ | 536/606 [07:11<00:59,  1.17it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/NGSCIQPXSPCNIO-AWEZNQCLSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 89%|████████▉ | 538/606 [07:12<00:57,  1.19it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZZYZJBMNVRAFBQ-LLVKDONJSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 89%|████████▉ | 540/606 [07:14<00:55,  1.19it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/ZZYZJBMNVRAFBQ-LLVKDONJSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 89%|████████▉ | 542/606 [07:16<00:53,  1.20it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_8/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 90%|████████▉ | 544/606 [07:17<00:50,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 90%|█████████ | 546/606 [07:19<00:48,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 90%|█████████ | 548/606 [07:20<00:46,  1.23it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 91%|█████████ | 550/606 [07:22<00:45,  1.24it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_9/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 91%|█████████ | 552/606 [07:24<00:44,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_10/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 91%|█████████▏| 554/606 [07:25<00:43,  1.19it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 92%|█████████▏| 556/606 [07:27<00:42,  1.18it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 92%|█████████▏| 558/606 [07:29<00:41,  1.17it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 92%|█████████▏| 560/606 [07:31<00:39,  1.17it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/YTGGYUWVIMAUAX-RTWAWAEBSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 93%|█████████▎| 562/606 [07:32<00:37,  1.17it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/QFLUMJQUCAPCRJ-OALUTQOASA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 93%|█████████▎| 564/606 [07:34<00:36,  1.16it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_12/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 93%|█████████▎| 566/606 [07:36<00:36,  1.09it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_8/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 94%|█████████▎| 568/606 [07:39<00:37,  1.01it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 94%|█████████▍| 570/606 [07:41<00:36,  1.02s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_6/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 94%|█████████▍| 572/606 [07:43<00:34,  1.01s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_7/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 95%|█████████▍| 574/606 [07:45<00:31,  1.01it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_9/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 95%|█████████▌| 576/606 [07:46<00:29,  1.02it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_10/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 95%|█████████▌| 578/606 [07:48<00:27,  1.03it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_11/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 96%|█████████▌| 580/606 [07:50<00:25,  1.03it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_5/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 96%|█████████▌| 582/606 [07:52<00:24,  1.00s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 96%|█████████▋| 584/606 [07:54<00:21,  1.01it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 97%|█████████▋| 586/606 [07:56<00:19,  1.03it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/FAYMTYBALKFINZ-CABZTGNLSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 97%|█████████▋| 588/606 [07:58<00:16,  1.07it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LSCORSGHQVIJEW-QGZVFWFLSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 97%|█████████▋| 590/606 [08:00<00:14,  1.08it/s]

No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 98%|█████████▊| 591/606 [08:02<00:16,  1.10s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LSCORSGHQVIJEW-QGZVFWFLSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 98%|█████████▊| 593/606 [08:04<00:13,  1.05s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/LSCORSGHQVIJEW-QGZVFWFLSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 98%|█████████▊| 595/606 [08:05<00:11,  1.01s/it]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WQPDKBFVGVJUHI-LLVKDONJSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 99%|█████████▊| 597/606 [08:07<00:08,  1.00it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WQPDKBFVGVJUHI-LLVKDONJSA-N/conf_2/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 99%|█████████▉| 599/606 [08:09<00:06,  1.04it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WQPDKBFVGVJUHI-LLVKDONJSA-N/conf_3/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

 99%|█████████▉| 601/606 [08:11<00:04,  1.07it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/WQPDKBFVGVJUHI-LLVKDONJSA-N/conf_4/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

100%|█████████▉| 603/606 [08:13<00:02,  1.10it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/KGZUJYDTOJDLJK-SNVBAGLBSA-N/conf_1/xyz.json.
No xyz.json file found in the specified path or overwrite_results is True. Results dictionary will be empty.

100%|██████████| 606/606 [08:14<00:00,  1.22it/s]

Loading existing results from DATA/LNiH2_library_001_to_download_2026_03_24/KGZUJYDTOJDLJK-SNVBAGLBSA-N/conf_2/xyz.json.

,SASA,SASA_Volume,%Vbur_atom_H1_radius_2.0,%Vbur_atom_H1_radius_2.5,%Vbur_atom_H1_radius_3.0,%Vbur_atom_H1_radius_3.5,%Vbur_atom_H1_radius_4.0,%Vbur_atom_H1_radius_4.5,%Vbur_atom_H1_radius_5.0,%Vbur_atom_H2_radius_2.0,...,Angle_H2_Ni_H1,Angle_Ni_N1_C1,Angle_Ni_N2_C2,Angle_N1_C1_C2,Angle_N2_C2_C1,Angle_N1_Ni_N2,Angle_C1_Ni_C2,Dihed_N1_C1_C2_N2,Dihed_C1_C2_N2_Ni,Dihed_C2_C1_N1_Ni
path,,,,,,,,,,,,,,,,,,,,,
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,463.840531,738.977808,68.217330,58.319768,49.576319,41.425759,35.255803,30.639979,27.199355,68.159220,...,80.285464,112.981331,113.778300,111.707017,119.327437,82.181615,30.439767,-0.264273,-0.930212,1.278973
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,463.840531,738.977808,68.217330,58.319768,49.576319,41.425759,35.255803,30.639979,27.199355,68.159220,...,80.285464,112.981331,113.778300,111.707017,119.327437,82.181615,30.439767,-0.264273,-0.930212,1.278973
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,463.390528,738.279360,68.252841,58.318140,49.604254,41.500885,35.322528,30.694794,27.242715,68.194731,...,80.423225,112.983540,113.755692,111.715757,119.338761,82.195506,30.442198,-0.421224,-0.389638,0.985586
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,463.390528,738.279360,68.252841,58.318140,49.604254,41.500885,35.322528,30.694794,27.242715,68.194731,...,80.423225,112.983540,113.755692,111.715757,119.338761,82.195506,30.442198,-0.421224,-0.389638,0.985586
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25,658.628578,1117.755128,67.319861,57.343079,48.592074,41.020430,35.888911,32.580486,30.408021,74.596462,...,79.727473,113.673296,110.255125,112.146020,120.559024,83.229166,30.756306,-0.615986,3.047589,-2.268976

### Charges and Energy Descriptors

In [7]:
results_charges_dict = get_all_charges(df_num, atoms)
df_charges_desc = pd.DataFrame.from_dict(results_charges_dict, orient='index')
df_charges_desc.set_index('path', inplace=True)
df_charges_desc.head(5)

Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...
Parsing GBW JSON for singlepoint properties...

,mulliken_H1,mulliken_H2,mulliken_C1,mulliken_C2,mulliken_N1,mulliken_N2,mulliken_Ni,loewdin_H1,loewdin_H2,loewdin_C1,...,saniso_N1,saniso_N2,saniso_Ni,siso_H1,siso_H2,siso_C1,siso_C2,siso_N1,siso_N2,siso_Ni
path,,,,,,,,,,,,,,,,,,,,,
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.077996,-0.097464,0.109601,0.291640,-0.048309,-0.049192,-0.348348,-0.069781,-0.071689,-0.149184,...,366.483239,237.285020,-1920.025043,39.219221,40.217872,37.668341,17.161352,-2.515718,18.126859,-4049.465402
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.077996,-0.097464,0.109601,0.291640,-0.048309,-0.049192,-0.348348,-0.069781,-0.071689,-0.149184,...,366.483239,237.285020,-1920.025043,39.219221,40.217872,37.668341,17.161352,-2.515718,18.126859,-4049.465402
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.079398,-0.097876,0.108511,0.292047,-0.048006,-0.049183,-0.347179,-0.069868,-0.071959,-0.149172,...,367.025926,240.718564,-1934.564548,39.198500,40.214541,37.658881,17.139805,-2.552599,18.228884,-4060.608625
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.079398,-0.097876,0.108511,0.292047,-0.048006,-0.049183,-0.347179,-0.069868,-0.071959,-0.149172,...,367.025926,240.718564,-1934.564548,39.198500,40.214541,37.658881,17.139805,-2.552599,18.228884,-4060.608625
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25,-0.098376,-0.074072,0.030477,0.364906,-0.002199,-0.123407,-0.325068,-0.066446,-0.064130,-0.149660,...,397.221237,237.660611,-2606.009812,38.720765,42.552337,36.398284,17.046468,-34.346185,15.348416,-4296.334652

### NBO Descriptors

In [8]:
results_nbo_dict = get_all_nbo_properties(df_num, atoms, basename="singlepoint")
df_nbo_desc = results_nbo_dict.copy()
df_nbo_desc.set_index("path", inplace=True)
df_nbo_desc.head(5)

# filter homo informations to restrict to the range homo-5 to lumo+5
homo_lumo_range = [1, 2, 3, 4, 5]
colums_to_drop = []
for c in df_nbo_desc.columns:
    if re.search(r'_hm\d+_', c):
        if not any(f'_hm{h}_' in c for h in homo_lumo_range):
            colums_to_drop.append(c)
    elif re.search(r'_lp\d+_', c):
        if not any(f'_lp{l}_' in c for l in homo_lumo_range):
            colums_to_drop.append(c)
print(colums_to_drop)

# remove analysis info:
for c in df_nbo_desc.columns:
    if "analysis_info" in c:
        colums_to_drop.append(c)


# Note: the notation hmX means homo - X and lpX means lumo + X.

df_nbo_desc = df_nbo_desc.drop(columns=colums_to_drop)
df_nbo_desc.head(5)

Could not find end of NBO section
Could not find end of NBO section

,npa_H1_charge,npa_H1_core,npa_H1_valence,npa_H1_rydberg,npa_H1_total,npa_H2_charge,npa_H2_core,npa_H2_valence,npa_H2_rydberg,npa_H2_total,...,nho_directionality_hm_C1_C2_type,nho_directionality_hm_C1_C2_bond_index,nho_directionality_hm_C1_C2_line_theta,nho_directionality_hm_C1_C2_line_phi,nho_directionality_hm_C1_C2_hybrid_theta,nho_directionality_hm_C1_C2_hybrid_phi,nho_directionality_hm_C1_C2_deviation,nho_directionality_hm_C2_N2_hybrid_theta,nho_directionality_hm_C2_N2_hybrid_phi,nho_directionality_hm_C2_N2_deviation
path,,,,,,,,,,,,,,,,,,,,,
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.21653,0.0,1.21368,0.00285,1.21653,-0.22963,0.0,1.22667,0.00296,1.22963,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.21653,0.0,1.21368,0.00285,1.21653,-0.22963,0.0,1.22667,0.00296,1.22963,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.21662,0.0,1.21378,0.00284,1.21662,-0.23047,0.0,1.22752,0.00295,1.23047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.21662,0.0,1.21378,0.00284,1.21662,-0.23047,0.0,1.22752,0.00295,1.23047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25,-0.21984,0.0,1.21684,0.00300,1.21984,-0.23576,0.0,1.23294,0.00282,1.23576,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Vertical Redox Descriptors

In [9]:
results_redox_dict = get_redox_descriptors(df_num, atoms)
df_redox_desc = pd.DataFrame.from_dict(results_redox_dict, orient='index')
df_redox_desc.set_index('path', inplace=True)
df_redox_desc.head(5)

,Vertical_Ionization_Potential,Vertical_Electron_Affinity,Hardness,Electronegativity,Electrophilicity,fplus_mulliken_H1,fminus_mulliken_H1,fzero_mulliken_H1,fplus_mulliken_H2,fminus_mulliken_H2,...,fzero_mulliken_C2,fplus_mulliken_N1,fminus_mulliken_N1,fzero_mulliken_N1,fplus_mulliken_N2,fminus_mulliken_N2,fzero_mulliken_N2,fplus_mulliken_Ni,fminus_mulliken_Ni,fzero_mulliken_Ni
path,,,,,,,,,,,,,,,,,,,,,
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.208644,-0.036060,-0.086292,-0.122352,-0.086741,0.052206,0.157895,0.105050,0.071117,0.172430,...,0.041732,0.040563,-0.022216,0.009174,0.058408,-0.021983,0.018212,0.080482,0.263588,0.172035
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1,-0.208644,-0.036060,-0.086292,-0.122352,-0.086741,0.052206,0.157895,0.105050,0.071117,0.172430,...,0.041732,0.040563,-0.022216,0.009174,0.058408,-0.021983,0.018212,0.080482,0.263588,0.172035
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.208691,-0.036117,-0.086287,-0.122404,-0.086819,0.052415,0.158730,0.105573,0.071033,0.172497,...,0.041755,0.040534,-0.022350,0.009092,0.058377,-0.022069,0.018154,0.080286,0.262843,0.171564
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2,-0.208691,-0.036117,-0.086287,-0.122404,-0.086819,0.052415,0.158730,0.105573,0.071033,0.172497,...,0.041755,0.040534,-0.022350,0.009092,0.058377,-0.022069,0.018154,0.080286,0.262843,0.171564
orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25,-0.213338,-0.046233,-0.083552,-0.129785,-0.100800,0.050472,0.158524,0.104498,0.059904,0.166209,...,0.042802,0.043624,-0.010402,0.016611,0.065737,-0.028175,0.018781,0.073782,0.241608,0.157695

### Summary of Descriptors

In [10]:
# Build a single summary table matched by molecular path
from desc_utils.data_extraction import _truncate_to_orca_descriptors

# 1) Base table (normalize df_num path so it matches extractor outputs)
_repo_root = Path('desc_utils/data_extraction.py').resolve().parent.parent
df_num_idx = df_num.copy()
df_num_idx['path'] = df_num_idx['path'].map(lambda p: _truncate_to_orca_descriptors(p, _repo_root))
df_num_idx = df_num_idx.set_index("path")

# 2) Concatenate all descriptor tables on index (= path)
total_df = pd.concat(
    [df_num_idx, df_xyz_desc, df_charges_desc, df_redox_desc, df_nbo_desc],
    axis=1,
    join="outer"
)

# 3) Remove duplicated column names (keep first occurrence)
total_df = total_df.loc[:, ~total_df.columns.duplicated()]

# 4) Restore path as a normal column
total_df = total_df.reset_index().rename(columns={"index": "path"})

print("total_df shape:", total_df.shape)
total_df.head(3)

total_df shape: (606, 505)

,path,xyz_name,ligand_type,inchi,SCF_energy,smiles,H1,Ni,H2,N1,...,nho_directionality_hm_C1_C2_type,nho_directionality_hm_C1_C2_bond_index,nho_directionality_hm_C1_C2_line_theta,nho_directionality_hm_C1_C2_line_phi,nho_directionality_hm_C1_C2_hybrid_theta,nho_directionality_hm_C1_C2_hybrid_phi,nho_directionality_hm_C1_C2_deviation,nho_directionality_hm_C2_N2_hybrid_theta,nho_directionality_hm_C2_N2_hybrid_phi,nho_directionality_hm_C2_N2_deviation
0,orca_descriptors/DATA/LNiH2_library_001_to_dow...,conf_1,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425277,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,orca_descriptors/DATA/LNiH2_library_001_to_dow...,optimization,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425277,[H]C1=C(F)NC(=C2N[C@@]3([H])c4c([H])c([H])c([H...,1,2,3,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,orca_descriptors/DATA/LNiH2_library_001_to_dow...,conf_2,core_5,IJHJNYMOYGPPGZ-OCCSQVGLSA-N,-2371.425257,[H]C1=C([H])C([H])=C(F)N[C]1[C]1N[C@@]2([H])c3...,1,2,3,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# DescriPyTor

### Convert the ORCA output files to pseudo Gaussian log files for compatibility with descripytor generation. 

This step is necessary because descripy is designed to work with Gaussian log files, and the ORCA output files need to be converted to this format for descripy to process them correctly.

In [11]:
# convert orca files to log files | a log file is created for each conf_* subfolder in the orca_folder, and contains the same information as the orca output file but in a format that can be read by the descriptor calculation code
script_path = Path("orca2gaussian/orca_2_gauss.py")

if not script_path.exists():
    raise FileNotFoundError(f"Script not found: {script_path.resolve()}")
if not orca_folder.exists():
    raise FileNotFoundError(f"Folder not found: {orca_folder.resolve()}")


try:
    subprocess.run(
                [sys.executable, str(script_path), "--orca-folder", str(orca_folder)],
                capture_output=True,
                text=True,
                check=True,
            )

except subprocess.CalledProcessError as exc:
    print(f"Failed for {orca_folder}: {exc.stderr.strip() or exc}")

### DescriPyTor

#### Convert the log files to feather files for use in DescriPyTor.

In [ ]:
# Load Descripytor feather file utils
DESCRIPYTOR_DIR = Path("DescriPyTor/MolFeatures")
OVERWRITE_FEATHER = False  # Set to True to overwrite existing feather files, False to skip if feather file already exists
print(f"Setting DESCRIPYTOR_DIR to: {DESCRIPYTOR_DIR}")
sys.path.append(DESCRIPYTOR_DIR)
sys.path.append(os.path.join(DESCRIPYTOR_DIR, 'M3_modeler'))
sys.path.append(os.path.join(DESCRIPYTOR_DIR, 'M2_data_extractor'))
sys.path.append(os.path.join(DESCRIPYTOR_DIR, 'utils'))

try:
    from data_extractor import Molecules, extract_connectivity
    from feather_extractor import logs_to_feather
    import gaussian_handler
    from gaussian_handler import feather_file_handler
    from help_functions import dict_to_horizontal_df, get_df_from_file, pick_samples_to_remove_for_distribution
    import help_functions
    import visualize

    print("All modules imported successfully.")
    
except ModuleNotFoundError as e:
    print(f"Module import failed: {e} \nPlease ensure all required modules are installed and available in the path specified on the right hand corner of the notebook.")


pd.set_option('display.max_columns', None)

# log_dir = os.path.join(examples_path, 'logs_example')

# iterate over all the log files in the orca_folder and check if they exist, print the path of the log file if it exists, otherwise print a warning message, and extract the log files to a feather file.
pwd_before = os.getcwd()
print(f"Current working directory: {os.getcwd()}")
for inchi_folder in os.listdir(orca_folder):
    os.chdir(os.path.join(orca_folder, inchi_folder))
    for conf_folder in os.listdir('.'):
        if conf_folder.startswith('conf_') and os.path.isdir(conf_folder):
            os.chdir(conf_folder)
            log_file_path = None
            for f in os.listdir('.'):
                if f.endswith('.log'):
                    log_file_path = os.path.join(os.getcwd(), f)
            if log_file_path is None:
                print(f"No log file found in {os.getcwd()}")
            else:
                feather_file = log_file_path.replace('.log', '.feather')
                if os.path.exists(feather_file) and not OVERWRITE_FEATHER:
                    print(f"Feather file already exists, skipping: {feather_file}")
                else:
                    try:
                        logs_to_feather(os.getcwd(), feather_dir=os.getcwd())
                        print(f"Logs successfully converted to feather format at: {os.getcwd()}")
                    except Exception as e:
                        print(f"Error converting logs in {os.getcwd()} to feather format: {e}")
            os.chdir('..')
        
    os.chdir(pwd_before)

Setting DESCRIPYTOR_DIR to: DescriPyTor/MolFeatures
Module import failed: No module named 'modeling'
Please ensure all required modules are installed and available in the path specified on the right hand corner of the notebook.
Current working directory: /Users/julesschleinitz/Desktop/Code/orca_descriptors
conf_1.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_1.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_1
conf_2.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_2.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/IJHJNYMOYGPPGZ-OCCSQVGLSA-N/conf_2
conf_25.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_25.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_25
conf_22.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_22.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_22
conf_14.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_14.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_14
conf_13.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_13.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_13
conf_47.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_47.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_47
conf_78.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_78.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_78
conf_40.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_40.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_40
conf_82.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_82.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_82
conf_76.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_76.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_76
conf_49.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_49.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_49
conf_71.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_71.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_71
conf_85.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_85.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_85
conf_12.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_12.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_12
conf_15.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_15.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_15
conf_23.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_23.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_23
conf_24.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_24.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_24
conf_84.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_84.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_84
conf_70.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_70.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_70
conf_77.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_77.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_77
conf_83.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_83.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_83
conf_48.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_48.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_48
conf_41.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_41.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_41
conf_46.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_46.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_46
conf_79.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_79.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_79
conf_100.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_100.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_100
conf_90.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_90.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_90
conf_64.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_64.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_64
conf_63.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_63.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_63
conf_97.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_97.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_97
conf_55.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_55.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_55
conf_99.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_99.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_99
conf_52.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_52.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_52
conf_39.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_39.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_39
conf_8.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_8.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_8
conf_37.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_37.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_37
conf_1.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_1.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_1
conf_30.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_30.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_30
conf_6.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_6.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_6
conf_98.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_98.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_98
conf_53.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_53.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_53
conf_54.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_54.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_54
conf_96.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_96.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_96
conf_62.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_62.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_62
conf_65.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_65.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_65
conf_91.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_91.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_91
conf_31.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_31.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_31
conf_7.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_7.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_7
conf_36.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_36.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_36
conf_9.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_9.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_9
conf_38.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_38.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_38
conf_43.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_43.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_43
conf_88.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_88.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_88
conf_44.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_44.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_44
conf_72.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_72.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_72
conf_86.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_86.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_86
conf_81.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_81.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_81
conf_75.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_75.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_75
conf_21.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_21.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_21
conf_19.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_19.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_19
conf_26.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_26.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_26
conf_10.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_10.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_10
conf_28.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_28.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_28
conf_17.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_17.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_17
conf_74.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_74.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_74
conf_80.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_80.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_80
conf_87.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_87.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_87
conf_73.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_73.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_73
conf_45.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_45.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_45
conf_42.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_42.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_42
conf_89.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_89.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_89
conf_29.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_29.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_29
conf_16.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_16.feather
Done!
Logs successfully converted to feather format at: /Users/julesschleinitz/Desktop/Code/orca_descriptors/DATA/LNiH2_library_001_to_download_2026_03_24/DVLYVQBEMHJQAQ-SFHVURJKSA-N/conf_16
conf_11.log: NBO, Hirshfeld and CM5 charges
Data saved to conf_11.feather
Done!

#### Extract DescriPyTor descriptors (vibrations, dipoles and sterimol descriptors)

In [ ]:

os.chdir(ROOT_DIR)

# renumbering of the atoms in the feather files according to the df_num numberings
renumbering_convention = {"H1": 1, "H2": 2, "Ni": 3, "N1": 4, "C1": 5, "C2": 6, "N2": 7}

desc_all = {}
for i, row in tqdm(df_num.iterrows(), total=df_num.shape[0]):
    os.chdir(ROOT_DIR)
    desc_mol = {}
    # read path
    feather_dir = row['path']
    desc_mol['feather_dir'] = feather_dir
    # create Molecule object and renumber atoms according to the df_num numberings
    mols = Molecules(molecules_dir_name=feather_dir)

    # global descriptors
    ## 1-atom descriptors
    charges_dict    = mols.get_charge_df_dict(atom_indices=[row[x] for x in atoms]) # NBO
    index = charges_dict.index[0]
    for j, atom in enumerate(atoms):
        desc_mol[f'charge_NBO_{atom}'] = charges_dict.loc[index, f"nbo_atom_{row[atom]}"]

    ## 2-atom descriptors
    # sterimol descriptors (uses "bonds" list defined above to determine which sterimol descriptors to calculate)
    sterimol_descriptors    = mols.get_sterimol_dict(atom_indices=[[row[x], row[y]] for x, y in bonds])
    for j, (x1, x2) in enumerate(bonds):
        desc_mol[f'B1_{x1}-{x2}']           = sterimol_descriptors.loc[index, f'B1_{row[x1]}-{row[x2]}']
        desc_mol[f'B5_{x1}-{x2}']           = sterimol_descriptors.loc[index, f'B5_{row[x1]}-{row[x2]}']
        desc_mol[f'L_{x1}-{x2}']            = sterimol_descriptors.loc[index, f'L_{row[x1]}-{row[x2]}']
        desc_mol[f'loc_B5_{x1}-{x2}']       = sterimol_descriptors.loc[index, f'loc_B5_{row[x1]}-{row[x2]}']
        desc_mol[f'B1-B5_angle_{x1}-{x2}']  = sterimol_descriptors.loc[index, f'B1_B5_angle_{row[x1]}-{row[x2]}']

    bond_length_dict        = mols.get_bond_length_dict(atom_pairs=[[row[x], row[y]] for x, y in bonds]) # dataframe with bond length descriptors for specified bonds
    for j, (x1, x2) in enumerate(bonds):
        desc_mol[f'dist_{x1}-{x2}'] = bond_length_dict.loc[index, f'0_bond_length_{row[x1]}-{row[x2]}']

    vibrations_dict         = mols.get_stretch_vibration_dict(atom_pairs=[[row[x], row[y]] for x, y in bonds]) # dataframe with vibration descriptors for all molecules in the feather file, can be filtered for specific vibrations of interest based on the atoms involved in the vibration
    for j, (x1, x2) in enumerate(bonds):
        desc_mol[f'vib_freq_{x1}-{x2}'] = vibrations_dict.loc[index, f'Frequency_Stretch_{row[x1]}_{row[x2]}']
        desc_mol[f'vib_amp_{x1}-{x2}'] = vibrations_dict.loc[index, f'Amplitude_Stretch_{row[x1]}_{row[x2]}']

    vibrations_bend_dict    = mols.get_bend_vibration_dict(atom_pairs=[[row[x], row[y]] for x, y in pairs_bending]) # dataframe with bend vibration descriptors for specified angles
    for j, (x1, x2) in enumerate(pairs_bending):
        desc_mol[f'vib_freq_bend_{x1}-{x2}'] = vibrations_bend_dict.loc[index, f'Frequency_Bending_{row[x1]}-{row[x2]}']
        desc_mol[f'vib_amp_bend_{x1}-{x2}']  = vibrations_bend_dict.loc[index, f'Cross_mag_Bending_{row[x1]}-{row[x2]}']
    
    charges_diff_dict       = mols.get_charge_diff_df_dict(atom_indices=[[row[x], row[y]] for x, y in bonds]) # dataframe with charge difference descriptors for specified bonds
    for j, (x1, x2) in enumerate(bonds):
        desc_mol[f'charge_NBO_diff_{x1}-{x2}'] = charges_diff_dict.loc[index, f'nbo_diff_{row[x1]}-{row[x2]}']

    ## 3-atom descriptors
    dipole_ni = mols.get_dipole_dict(atom_indices=[row["Ni"], row["N2"], row["N1"]]) # dataframe with dipole moment descriptors for specified atom
    desc_mol['dipole'] = dipole_ni.loc[index, f'total_dipole_{row["Ni"]}-{row["N2"]}-{row["N1"]}']
    desc_mol['dipole_x_Ni-N2-N1'] = dipole_ni.loc[index, f'dipole_x_{row["Ni"]}-{row["N2"]}-{row["N1"]}']
    desc_mol['dipole_y_Ni-N2-N1'] = dipole_ni.loc[index, f'dipole_y_{row["Ni"]}-{row["N2"]}-{row["N1"]}']
    desc_mol['dipole_z_Ni-N2-N1'] = dipole_ni.loc[index, f'dipole_z_{row["Ni"]}-{row["N2"]}-{row["N1"]}']

    angles_dict = mols.get_bond_angle_dict(atom_indices=[[row[x], row[y], row[z]] for x, y, z in angles])
    for j, (x1, x2, x3) in enumerate(angles):
        desc_mol[f'angle_{x1}-{x2}-{x3}'] = angles_dict.loc[index, f'0_angle_[{row[x1]}, {row[x2]}, {row[x3]}]']

    desc_all[i] = desc_mol

df_desc = pd.DataFrame.from_dict(desc_all, orient='index')
df_desc.head(5)

  0%|          | 0/606 [00:00<?, ?it/s]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

  0%|          | 1/606 [00:00<08:22,  1.20it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

  0%|          | 2/606 [00:01<08:31,  1.18it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

  0%|          | 3/606 [00:02<08:18,  1.21it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

  1%|          | 4/606 [00:03<08:24,  1.19it/s]

Calculating stretch vibration for atoms [[6, 12], [12, 6], [5, 4], [4, 5], [2, 12], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 12]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_25.feather'] Failed Molecules: []

  1%|          | 5/606 [00:05<11:56,  1.19s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_25 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_25 for [2, 4]

Molecules Loaded: ['conf_25.feather'] Failed Molecules: []

  1%|          | 6/606 [00:07<14:21,  1.44s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_25 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_25 for [2, 4]

Molecules Loaded: ['conf_22.feather'] Failed Molecules: []

  1%|          | 7/606 [00:08<15:44,  1.58s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_22 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_22 for [2, 4]

Molecules Loaded: ['conf_22.feather'] Failed Molecules: []

  1%|▏         | 8/606 [00:10<16:41,  1.67s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_22 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_22 for [2, 4]

Molecules Loaded: ['conf_14.feather'] Failed Molecules: []

  1%|▏         | 9/606 [00:12<17:33,  1.76s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 4]

Molecules Loaded: ['conf_14.feather'] Failed Molecules: []

  2%|▏         | 10/606 [00:14<18:23,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_14 for [2, 4]

Molecules Loaded: ['conf_13.feather'] Failed Molecules: []

  2%|▏         | 11/606 [00:16<18:36,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 4]

Molecules Loaded: ['conf_13.feather'] Failed Molecules: []

  2%|▏         | 12/606 [00:18<18:30,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_13 for [2, 4]

Molecules Loaded: ['conf_47.feather'] Failed Molecules: []

  2%|▏         | 13/606 [00:20<18:39,  1.89s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_47 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_47 for [2, 4]

Molecules Loaded: ['conf_47.feather'] Failed Molecules: []

  2%|▏         | 14/606 [00:22<18:47,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_47 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_47 for [2, 4]

Molecules Loaded: ['conf_78.feather'] Failed Molecules: []

  2%|▏         | 15/606 [00:24<18:46,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_78 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_78 for [2, 4]

Molecules Loaded: ['conf_78.feather'] Failed Molecules: []

  3%|▎         | 16/606 [00:26<18:37,  1.89s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_78 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_78 for [2, 4]

Molecules Loaded: ['conf_40.feather'] Failed Molecules: []

  3%|▎         | 17/606 [00:28<18:33,  1.89s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_40 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_40 for [2, 4]

Molecules Loaded: ['conf_40.feather'] Failed Molecules: []

  3%|▎         | 18/606 [00:29<18:14,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_40 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_40 for [2, 4]

Molecules Loaded: ['conf_82.feather'] Failed Molecules: []

  3%|▎         | 19/606 [00:31<18:02,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_82 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_82 for [2, 4]

Molecules Loaded: ['conf_82.feather'] Failed Molecules: []

  3%|▎         | 20/606 [00:33<18:09,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_82 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_82 for [2, 4]

Molecules Loaded: ['conf_76.feather'] Failed Molecules: []

  3%|▎         | 21/606 [00:35<18:15,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_76 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_76 for [2, 4]

Molecules Loaded: ['conf_76.feather'] Failed Molecules: []

  4%|▎         | 22/606 [00:37<18:09,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_76 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_76 for [2, 4]

Molecules Loaded: ['conf_49.feather'] Failed Molecules: []

  4%|▍         | 23/606 [00:39<18:12,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_49 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_49 for [2, 4]

Molecules Loaded: ['conf_49.feather'] Failed Molecules: []

  4%|▍         | 24/606 [00:41<18:11,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_49 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_49 for [2, 4]

Molecules Loaded: ['conf_71.feather'] Failed Molecules: []

  4%|▍         | 25/606 [00:43<18:06,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_71 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_71 for [2, 4]

Molecules Loaded: ['conf_71.feather'] Failed Molecules: []

  4%|▍         | 26/606 [00:44<17:44,  1.83s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_71 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_71 for [2, 15]

Molecules Loaded: ['conf_85.feather'] Failed Molecules: []

  4%|▍         | 27/606 [00:46<17:45,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_85 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_85 for [2, 4]

Molecules Loaded: ['conf_85.feather'] Failed Molecules: []

  5%|▍         | 28/606 [00:48<17:39,  1.83s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_85 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_85 for [2, 15]

Molecules Loaded: ['conf_12.feather'] Failed Molecules: []

  5%|▍         | 29/606 [00:50<17:34,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 4]

Molecules Loaded: ['conf_12.feather'] Failed Molecules: []

  5%|▍         | 30/606 [00:52<17:54,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_12 for [2, 4]

Molecules Loaded: ['conf_15.feather'] Failed Molecules: []

  5%|▌         | 31/606 [00:54<17:47,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 4]

Molecules Loaded: ['conf_15.feather'] Failed Molecules: []

  5%|▌         | 32/606 [00:55<17:41,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_15 for [2, 4]

Molecules Loaded: ['conf_23.feather'] Failed Molecules: []

  5%|▌         | 33/606 [00:57<17:41,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_23 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_23 for [2, 4]

Molecules Loaded: ['conf_23.feather'] Failed Molecules: []

  6%|▌         | 34/606 [00:59<17:37,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_23 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_23 for [2, 4]

Molecules Loaded: ['conf_24.feather'] Failed Molecules: []

  6%|▌         | 35/606 [01:01<17:36,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_24 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_24 for [2, 4]

Molecules Loaded: ['conf_24.feather'] Failed Molecules: []

  6%|▌         | 36/606 [01:03<17:40,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_24 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_24 for [2, 4]

Molecules Loaded: ['conf_84.feather'] Failed Molecules: []

  6%|▌         | 37/606 [01:05<17:34,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_84 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_84 for [2, 4]

Molecules Loaded: ['conf_84.feather'] Failed Molecules: []

  6%|▋         | 38/606 [01:07<17:32,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_84 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_84 for [2, 4]

Molecules Loaded: ['conf_70.feather'] Failed Molecules: []

  6%|▋         | 39/606 [01:08<17:30,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_70 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_70 for [2, 4]

Molecules Loaded: ['conf_70.feather'] Failed Molecules: []

  7%|▋         | 40/606 [01:10<17:40,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_70 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_70 for [2, 4]

Molecules Loaded: ['conf_77.feather'] Failed Molecules: []

  7%|▋         | 41/606 [01:12<17:31,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_77 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_77 for [2, 4]

Molecules Loaded: ['conf_77.feather'] Failed Molecules: []

  7%|▋         | 42/606 [01:14<18:03,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_77 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_77 for [2, 4]

Molecules Loaded: ['conf_83.feather'] Failed Molecules: []

  7%|▋         | 43/606 [01:16<17:47,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_83 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_83 for [2, 4]

Molecules Loaded: ['conf_83.feather'] Failed Molecules: []

  7%|▋         | 44/606 [01:18<17:36,  1.88s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_83 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_83 for [2, 15]

Molecules Loaded: ['conf_48.feather'] Failed Molecules: []

  7%|▋         | 45/606 [01:20<17:30,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_48 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_48 for [2, 4]

Molecules Loaded: ['conf_48.feather'] Failed Molecules: []

  8%|▊         | 46/606 [01:22<17:17,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_48 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_48 for [2, 4]

Molecules Loaded: ['conf_41.feather'] Failed Molecules: []

  8%|▊         | 47/606 [01:23<17:06,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_41 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_41 for [2, 4]

Molecules Loaded: ['conf_41.feather'] Failed Molecules: []

  8%|▊         | 48/606 [01:25<16:54,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_41 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_41 for [2, 4]

Molecules Loaded: ['conf_46.feather'] Failed Molecules: []

  8%|▊         | 49/606 [01:27<16:52,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_46 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_46 for [2, 4]

Molecules Loaded: ['conf_46.feather'] Failed Molecules: []

  8%|▊         | 50/606 [01:29<16:47,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_46 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_46 for [2, 4]

Molecules Loaded: ['conf_79.feather'] Failed Molecules: []

  8%|▊         | 51/606 [01:30<16:39,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_79 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_79 for [2, 4]

Molecules Loaded: ['conf_79.feather'] Failed Molecules: []

  9%|▊         | 52/606 [01:32<16:37,  1.80s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_79 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_79 for [2, 15]

Molecules Loaded: ['conf_100.feather'] Failed Molecules: []

  9%|▊         | 53/606 [01:34<16:39,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_100 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_100 for [2, 4]

Molecules Loaded: ['conf_100.feather'] Failed Molecules: []

  9%|▉         | 54/606 [01:36<16:38,  1.81s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_100 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_100 for [2, 15]

Molecules Loaded: ['conf_90.feather'] Failed Molecules: []

  9%|▉         | 55/606 [01:38<16:33,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_90 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_90 for [2, 4]

Molecules Loaded: ['conf_90.feather'] Failed Molecules: []

  9%|▉         | 56/606 [01:40<16:33,  1.81s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_90 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_90 for [2, 15]

Molecules Loaded: ['conf_64.feather'] Failed Molecules: []

  9%|▉         | 57/606 [01:41<16:30,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_64 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_64 for [2, 4]

Molecules Loaded: ['conf_64.feather'] Failed Molecules: []

 10%|▉         | 58/606 [01:43<16:28,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_64 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_64 for [2, 4]

Molecules Loaded: ['conf_63.feather'] Failed Molecules: []

 10%|▉         | 59/606 [01:45<16:29,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_63 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_63 for [2, 4]

Molecules Loaded: ['conf_63.feather'] Failed Molecules: []

 10%|▉         | 60/606 [01:47<16:41,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_63 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_63 for [2, 4]

Molecules Loaded: ['conf_97.feather'] Failed Molecules: []

 10%|█         | 61/606 [01:49<16:36,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_97 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_97 for [2, 4]

Molecules Loaded: ['conf_97.feather'] Failed Molecules: []

 10%|█         | 62/606 [01:50<16:24,  1.81s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_97 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_97 for [2, 15]

Molecules Loaded: ['conf_55.feather'] Failed Molecules: []

 10%|█         | 63/606 [01:52<16:21,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_55 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_55 for [2, 4]

Molecules Loaded: ['conf_55.feather'] Failed Molecules: []

 11%|█         | 64/606 [01:54<16:20,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_55 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_55 for [2, 4]

Molecules Loaded: ['conf_99.feather'] Failed Molecules: []

 11%|█         | 65/606 [01:56<16:19,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_99 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_99 for [2, 4]

Molecules Loaded: ['conf_99.feather'] Failed Molecules: []

 11%|█         | 66/606 [01:58<16:09,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_99 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_99 for [2, 4]

Molecules Loaded: ['conf_52.feather'] Failed Molecules: []

 11%|█         | 67/606 [01:59<16:18,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_52 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_52 for [2, 4]

Molecules Loaded: ['conf_52.feather'] Failed Molecules: []

 11%|█         | 68/606 [02:01<16:16,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_52 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_52 for [2, 4]

Molecules Loaded: ['conf_39.feather'] Failed Molecules: []

 11%|█▏        | 69/606 [02:03<16:07,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_39 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_39 for [2, 4]

Molecules Loaded: ['conf_39.feather'] Failed Molecules: []

 12%|█▏        | 70/606 [02:05<16:17,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_39 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_39 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 12%|█▏        | 71/606 [02:07<16:27,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_8.feather'] Failed Molecules: []

 12%|█▏        | 72/606 [02:09<16:12,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_8 for [2, 4]

Molecules Loaded: ['conf_37.feather'] Failed Molecules: []

 12%|█▏        | 73/606 [02:10<16:05,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_37 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_37 for [2, 4]

Molecules Loaded: ['conf_37.feather'] Failed Molecules: []

 12%|█▏        | 74/606 [02:12<16:31,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_37 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_37 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 12%|█▏        | 75/606 [02:14<16:30,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 13%|█▎        | 76/606 [02:16<16:19,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_30.feather'] Failed Molecules: []

 13%|█▎        | 77/606 [02:18<16:15,  1.84s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_30 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_30 for [2, 4]

Molecules Loaded: ['conf_30.feather'] Failed Molecules: []

 13%|█▎        | 78/606 [02:20<16:05,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_30 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_30 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 13%|█▎        | 79/606 [02:21<16:00,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 13%|█▎        | 80/606 [02:23<16:03,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_98.feather'] Failed Molecules: []

 13%|█▎        | 81/606 [02:25<15:58,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_98 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_98 for [2, 4]

Molecules Loaded: ['conf_98.feather'] Failed Molecules: []

 14%|█▎        | 82/606 [02:27<15:55,  1.82s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_98 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_98 for [2, 15]

Molecules Loaded: ['conf_53.feather'] Failed Molecules: []

 14%|█▎        | 83/606 [02:29<15:52,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_53 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_53 for [2, 4]

Molecules Loaded: ['conf_53.feather'] Failed Molecules: []

 14%|█▍        | 84/606 [02:31<15:48,  1.82s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_53 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_53 for [2, 4]

Molecules Loaded: ['conf_54.feather'] Failed Molecules: []

 14%|█▍        | 85/606 [02:32<15:44,  1.81s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_54 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_54 for [2, 4]

Molecules Loaded: ['conf_54.feather'] Failed Molecules: []

 14%|█▍        | 86/606 [02:34<15:36,  1.80s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_54 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_54 for [2, 4]

Molecules Loaded: ['conf_96.feather'] Failed Molecules: []

 14%|█▍        | 87/606 [02:36<16:01,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_96 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_96 for [2, 4]

Molecules Loaded: ['conf_96.feather'] Failed Molecules: []

 15%|█▍        | 88/606 [02:38<16:02,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_96 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_96 for [2, 4]

Molecules Loaded: ['conf_62.feather'] Failed Molecules: []

 15%|█▍        | 89/606 [02:40<15:45,  1.83s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_62 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_62 for [2, 4]

Molecules Loaded: ['conf_62.feather'] Failed Molecules: []

 15%|█▍        | 90/606 [02:42<15:55,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_62 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_62 for [2, 4]

Molecules Loaded: ['conf_65.feather'] Failed Molecules: []

 15%|█▌        | 91/606 [02:44<15:56,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_65 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_65 for [2, 4]

Molecules Loaded: ['conf_65.feather'] Failed Molecules: []

 15%|█▌        | 92/606 [02:45<15:52,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_65 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_65 for [2, 4]

Molecules Loaded: ['conf_91.feather'] Failed Molecules: []

 15%|█▌        | 93/606 [02:47<16:06,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_91 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_91 for [2, 4]

Molecules Loaded: ['conf_91.feather'] Failed Molecules: []

 16%|█▌        | 94/606 [02:49<15:59,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_91 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_91 for [2, 4]

Molecules Loaded: ['conf_31.feather'] Failed Molecules: []

 16%|█▌        | 95/606 [02:51<16:01,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_31 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_31 for [2, 4]

Molecules Loaded: ['conf_31.feather'] Failed Molecules: []

 16%|█▌        | 96/606 [02:53<15:47,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_31 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_31 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 16%|█▌        | 97/606 [02:55<15:42,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 16%|█▌        | 98/606 [02:57<15:41,  1.85s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_36.feather'] Failed Molecules: []

 16%|█▋        | 99/606 [02:58<15:45,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_36 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_36 for [2, 4]

Molecules Loaded: ['conf_36.feather'] Failed Molecules: []

 17%|█▋        | 100/606 [03:00<15:52,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_36 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_36 for [2, 4]

Molecules Loaded: ['conf_9.feather'] Failed Molecules: []

 17%|█▋        | 101/606 [03:02<15:59,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 4]

Molecules Loaded: ['conf_9.feather'] Failed Molecules: []

 17%|█▋        | 102/606 [03:04<15:55,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_9 for [2, 4]

Molecules Loaded: ['conf_38.feather'] Failed Molecules: []

 17%|█▋        | 103/606 [03:06<16:00,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_38 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_38 for [2, 4]

Molecules Loaded: ['conf_38.feather'] Failed Molecules: []

 17%|█▋        | 104/606 [03:08<15:58,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_38 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_38 for [2, 4]

Molecules Loaded: ['conf_43.feather'] Failed Molecules: []

 17%|█▋        | 105/606 [03:10<15:59,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_43 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_43 for [2, 4]

Molecules Loaded: ['conf_43.feather'] Failed Molecules: []

 17%|█▋        | 106/606 [03:12<15:57,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_43 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_43 for [2, 4]

Molecules Loaded: ['conf_88.feather'] Failed Molecules: []

 18%|█▊        | 107/606 [03:14<15:59,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_88 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_88 for [2, 4]

Molecules Loaded: ['conf_88.feather'] Failed Molecules: []

 18%|█▊        | 108/606 [03:16<15:48,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_88 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_88 for [2, 4]

Molecules Loaded: ['conf_44.feather'] Failed Molecules: []

 18%|█▊        | 109/606 [03:18<15:59,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_44 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_44 for [2, 4]

Molecules Loaded: ['conf_44.feather'] Failed Molecules: []

 18%|█▊        | 110/606 [03:20<15:54,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_44 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_44 for [2, 4]

Molecules Loaded: ['conf_72.feather'] Failed Molecules: []

 18%|█▊        | 111/606 [03:22<15:53,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_72 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_72 for [2, 4]

Molecules Loaded: ['conf_72.feather'] Failed Molecules: []

 18%|█▊        | 112/606 [03:23<15:34,  1.89s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_72 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_72 for [2, 4]

Molecules Loaded: ['conf_86.feather'] Failed Molecules: []

 19%|█▊        | 113/606 [03:25<15:34,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_86 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_86 for [2, 4]

Molecules Loaded: ['conf_86.feather'] Failed Molecules: []

 19%|█▉        | 114/606 [03:27<15:43,  1.92s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_86 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_86 for [2, 15]

Molecules Loaded: ['conf_81.feather'] Failed Molecules: []

 19%|█▉        | 115/606 [03:29<15:42,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_81 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_81 for [2, 4]

Molecules Loaded: ['conf_81.feather'] Failed Molecules: []

 19%|█▉        | 116/606 [03:31<15:32,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_81 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_81 for [2, 4]

Molecules Loaded: ['conf_75.feather'] Failed Molecules: []

 19%|█▉        | 117/606 [03:33<15:35,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_75 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_75 for [2, 4]

Molecules Loaded: ['conf_75.feather'] Failed Molecules: []

 19%|█▉        | 118/606 [03:35<15:29,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_75 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_75 for [2, 4]

Molecules Loaded: ['conf_21.feather'] Failed Molecules: []

 20%|█▉        | 119/606 [03:37<15:26,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_21 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_21 for [2, 4]

Molecules Loaded: ['conf_21.feather'] Failed Molecules: []

 20%|█▉        | 120/606 [03:39<15:22,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_21 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_21 for [2, 4]

Molecules Loaded: ['conf_19.feather'] Failed Molecules: []

 20%|█▉        | 121/606 [03:41<15:24,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_19 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_19 for [2, 4]

Molecules Loaded: ['conf_19.feather'] Failed Molecules: []

 20%|██        | 122/606 [03:43<15:27,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_19 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_19 for [2, 4]

Molecules Loaded: ['conf_26.feather'] Failed Molecules: []

 20%|██        | 123/606 [03:44<15:15,  1.89s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_26 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_26 for [2, 4]

Molecules Loaded: ['conf_26.feather'] Failed Molecules: []

 20%|██        | 124/606 [03:46<15:20,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_26 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_26 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 21%|██        | 125/606 [03:48<15:22,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_10.feather'] Failed Molecules: []

 21%|██        | 126/606 [03:50<15:07,  1.89s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_10 for [2, 4]

Molecules Loaded: ['conf_28.feather'] Failed Molecules: []

 21%|██        | 127/606 [03:52<14:58,  1.88s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_28 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_28 for [2, 4]

Molecules Loaded: ['conf_28.feather'] Failed Molecules: []

 21%|██        | 128/606 [03:54<14:53,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_28 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_28 for [2, 4]

Molecules Loaded: ['conf_17.feather'] Failed Molecules: []

 21%|██▏       | 129/606 [03:56<14:47,  1.86s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 4]

Molecules Loaded: ['conf_17.feather'] Failed Molecules: []

 21%|██▏       | 130/606 [03:57<14:48,  1.87s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_17 for [2, 4]

Molecules Loaded: ['conf_74.feather'] Failed Molecules: []

 22%|██▏       | 131/606 [03:59<15:03,  1.90s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_74 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_74 for [2, 4]

Molecules Loaded: ['conf_74.feather'] Failed Molecules: []

 22%|██▏       | 132/606 [04:01<15:03,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_74 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_74 for [2, 4]

Molecules Loaded: ['conf_80.feather'] Failed Molecules: []

 22%|██▏       | 133/606 [04:03<15:09,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_80 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_80 for [2, 4]

Molecules Loaded: ['conf_80.feather'] Failed Molecules: []

 22%|██▏       | 134/606 [04:05<15:13,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_80 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_80 for [2, 4]

Molecules Loaded: ['conf_87.feather'] Failed Molecules: []

 22%|██▏       | 135/606 [04:07<15:14,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_87 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_87 for [2, 4]

Molecules Loaded: ['conf_87.feather'] Failed Molecules: []

 22%|██▏       | 136/606 [04:09<15:05,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_87 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_87 for [2, 4]

Molecules Loaded: ['conf_73.feather'] Failed Molecules: []

 23%|██▎       | 137/606 [04:11<15:02,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_73 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_73 for [2, 4]

Molecules Loaded: ['conf_73.feather'] Failed Molecules: []

 23%|██▎       | 138/606 [04:13<15:06,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_73 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_73 for [2, 4]

Molecules Loaded: ['conf_45.feather'] Failed Molecules: []

 23%|██▎       | 139/606 [04:15<15:14,  1.96s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_45 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_45 for [2, 4]

Molecules Loaded: ['conf_45.feather'] Failed Molecules: []

 23%|██▎       | 140/606 [04:17<15:18,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_45 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_45 for [2, 4]

Molecules Loaded: ['conf_42.feather'] Failed Molecules: []

 23%|██▎       | 141/606 [04:19<15:16,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_42 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_42 for [2, 4]

Molecules Loaded: ['conf_42.feather'] Failed Molecules: []

 23%|██▎       | 142/606 [04:21<15:05,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_42 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_42 for [2, 4]

Molecules Loaded: ['conf_89.feather'] Failed Molecules: []

 24%|██▎       | 143/606 [04:23<14:57,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_89 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_89 for [2, 4]

Molecules Loaded: ['conf_89.feather'] Failed Molecules: []

 24%|██▍       | 144/606 [04:25<14:49,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_89 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_89 for [2, 4]

Molecules Loaded: ['conf_29.feather'] Failed Molecules: []

 24%|██▍       | 145/606 [04:27<14:50,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_29 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_29 for [2, 4]

Molecules Loaded: ['conf_29.feather'] Failed Molecules: []

 24%|██▍       | 146/606 [04:29<14:47,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_29 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_29 for [2, 4]

Molecules Loaded: ['conf_16.feather'] Failed Molecules: []

 24%|██▍       | 147/606 [04:31<14:53,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 4]

Molecules Loaded: ['conf_16.feather'] Failed Molecules: []

 24%|██▍       | 148/606 [04:32<14:47,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_16 for [2, 4]

Molecules Loaded: ['conf_11.feather'] Failed Molecules: []

 25%|██▍       | 149/606 [04:34<14:39,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 4]

Molecules Loaded: ['conf_11.feather'] Failed Molecules: []

 25%|██▍       | 150/606 [04:36<14:39,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_11 for [2, 4]

Molecules Loaded: ['conf_18.feather'] Failed Molecules: []

 25%|██▍       | 151/606 [04:38<14:49,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_18 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_18 for [2, 4]

Molecules Loaded: ['conf_18.feather'] Failed Molecules: []

 25%|██▌       | 152/606 [04:40<14:40,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_18 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_18 for [2, 4]

Molecules Loaded: ['conf_27.feather'] Failed Molecules: []

 25%|██▌       | 153/606 [04:42<14:47,  1.96s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_27 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_27 for [2, 4]

Molecules Loaded: ['conf_27.feather'] Failed Molecules: []

 25%|██▌       | 154/606 [04:44<14:50,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_27 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_27 for [2, 4]

Molecules Loaded: ['conf_20.feather'] Failed Molecules: []

 26%|██▌       | 155/606 [04:46<14:50,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_20 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_20 for [2, 4]

Molecules Loaded: ['conf_20.feather'] Failed Molecules: []

 26%|██▌       | 156/606 [04:48<14:34,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_20 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_20 for [2, 4]

Molecules Loaded: ['conf_33.feather'] Failed Molecules: []

 26%|██▌       | 157/606 [04:50<14:28,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_33 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_33 for [2, 4]

Molecules Loaded: ['conf_33.feather'] Failed Molecules: []

 26%|██▌       | 158/606 [04:52<14:23,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_33 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_33 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 26%|██▌       | 159/606 [04:54<14:12,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 26%|██▋       | 160/606 [04:56<14:11,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_34.feather'] Failed Molecules: []

 27%|██▋       | 161/606 [04:58<14:12,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_34 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_34 for [2, 4]

Molecules Loaded: ['conf_34.feather'] Failed Molecules: []

 27%|██▋       | 162/606 [05:00<14:09,  1.91s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_34 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_34 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 27%|██▋       | 163/606 [05:01<14:12,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 27%|██▋       | 164/606 [05:03<14:16,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_60.feather'] Failed Molecules: []

 27%|██▋       | 165/606 [05:05<14:19,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_60 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_60 for [2, 4]

Molecules Loaded: ['conf_60.feather'] Failed Molecules: []

 27%|██▋       | 166/606 [05:07<14:19,  1.95s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_60 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_60 for [2, 15]

Molecules Loaded: ['conf_94.feather'] Failed Molecules: []

 28%|██▊       | 167/606 [05:09<14:26,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_94 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_94 for [2, 4]

Molecules Loaded: ['conf_94.feather'] Failed Molecules: []

 28%|██▊       | 168/606 [05:11<14:37,  2.00s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_94 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_94 for [2, 15]

Molecules Loaded: ['conf_58.feather'] Failed Molecules: []

 28%|██▊       | 169/606 [05:13<14:33,  2.00s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_58 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_58 for [2, 4]

Molecules Loaded: ['conf_58.feather'] Failed Molecules: []

 28%|██▊       | 170/606 [05:15<14:32,  2.00s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_58 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_58 for [2, 4]

Molecules Loaded: ['conf_93.feather'] Failed Molecules: []

 28%|██▊       | 171/606 [05:17<14:25,  1.99s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_93 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_93 for [2, 4]

Molecules Loaded: ['conf_93.feather'] Failed Molecules: []

 28%|██▊       | 172/606 [05:19<14:17,  1.98s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_93 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_93 for [2, 4]

Molecules Loaded: ['conf_67.feather'] Failed Molecules: []

 29%|██▊       | 173/606 [05:21<14:14,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_67 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_67 for [2, 4]

Molecules Loaded: ['conf_67.feather'] Failed Molecules: []

 29%|██▊       | 174/606 [05:23<14:00,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_67 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_67 for [2, 4]

Molecules Loaded: ['conf_51.feather'] Failed Molecules: []

 29%|██▉       | 175/606 [05:25<13:56,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_51 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_51 for [2, 4]

Molecules Loaded: ['conf_51.feather'] Failed Molecules: []

 29%|██▉       | 176/606 [05:27<14:09,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_51 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_51 for [2, 4]

Molecules Loaded: ['conf_69.feather'] Failed Molecules: []

 29%|██▉       | 177/606 [05:29<14:11,  1.98s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_69 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_69 for [2, 4]

Molecules Loaded: ['conf_69.feather'] Failed Molecules: []

 29%|██▉       | 178/606 [05:31<14:04,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_69 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_69 for [2, 4]

Molecules Loaded: ['conf_56.feather'] Failed Molecules: []

 30%|██▉       | 179/606 [05:33<13:51,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_56 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_56 for [2, 4]

Molecules Loaded: ['conf_56.feather'] Failed Molecules: []

 30%|██▉       | 180/606 [05:35<13:53,  1.96s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_56 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_56 for [2, 4]

Molecules Loaded: ['conf_35.feather'] Failed Molecules: []

 30%|██▉       | 181/606 [05:37<13:46,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_35 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_35 for [2, 4]

Molecules Loaded: ['conf_35.feather'] Failed Molecules: []

 30%|███       | 182/606 [05:39<13:33,  1.92s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_35 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_35 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 30%|███       | 183/606 [05:41<13:42,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 30%|███       | 184/606 [05:43<13:52,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_32.feather'] Failed Molecules: []

 31%|███       | 185/606 [05:45<13:42,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_32 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_32 for [2, 4]

Molecules Loaded: ['conf_32.feather'] Failed Molecules: []

 31%|███       | 186/606 [05:47<13:35,  1.94s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_32 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_32 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 31%|███       | 187/606 [05:49<13:38,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 31%|███       | 188/606 [05:51<13:41,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_68.feather'] Failed Molecules: []

 31%|███       | 189/606 [05:53<13:43,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_68 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_68 for [2, 4]

Molecules Loaded: ['conf_68.feather'] Failed Molecules: []

 31%|███▏      | 190/606 [05:55<13:33,  1.96s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_68 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_68 for [2, 15]

Molecules Loaded: ['conf_57.feather'] Failed Molecules: []

 32%|███▏      | 191/606 [05:56<13:29,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_57 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_57 for [2, 4]

Molecules Loaded: ['conf_57.feather'] Failed Molecules: []

 32%|███▏      | 192/606 [05:58<13:25,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_57 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_57 for [2, 4]

Molecules Loaded: ['conf_50.feather'] Failed Molecules: []

 32%|███▏      | 193/606 [06:00<13:17,  1.93s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_50 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_50 for [2, 4]

Molecules Loaded: ['conf_50.feather'] Failed Molecules: []

 32%|███▏      | 194/606 [06:02<13:24,  1.95s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_50 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_50 for [2, 4]

Molecules Loaded: ['conf_59.feather'] Failed Molecules: []

 32%|███▏      | 195/606 [06:04<13:24,  1.96s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_59 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_59 for [2, 4]

Molecules Loaded: ['conf_59.feather'] Failed Molecules: []

 32%|███▏      | 196/606 [06:06<13:26,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_59 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_59 for [2, 4]

Molecules Loaded: ['conf_66.feather'] Failed Molecules: []

 33%|███▎      | 197/606 [06:08<13:26,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_66 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_66 for [2, 4]

Molecules Loaded: ['conf_66.feather'] Failed Molecules: []

 33%|███▎      | 198/606 [06:10<13:37,  2.00s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_66 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_66 for [2, 4]

Molecules Loaded: ['conf_92.feather'] Failed Molecules: []

 33%|███▎      | 199/606 [06:12<13:33,  2.00s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_92 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_92 for [2, 4]

Molecules Loaded: ['conf_92.feather'] Failed Molecules: []

 33%|███▎      | 200/606 [06:14<13:21,  1.97s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_92 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_92 for [2, 4]

Molecules Loaded: ['conf_95.feather'] Failed Molecules: []

 33%|███▎      | 201/606 [06:16<13:20,  1.98s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_95 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_95 for [2, 4]

Molecules Loaded: ['conf_95.feather'] Failed Molecules: []

 33%|███▎      | 202/606 [06:18<13:13,  1.96s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_95 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_95 for [2, 4]

Molecules Loaded: ['conf_61.feather'] Failed Molecules: []

 33%|███▎      | 203/606 [06:20<13:08,  1.96s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_61 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_61 for [2, 4]

Molecules Loaded: ['conf_61.feather'] Failed Molecules: []

 34%|███▎      | 204/606 [06:22<13:07,  1.96s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_61 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_61 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 34%|███▍      | 205/606 [06:23<11:03,  1.66s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 34%|███▍      | 206/606 [06:24<09:38,  1.45s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 34%|███▍      | 207/606 [06:25<08:33,  1.29s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Molecules Loaded: ['conf_2.feather'] Failed Molecules: []

 34%|███▍      | 208/606 [06:26<07:55,  1.19s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 15], [15, 6], [2, 4], [2, 15], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_2 for [2, 15]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 34%|███▍      | 209/606 [06:27<07:24,  1.12s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_3.feather'] Failed Molecules: []

 35%|███▍      | 210/606 [06:28<07:18,  1.11s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_3 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 35%|███▍      | 211/606 [06:29<07:05,  1.08s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_4.feather'] Failed Molecules: []

 35%|███▍      | 212/606 [06:30<06:55,  1.05s/it]

Calculating stretch vibration for atoms [[6, 15], [15, 6], [5, 4], [4, 5], [2, 15], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 15]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_4 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 35%|███▌      | 213/606 [06:31<06:54,  1.06s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_1.feather'] Failed Molecules: []

 35%|███▌      | 214/606 [06:32<07:00,  1.07s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_1 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 35%|███▌      | 215/606 [06:33<07:12,  1.11s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Molecules Loaded: ['conf_6.feather'] Failed Molecules: []

 36%|███▌      | 216/606 [06:34<07:11,  1.11s/it]

Calculating stretch vibration for atoms [[5, 4], [4, 5], [6, 13], [13, 6], [2, 4], [2, 13], [2, 1], [2, 3], [5, 6], [6, 5]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 4]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_6 for [2, 13]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 36%|███▌      | 217/606 [06:36<07:18,  1.13s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_7.feather'] Failed Molecules: []

 36%|███▌      | 218/606 [06:37<07:21,  1.14s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_7 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 36%|███▌      | 219/606 [06:38<07:20,  1.14s/it]

Calculating stretch vibration for atoms [[6, 13], [13, 6], [5, 4], [4, 5], [2, 13], [2, 4], [2, 1], [2, 3], [6, 5], [5, 6]] with threshold 1400
 Remember : ALWAYS LOOK AT THE RESULTING VIBRATION
Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 13]

Strech Vibration Error: the following bonds do not exist-check atom numbering in molecule:
 conf_5 for [2, 4]

Molecules Loaded: ['conf_5.feather'] Failed Molecules: []

 36%|███▋      | 220/606 [06:39<07:22,  1.15s/it]

# Combining ORCA and DescriPyTor descriptors

In [ ]:
import re

# --- 1) Build merge key (conf folder) for total_df ---
total_work = total_df.drop(columns=atoms).copy()

def _normalize_conf_dir(p):
    if pd.isna(p):
        return np.nan
    p = str(p).replace("\\", "/")
    if p.endswith(".feather"):
        p = os.path.dirname(p)
    p = p.rstrip("/")
    p = re.sub(r"^orca_descriptors/", "", p)  # align with df_desc paths
    return p

total_work["conf_dir"] = total_work["path"].map(_normalize_conf_dir)

# --- 2) Build merge key for df_desc ---
desc_work = df_desc.copy()
if "feather_dir" not in desc_work.columns:
    raise KeyError("df_desc must contain 'feather_dir'.")

desc_work["conf_dir"] = desc_work["feather_dir"].map(_normalize_conf_dir)

# --- 3) Combine descriptor tables ---
combined_df = total_work.merge(
    desc_work,
    on="conf_dir",
    how="outer",
    suffixes=("_total", "_desc")
)

# If duplicate energy columns exist, keep one unified SCF_energy
if "SCF_energy" not in combined_df.columns:
    scf_candidates = [c for c in combined_df.columns if c.startswith("SCF_energy")]
    if scf_candidates:
        combined_df["SCF_energy"] = combined_df[scf_candidates].bfill(axis=1).iloc[:, 0]

# --- 4) Group key = inchi folder (path without /conf_XX) ---
combined_df["inchi_folder"] = combined_df["conf_dir"].str.replace(
    r"/conf_\d+$", "", regex=True
)

# --- 5) Boltzmann aggregation per inchi folder ---
T = 298.15
kB_hartree_per_K = 3.166811563e-6  # Hartree/K

if "SCF_energy" not in combined_df.columns:
    raise KeyError("SCF_energy column not found after merge.")

numeric_cols = combined_df.select_dtypes(include=[np.number]).columns.tolist()

rows = []
for inchi_folder, g in combined_df.groupby("inchi_folder", dropna=True):
    g = g.copy()
    e = pd.to_numeric(g["SCF_energy"], errors="coerce")
    if e.notna().sum() == 0:
        continue

    e_min = e.min()
    idx_low = e.idxmin()

    dE = e - e_min
    w = np.exp(-(dE / (kB_hartree_per_K * T)))
    w = w / np.nansum(w)

    out = {
        "inchi_folder": inchi_folder,
        "inchi": os.path.basename(inchi_folder),
        "min_energy_value": e_min,
        "smiles": g["smiles"].iloc[0] if "smiles" in g.columns else np.nan,
        "ligand_class": g["ligand_class"].iloc[0] if "ligand_class" in g.columns else np.nan
    }

    for col in numeric_cols:
        v = pd.to_numeric(g[col], errors="coerce")

        out[f"{col}_min"] = v.min()
        out[f"{col}_max"] = v.max()
        out[f"{col}_lowE"] = g.loc[idx_low, col] if idx_low in g.index else np.nan

        valid = v.notna() & w.notna()
        out[f"{col}_boltz"] = (
            np.average(v[valid], weights=w[valid]) if valid.any() else np.nan
        )

    rows.append(out)

df_boltzmann_summary = pd.DataFrame(rows).sort_values("inchi_folder").reset_index(drop=True)
df_boltzmann_summary.drop(columns=["min_energy_value"], inplace=True)

print("combined_df shape:", combined_df.shape)
print("df_boltzmann_summary shape:", df_boltzmann_summary.shape)
df_boltzmann_summary.head()

### Remove noisy descriptors

In [ ]:
import importlib
import desc_utils.data_extraction as de

importlib.reload(de)

from desc_utils.data_extraction import filter_numeric_descriptors

df_num_desc_filtered, report = filter_numeric_descriptors(
    df_boltzmann_summary,
    remove_low_occupancy_nbo=True,
    occupancy_boltz_threshold=0.001,
    corr_threshold=0.95,
    corr_pruning_mode="bridge_star_centers", #"component_ranked",
    ratio_threshold=0.01,
    orbital_filter="remove rydbergs",
    cor_orbital_filter="remove cor",
    ni_orbital_filter="remove 4f rydbergs",    # new filter
    nmr_filter="remove aniso",
    bond_analysis_filter="remove phi theta",
)

print("Initial numeric descriptors:", report["initial_numeric_count"])
print("Removed (NBO low occupancy orbitals):", len(report["removed_low_occ_nbo_orbitals"]))
print("Removed (NBO low occupancy columns):", len(report["removed_low_occ_nbo_columns"]))
print("Removed (Rydberg, except Ni):", len(report["removed_rydberg"]))
print("Removed (Ni 4f Rydbergs):", len(report["removed_ni_4f_rydberg"]))
print("Removed (NMR aniso):", len(report["removed_nmr_aniso"]))
print("Removed (phi/theta bond analysis):", len(report["removed_phi_theta"]))
print("Removed (zero std):", len(report["removed_zero_std"]))
print("Removed (std/abs(mean) < 1%):", len(report["removed_low_ratio"]))
print("Removed (high correlation):", len(report["removed_high_corr"]))
print("Final numeric descriptors:", report["final_numeric_count"])

# filter_numeric_descriptors returns only numeric columns, so re-attach meta columns from df_boltzmann_summary
meta_cols = ["smiles", "inchi", "inchi_folder", "ligand_class"]
for col in meta_cols:
    if col in df_boltzmann_summary.columns:
        df_num_desc_filtered[col] = df_boltzmann_summary[col].values

df_num_desc_filtered.head()

In [ ]:
# save to csv
from datetime import datetime
output_csv_path = datetime.now().strftime("%Y%m%d") + "_" + src_dir.split('/')[-1] + "_descriptors_" + ".csv"
df_num_desc_filtered.to_csv(output_csv_path, index=False)